import { showToast } from './state.js';

// The FIT parser and its Buffer polyfill are VENDORED locally
// (js/vendor/fit-parser.js, regenerated by scripts/vendor-fit.mjs) rather than
// loaded from a CDN. This is deliberate:
//   1. Security: the previous version fetched the parser from a third-party CDN
//      at runtime, pulling executable code into the privileged Android WebView —
//      a remote-code-execution surface — and was in any case blocked by the app
//      CSP (script-src 'self' cdn.jsdelivr.net), so FIT import was broken as
//      shipped. The local bundle runs from our own origin, offline, no 3rd-party code.
//   2. Resilience/startup: still imported LAZILY (only when a .FIT is picked) so
//      the ~290 KB bundle never sits on the boot path.
let _fitDepsPromise = null;
function loadFitDeps() {
  if (!_fitDepsPromise) {
    _fitDepsPromise = import('./vendor/fit-parser.js')
      .then(({ FitParser, Buffer }) => {
        if (typeof window !== 'undefined' && !window.Buffer) window.Buffer = Buffer;
        return { Buffer, FitParser };
      })
      .catch((err) => {
        _fitDepsPromise = null; // let the next attempt retry
        throw err;
      });
  }
  return _fitDepsPromise;
}

export function initGarminRunImport(onDataExtracted) {
  setupUploader('fitUpload', true, onDataExtracted);
}

export function initGarminGymImport(onDataExtracted) {
  setupUploader('fitGymUpload', false, onDataExtracted);
}

function setupUploader(inputId, isRun, onDataExtracted) {
  const uploadInput = document.getElementById(inputId);
  if (!uploadInput) return;

  uploadInput.addEventListener('change', (event) => {
    const file = event.target.files[0];
    if (!file) return;

    event.target.value = ''; 

    showToast('Parsing Garmin file...');

    const reader = new FileReader();

    reader.onload = async (e) => {
      let Buffer, FitParser;
      try {
        ({ Buffer, FitParser } = await loadFitDeps());
      } catch (depErr) {
        showToast('Could not load the FIT parser — check your connection and try again.', true);
        return;
      }
      try {
        const arrayBuffer = e.target.result;
        const nodeBuffer = Buffer.from(arrayBuffer);

        const fitParser = new FitParser({
          force: true,
          speedUnit: 'km/h',
          lengthUnit: 'km',
          elapsedRecordField: true,
          mode: 'list', 
        });

        fitParser.parse(nodeBuffer, async (error, data) => {
          if (error) {
            showToast('Parse error: ' + error.toString().slice(0, 60), true);
            return;
          }
          try {
            await extractData(data, isRun, onDataExtracted);
          } catch (e) {
            showToast('FIT import failed: ' + String(e).slice(0, 60), true);
          }
        });

      } catch (fatalError) {
        showToast('FIT import failed: ' + fatalError.toString().slice(0, 60), true);
      }
    };

    reader.readAsArrayBuffer(file);
  });
}

// ── Pure extraction (exported, DOM-free, so the FIT field contract can be
//    unit-tested against fixtures without a device or the parser). ───────────

/** A finite number, or null. Guards against NaN/undefined/strings. */
function num(v) { return (typeof v === 'number' && isFinite(v)) ? v : null; }

/** First present (non-null/undefined) value among the EXACT keys, else undefined. */
function pickExact(session, names) {
  for (const n of names) {
    if (session[n] !== undefined && session[n] !== null) return session[n];
  }
  return undefined;
}

/**
 * Exact-key numeric lookup with a plausible range; null when absent, non-numeric,
 * or out of range. Exact keys are essential: FIT's aerobic
 * `total_training_effect` and anaerobic `total_anaerobic_training_effect` share
 * the `training_effect` substring, so a loose (includes) match let one capture
 * the other's value depending on key order. No fake `0` default either — a
 * missing field stays null instead of masquerading as a real reading.
 */
function pickNum(session, names, min, max) {
  const v = num(pickExact(session, names));
  if (v === null) return null;
  return (v >= min && v <= max) ? v : null;
}

function findSession(garminData, isRun) {
  if (Array.isArray(garminData.sessions) && garminData.sessions.length > 0) return garminData.sessions[0];
  if (garminData.session) {
    return Array.isArray(garminData.session) ? (garminData.session[0] || null) : garminData.session;
  }
  let found = null;
  (function search(data) {
    if (found) return;
    if (Array.isArray(data)) { for (const it of data) { search(it); if (found) return; } return; }
    if (data && typeof data === 'object') {
      const hasTime = data.total_timer_time !== undefined || data.total_elapsed_time !== undefined;
      const hasDist = data.total_distance !== undefined;
      const hasCals = data.total_calories !== undefined;
      if (isRun && hasDist && hasTime) { found = data; return; }
      if (!isRun && hasTime && hasCals) { found = data; return; }
      for (const k in data) { search(data[k]); if (found) return; }
    }
  })(garminData);
  return found;
}

/**
 * A millisecond epoch from whatever the parser produced, or null.
 * The vendored fit-parser converts FIT timestamps to real `Date` objects, but
 * fixtures and older exports can carry an ISO string or a bare epoch.
 */
function toTs(value) {
  if (value == null) return null;
  if (value instanceof Date) {
    const t = value.getTime();
    return Number.isFinite(t) ? t : null;
  }
  if (typeof value === 'number') return Number.isFinite(value) && value > 0 ? value : null;
  if (typeof value === 'string') {
    const t = Date.parse(value);
    return Number.isFinite(t) ? t : null;
  }
  return null;
}

/** Plausible activity window — guards against a garbled epoch or a device clock
 *  left in 1989. Anything outside is treated as "no usable timestamp" rather
 *  than silently dating an import decades away. */
const TS_MIN = Date.UTC(2000, 0, 1);
const tsMax = () => Date.now() + 2 * 86400000;

/**
 * When the activity actually STARTED, in ms.
 *
 * This is the field that decides which calendar day an imported run belongs to.
 * Without it the app dated every import to whichever day the cockpit happened to
 * be showing, so a run done last Tuesday landed on today and every date-strict
 * analytic inherited the wrong day.
 *
 * `start_time` is preferred. A FIT session's `timestamp` is the END of the
 * activity, so it is only used as a fallback with the duration subtracted.
 */
export function sessionStartTs(session, durationSeconds = 0) {
  if (!session || typeof session !== 'object') return null;
  const inWindow = (t) => (t != null && t >= TS_MIN && t <= tsMax() ? t : null);

  const explicit = inWindow(toTs(pickExact(session, ['start_time', 'startTime'])));
  if (explicit) return explicit;

  const end = inWindow(toTs(pickExact(session, ['timestamp'])));
  if (end == null) return null;
  const secs = num(durationSeconds) || 0;
  return secs > 0 ? end - Math.round(secs * 1000) : end;
}

function formatDuration(seconds) {
  const s = num(seconds) || 0;
  const mins = Math.floor(s / 60);
  const secs = Math.floor(s % 60);
  return `${mins}:${secs.toString().padStart(2, '0')}`;
}

/**
 * Pure FIT → app-stats mapper. Returns a structured result instead of touching
 * the DOM/toasts, so the contract is testable. The parser is configured with
 * `lengthUnit: 'km'`, so `total_distance` is already kilometres.
 * @returns {{ ok:false, reason:string }
 *   | { ok:true, isRun:boolean, distanceKm:number, time:string, coordinates:number[][], stats:object }}
 */
export function extractSessionStats(garminData, isRun) {
  if (!garminData || typeof garminData !== 'object') return { ok: false, reason: 'empty' };
  const session = findSession(garminData, isRun);
  if (!session || typeof session !== 'object') return { ok: false, reason: 'no-session' };

  const distanceKm = num(session.total_distance) || 0;
  const durationSeconds = num(session.total_timer_time) ?? num(session.total_elapsed_time) ?? 0;

  const stats = {
    avgHR:      pickNum(session, ['avg_heart_rate', 'avg_hr', 'average_heart_rate'], 20, 260),
    maxHR:      pickNum(session, ['max_heart_rate', 'max_hr', 'maximum_heart_rate'], 20, 260),
    elevation:  pickNum(session, ['total_ascent', 'ascent'], 0, 100000),
    descent:    pickNum(session, ['total_descent', 'descent'], 0, 100000),
    calories:   pickNum(session, ['total_calories', 'calories'], 0, 100000),
    avgCadence: pickNum(session, ['avg_running_cadence', 'avg_cadence', 'average_cadence'], 0, 300),
    // Aerobic Training Effect — FIT `total_training_effect` (0–5).
    trainingEffect: pickNum(session, ['total_training_effect', 'total_aerobic_training_effect'], 0, 5),
    // Anaerobic Training Effect — FIT `total_anaerobic_training_effect` (0–5).
    // This is exactly what the UI's "Anaerobic TE" field displays.
    anaerobicTE:    pickNum(session, ['total_anaerobic_training_effect', 'total_anaerobic_effect'], 0, 5),
    hrZones: Array.isArray(session.time_in_hr_zone) ? session.time_in_hr_zone : null,
    // When the activity actually happened. Decides the calendar day the import
    // is attributed to, and doubles as the identity used to refuse a re-import.
    // Null when the file carries no usable timestamp — callers then fall back to
    // the existing slot-date behaviour rather than inventing a date.
    startTs: sessionStartTs(session, durationSeconds),
  };

  // Laps → run splits or gym sets.
  const laps = Array.isArray(garminData.laps) ? garminData.laps
    : (garminData.activity && Array.isArray(garminData.activity.laps) ? garminData.activity.laps : []);
  const splits = [];
  const gymSets = [];
  laps.forEach((lap, i) => {
    if (!lap || typeof lap !== 'object') return;
    if (isRun) {
      splits.push({
        lap: i + 1,
        time: num(lap.total_timer_time) ?? num(lap.total_elapsed_time) ?? 0,
        dist: num(lap.total_distance) || 0,
        avgHR: num(lap.avg_heart_rate) || 0,
      });
    } else if (num(lap.total_reps)) {
      gymSets.push({ set: i + 1, reps: lap.total_reps, weight: num(lap.weight) || 0, category: lap.category || 'Lifting' });
    }
  });
  stats.splits = splits.length ? splits : null;
  stats.gymSets = gymSets.length ? gymSets : null;

  // Records → GPS coordinates (semicircle→degree) + manual HR fallback.
  const records = Array.isArray(garminData.records) ? garminData.records
    : (garminData.activity && Array.isArray(garminData.activity.records) ? garminData.activity.records : []);
  const coordinates = [];
  let hrSum = 0, hrCnt = 0, hrMax = 0;
  for (const rec of records) {
    if (!rec || typeof rec !== 'object') continue;
    if (isRun && rec.position_lat != null && rec.position_long != null) {
      let lat = num(rec.position_lat), lng = num(rec.position_long);
      if (lat !== null && lng !== null) {
        if (Math.abs(lat) > 180) lat = lat * (180.0 / 2147483648.0);
        if (Math.abs(lng) > 180) lng = lng * (180.0 / 2147483648.0);
        coordinates.push([lat, lng]);
      }
    }
    const hr = num(rec.heart_rate);
    if (hr !== null && hr > 0) { hrSum += hr; hrCnt++; if (hr > hrMax) hrMax = hr; }
  }
  if (stats.avgHR === null && hrCnt > 0) stats.avgHR = hrSum / hrCnt;
  if (stats.maxHR === null && hrMax > 0) stats.maxHR = hrMax;

  return { ok: true, isRun, distanceKm, time: formatDuration(durationSeconds), coordinates, stats };
}

/**
 * Thin wrapper: run the pure extractor, hand the result to the destination save
 * (`onDataExtracted`), and ONLY report success once that save has actually
 * completed. `onDataExtracted` may be async and returns a truthy value on a
 * confirmed save; returning `false` (or throwing) surfaces an honest failure
 * instead of a false "Imported ✓". `toast` is injectable for tests.
 */
export async function extractData(garminData, isRun, onDataExtracted, toast = showToast) {
  const result = extractSessionStats(garminData, isRun);
  if (!result.ok) {
    toast(`Could not find ${isRun ? 'run' : 'gym'} data in this file.`, true);
    return false;
  }
  let saved;
  try {
    saved = isRun
      ? await onDataExtracted(result.distanceKm.toFixed(2), result.time, result.coordinates, result.stats)
      : await onDataExtracted(result.time, result.stats);
  } catch (err) {
    saved = false;
  }
  // `{ handled: true }` means the destination deliberately declined and has
  // already explained why (a re-import of an activity already logged). That is
  // not a failure, and re-toasting "Import failed" over the real reason would
  // replace a specific message with a wrong generic one.
  if (saved && typeof saved === 'object' && saved.handled) return false;
  if (saved === false) {
    toast('Import failed — nothing was saved.', true);
    return false;
  }
  toast('Garmin Imported! ✓');
  return true;
}
