// =============================================================================
// PROGRAM CATALOG — Rich metadata layer for the HybridHQ Program Library
// This is the source of truth for discovery, search, filtering, recommendations.
// Workout execution data lives in js/constants.js (PROGRAMS object) — preserved.
// =============================================================================

export const CATEGORIES = {
  hybrid:          { label: 'Hybrid',           icon: '⚡', color: '#8b5cf6' },
  strength:        { label: 'Strength',          icon: '🏋️', color: '#ef4444' },
  hypertrophy:     { label: 'Hypertrophy',       icon: '💪', color: '#3b82f6' },
  powerlifting:    { label: 'Powerlifting',      icon: '🔱', color: '#dc2626' },
  running:         { label: 'Running',           icon: '🏃', color: '#22d3ee' },
  hyrox:           { label: 'Hyrox',             icon: '🏟️', color: '#7c3aed' },
  endurance:       { label: 'Endurance',         icon: '🫀', color: '#10b981' },
  body_composition:{ label: 'Body Composition',  icon: '🔥', color: '#f59e0b' },
  general_fitness: { label: 'General Fitness',   icon: '🎯', color: '#06b6d4' },
  tactical:        { label: 'Tactical',          icon: '🎖️', color: '#84cc16' },
};

export const DIFFICULTY_LABELS = {
  beginner:     { label: 'Beginner',     dots: 1, color: '#10b981' },
  intermediate: { label: 'Intermediate', dots: 2, color: '#f59e0b' },
  advanced:     { label: 'Advanced',     dots: 3, color: '#ef4444' },
  elite:        { label: 'Elite',        dots: 4, color: '#dc2626' },
};

// Programs with IDs matching constants.js PROGRAMS keys will use existing workout data.
// New programs include representative day structures for execution.

export const PROGRAM_CATALOG = [

  // ── HYBRID ────────────────────────────────────────────────────────────────

  {
    id: 'hybridhq_foundations',
    name: 'HybridHQ Foundations',
    tagline: 'The definitive starting point for hybrid athletes',
    description: 'A 12-week program designed specifically for athletes who want to build a serious base of strength, muscle, and aerobic capacity simultaneously. Progressive overload drives strength gains while structured running blocks develop your aerobic engine.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'hybrid',
    subcategory: 'strength-endurance',
    tags: ['hybrid', 'strength', 'running', 'concurrent', 'beginner-hybrid', 'barbell', 'zone2'],
    durationWeeks: 12,
    sessionsPerWeek: 5,
    sessionDurationMinutes: { min: 50, max: 70 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells'],
    equipmentTier: 'gym',
    goals: ['strength', 'fitness', 'running', 'general-health'],
    metrics: { strengthEmphasis: 70, hypertrophyEmphasis: 45, enduranceEmphasis: 55, conditioningEmphasis: 40, recoveryDemand: 60, weeklyVolumeScore: 65 },
    highlights: ['5-day/week structure', 'Concurrent strength + running', 'Progressive overload built-in', 'Deload weeks included'],
    expectedOutcomes: ['Improved 5K time', 'Strength gains on main lifts', 'Better body composition', 'Aerobic base development'],
    popularity: 95, rating: 4.8, ratingCount: 312, completionRate: 0.61, enrolledCount: 2840,
    featured: true, verified: true, isNew: false,
    coverGradient: ['#1a0e2e', '#2d1a5c'], accentColor: '#8b5cf6', icon: '⚡',
    collections: ['featured', 'hybridhq-picks', 'hybrid-collection', 'recommended-starters', 'most-popular'],
    days: {
      mon: { title: 'Strength A', badge: 'Push + Pull', color: 'var(--accent-blue)', desc: 'Full body strength focus. Bench, Row, Squat.', runs: 'Rest', lifts: ['Bench Press', 'Barbell Row', 'Back Squat', 'Lateral Raise', 'Hammer Curl'] },
      tue: { title: 'Intervals + Arms', badge: 'Run + Accessory', color: 'var(--accent-pink)', desc: 'Track intervals followed by arm work.', runs: '⚡ 6×800m (90s recovery)', lifts: ['Pull-Ups', 'Incline DB Press', 'Barbell Curl', 'Tricep Band Pushdown'] },
      wed: { title: 'Strength B', badge: 'Lower + Pull', color: 'var(--accent-green)', desc: 'Lower body focus. Deadlift, Romanian DL.', runs: 'Rest', lifts: ['Deadlift', 'Romanian Deadlift', 'Bulgarian Split Squat', 'Calf Raises', 'Face Pull'] },
      thu: { title: 'Tempo Run', badge: 'Threshold', color: 'var(--accent-amber)', desc: 'Sustained effort at lactate threshold.', runs: '🔥 Tempo: 4×8 min @ threshold pace (2min rest)', lifts: [] },
      fri: { title: 'Strength C', badge: 'Upper Body', color: 'var(--accent-blue)', desc: 'OHP, chin-ups, accessories.', runs: 'Rest', lifts: ['Standing OHP', 'Chin-Ups', 'Seated DB Shoulder Press', 'Rear Delt Fly', 'Incline DB Curl'] },
      sat: { title: 'Long Run', badge: 'Zone 2', color: 'var(--accent-pink)', desc: 'Easy aerobic long run. Conversational pace.', runs: 'Zone 2 Long Run: 50-70 min', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest. Sleep, eat, recover.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 8, intensityLabel: 'Foundation Block' }, '2': { sets: 3, reps: 8, intensityLabel: 'Foundation Block' },
      '3': { sets: 4, reps: 6, intensityLabel: 'Build Block' }, '4': { sets: 2, reps: 8, intensityLabel: 'Deload' },
      '5': { sets: 4, reps: 6, intensityLabel: 'Strength Block' }, '6': { sets: 4, reps: 5, intensityLabel: 'Strength Block' },
      '7': { sets: 4, reps: 5, intensityLabel: 'Strength Block' }, '8': { sets: 2, reps: 6, intensityLabel: 'Deload' },
      '9': { sets: 4, reps: 4, intensityLabel: 'Peak Block' }, '10': { sets: 4, reps: 4, intensityLabel: 'Peak Block' },
      '11': { sets: 4, reps: 3, intensityLabel: 'Peak Block' }, '12': { sets: 2, reps: 5, intensityLabel: 'Taper' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Strength & Endurance', philosophy: 'Build strength and aerobic capacity concurrently using evidence-based concurrent training principles.' },
  },

  {
    id: 'hybrid_engine',
    name: 'Sub-20 5K Hybrid Engine',
    tagline: 'Break 20 minutes while building serious strength',
    description: 'A 9-week racing protocol that pushes your 5K pace below 20 minutes while maintaining maximal strength. Combines base accumulation, lactate threshold intervals, and heavy compound lifting.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'hybrid',
    subcategory: 'running-strength',
    tags: ['hybrid', '5k', 'running', 'strength', 'sub20', 'intervals', 'tempo', 'zone2'],
    durationWeeks: 9,
    sessionsPerWeek: 6,
    sessionDurationMinutes: { min: 50, max: 75 },
    difficulty: 'advanced',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells'],
    equipmentTier: 'gym',
    goals: ['5k-performance', 'strength', 'hybrid-fitness'],
    metrics: { strengthEmphasis: 75, hypertrophyEmphasis: 35, enduranceEmphasis: 80, conditioningEmphasis: 70, recoveryDemand: 85, weeklyVolumeScore: 80 },
    highlights: ['9-week racing protocol', 'Sub-20 5K focus', 'Heavy compound lifts', 'Interval + tempo structure'],
    expectedOutcomes: ['Sub-20 minute 5K', 'Improved lactate threshold', 'Maintained strength', 'Increased VO2max'],
    popularity: 88, rating: 4.7, ratingCount: 189, completionRate: 0.48, enrolledCount: 1620,
    featured: true, verified: true, isNew: false,
    coverGradient: ['#0d1b2a', '#1b4332'], accentColor: '#22d3ee', icon: '🏃',
    collections: ['featured', 'hybridhq-picks', 'hybrid-collection', 'running-collection', 'most-popular'],
  },

  {
    id: 'hybrid_strength_5k',
    name: 'Hybrid Strength & 5K Builder',
    tagline: 'Build muscle and run faster — no compromise',
    description: 'A 12-week strength-first hybrid program that builds real muscle while systematically improving your 5K performance. Prioritises compound strength movements with progressive overload across every training block.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'hybrid',
    subcategory: 'strength-running',
    tags: ['hybrid', 'strength', '5k', 'running', 'concurrent', 'muscle', 'push-pull-legs'],
    durationWeeks: 12,
    sessionsPerWeek: 6,
    sessionDurationMinutes: { min: 55, max: 80 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells'],
    equipmentTier: 'gym',
    goals: ['strength', 'running', 'muscle', 'hybrid-fitness'],
    metrics: { strengthEmphasis: 80, hypertrophyEmphasis: 55, enduranceEmphasis: 60, conditioningEmphasis: 45, recoveryDemand: 75, weeklyVolumeScore: 75 },
    highlights: ['Strength-first approach', 'PPL structure with running', 'Progressive overload emphasis', '12-week transformation'],
    expectedOutcomes: ['Significant strength gains', 'Faster 5K pace', 'Improved body composition', 'Better work capacity'],
    popularity: 82, rating: 4.6, ratingCount: 143, completionRate: 0.55, enrolledCount: 1240,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0e2e', '#0d3b2e'], accentColor: '#10b981', icon: '⚡',
    collections: ['hybrid-collection', 'hybridhq-picks', 'most-popular'],
  },

  {
    id: 'jacked_and_tan_2',
    name: 'GZCL: Jacked & Tan 2.0',
    tagline: 'Cody Lefever\'s legendary powerbuilding wave',
    description: 'A brutal 12-week powerbuilding program. Each week you hunt a new Rep Max before dropping into high-volume back-off sets. Three distinct waves build absolute strength and conditioning simultaneously.',
    author: { name: 'Cody Lefever (GZCL)', type: 'coach', verified: true },
    category: 'hybrid',
    subcategory: 'powerbuilding',
    tags: ['gzcl', 'powerbuilding', 'strength', 'hypertrophy', 'rep-max', 'advanced', 'barbell'],
    durationWeeks: 12,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 75, max: 105 },
    difficulty: 'advanced',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells'],
    equipmentTier: 'gym',
    goals: ['strength', 'powerbuilding', 'muscle'],
    metrics: { strengthEmphasis: 85, hypertrophyEmphasis: 65, enduranceEmphasis: 10, conditioningEmphasis: 20, recoveryDemand: 80, weeklyVolumeScore: 85 },
    highlights: ['Weekly Rep Max hunting', 'GZCL methodology', 'Strength + volume waves', 'Community favourite'],
    expectedOutcomes: ['New strength PRs', 'Significant muscle gain', 'Improved work capacity', 'Powerlifting total increase'],
    popularity: 91, rating: 4.8, ratingCount: 267, completionRate: 0.44, enrolledCount: 2100,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0a0a', '#3d1515'], accentColor: '#dc2626', icon: '🔱',
    collections: ['most-popular', 'highest-rated', 'hybrid-collection', 'strength-collection'],
  },

  {
    id: 'hyrox_foundations',
    name: 'Hyrox Foundations',
    tagline: 'Your first step toward Hyrox race day',
    description: 'A 12-week entry-level Hyrox preparation program. Builds the strength and conditioning base needed to complete a Hyrox race while developing familiarity with all 8 Hyrox stations.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'hyrox',
    subcategory: 'race-prep',
    tags: ['hyrox', 'hybrid', 'conditioning', 'strength', 'running', 'race-prep', 'beginner-hyrox'],
    durationWeeks: 12,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 50, max: 70 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'dumbbells', 'sled', 'ski-erg', 'rowing-machine', 'kettlebell'],
    equipmentTier: 'gym',
    goals: ['hyrox', 'race-completion', 'conditioning', 'strength'],
    metrics: { strengthEmphasis: 55, hypertrophyEmphasis: 25, enduranceEmphasis: 65, conditioningEmphasis: 80, recoveryDemand: 65, weeklyVolumeScore: 60 },
    highlights: ['All 8 Hyrox stations covered', 'Race-specific conditioning', 'Strength foundation', 'Beginner-friendly structure'],
    expectedOutcomes: ['Hyrox race completion', 'Improved work capacity', 'Functional strength', 'Conditioning base'],
    popularity: 87, rating: 4.7, ratingCount: 198, completionRate: 0.58, enrolledCount: 1890,
    featured: true, verified: true, isNew: false,
    coverGradient: ['#1a0e2e', '#2d1b69'], accentColor: '#7c3aed', icon: '🏟️',
    collections: ['featured', 'hyrox-collection', 'hybridhq-picks', 'most-popular'],
    days: {
      mon: { title: 'Strength A', badge: 'Lower Body', color: 'var(--accent-green)', desc: 'Squat, lunges, sled push prep.', runs: 'Rest', lifts: ['Back Squat', 'Romanian Deadlift', 'Bulgarian Split Squat', 'Calf Raises', 'Core/Plank'] },
      tue: { title: 'Conditioning A', badge: 'Hyrox Sim', color: 'var(--accent-amber)', desc: 'Hyrox station simulation + run.', runs: '🏃 Run 1km @ race pace + Ski Erg 500m + Row 500m', lifts: ['Deadlift'] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest or light mobility.', runs: 'Rest', lifts: [] },
      thu: { title: 'Strength B', badge: 'Upper Body', color: 'var(--accent-blue)', desc: 'Push, pull, core — functional strength.', runs: 'Rest', lifts: ['Bench Press', 'Pull-Ups', 'Standing OHP', 'Barbell Row', 'Hanging Leg Raises'] },
      fri: { title: 'Conditioning B', badge: 'Threshold', color: 'var(--accent-pink)', desc: 'Threshold running + burpee broad jumps.', runs: '🔥 3×1200m threshold + 3×10 burpee broad jumps', lifts: [] },
      sat: { title: 'Long + Stations', badge: 'Race Simulation', color: 'var(--accent-amber)', desc: 'Long run + multi-station simulation.', runs: '🏃 45-60min run + Farmer Carry + Wall Balls', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 10, intensityLabel: 'Base Phase' }, '2': { sets: 3, reps: 10, intensityLabel: 'Base Phase' },
      '3': { sets: 4, reps: 8, intensityLabel: 'Build Phase' }, '4': { sets: 2, reps: 10, intensityLabel: 'Deload' },
      '5': { sets: 4, reps: 8, intensityLabel: 'Conditioning Block' }, '6': { sets: 4, reps: 6, intensityLabel: 'Conditioning Block' },
      '7': { sets: 4, reps: 6, intensityLabel: 'Conditioning Block' }, '8': { sets: 2, reps: 8, intensityLabel: 'Deload' },
      '9': { sets: 4, reps: 5, intensityLabel: 'Race Prep Block' }, '10': { sets: 4, reps: 5, intensityLabel: 'Race Prep Block' },
      '11': { sets: 3, reps: 5, intensityLabel: 'Taper' }, '12': { sets: 2, reps: 5, intensityLabel: 'Race Week Taper' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Hyrox Race Preparation', philosophy: 'Systematic preparation for Hyrox through concurrent strength and conditioning development.' },
  },

  {
    id: 'hyrox_intermediate',
    name: 'Hyrox Intermediate Prep',
    tagline: 'Chase your Hyrox PB with structured periodisation',
    description: 'A 16-week intermediate Hyrox program for athletes who have completed a race and want to significantly improve their time. Features race-specific conditioning blocks, strength cycles, and a structured taper.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'hyrox',
    subcategory: 'race-prep',
    tags: ['hyrox', 'pb', 'race-prep', 'intermediate', 'conditioning', 'strength', 'intervals'],
    durationWeeks: 16,
    sessionsPerWeek: 5,
    sessionDurationMinutes: { min: 55, max: 80 },
    difficulty: 'advanced',
    equipment: ['barbell', 'dumbbells', 'sled', 'ski-erg', 'rowing-machine', 'kettlebell', 'sandbag'],
    equipmentTier: 'gym',
    goals: ['hyrox-pb', 'race-performance', 'conditioning'],
    metrics: { strengthEmphasis: 60, hypertrophyEmphasis: 20, enduranceEmphasis: 70, conditioningEmphasis: 90, recoveryDemand: 80, weeklyVolumeScore: 75 },
    highlights: ['16-week periodised plan', 'Race-simulation sessions', 'Strength + speed combination', 'Progressive taper'],
    expectedOutcomes: ['Hyrox PB', 'Improved race station times', 'Better running economy', 'Enhanced work capacity'],
    popularity: 79, rating: 4.6, ratingCount: 134, completionRate: 0.51, enrolledCount: 1120,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0e2e', '#2d1b69'], accentColor: '#a78bfa', icon: '🏟️',
    collections: ['hyrox-collection', 'hybridhq-picks'],
    days: {
      mon: { title: 'Strength Lower', badge: 'Leg Power', color: 'var(--accent-green)', desc: 'Sled prep, squat, lunges.', runs: 'Rest', lifts: ['Back Squat', 'Romanian Deadlift', 'Bulgarian Split Squat', 'Leg Press', 'Calf Raises'] },
      tue: { title: 'Conditioning + Run', badge: 'Race Sim', color: 'var(--accent-amber)', desc: 'Station sim + intervals.', runs: '⚡ 4×1km @ race pace + 4 Hyrox stations', lifts: ['Deadlift'] },
      wed: { title: 'Strength Upper', badge: 'Upper Power', color: 'var(--accent-blue)', desc: 'Pushing + pulling strength.', runs: 'Rest', lifts: ['Bench Press', 'Pull-Ups', 'Standing OHP', 'Barbell Row', 'Core/Plank'] },
      thu: { title: 'Threshold Run', badge: 'Tempo', color: 'var(--accent-pink)', desc: 'Sustained threshold effort.', runs: '🔥 2×20min threshold run (3min rest)', lifts: [] },
      fri: { title: 'Full Race Simulation', badge: 'Race Prep', color: 'var(--accent-amber)', desc: 'Race-distance sim with all stations.', runs: '🏟️ Full Hyrox simulation', lifts: [] },
      sat: { title: 'Long Zone 2', badge: 'Aerobic Base', color: 'var(--accent-pink)', desc: 'Easy long run for aerobic development.', runs: 'Zone 2: 60-90min easy', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 10, intensityLabel: 'Base' }, '2': { sets: 4, reps: 8, intensityLabel: 'Base' },
      '3': { sets: 4, reps: 8, intensityLabel: 'Build' }, '4': { sets: 2, reps: 10, intensityLabel: 'Deload' },
      '5': { sets: 4, reps: 6, intensityLabel: 'Strength Block' }, '6': { sets: 4, reps: 6, intensityLabel: 'Strength Block' },
      '7': { sets: 5, reps: 5, intensityLabel: 'Strength Block' }, '8': { sets: 2, reps: 8, intensityLabel: 'Deload' },
      '9': { sets: 4, reps: 5, intensityLabel: 'Race Conditioning' }, '10': { sets: 4, reps: 5, intensityLabel: 'Race Conditioning' },
      '11': { sets: 4, reps: 4, intensityLabel: 'Peak Block' }, '12': { sets: 4, reps: 4, intensityLabel: 'Peak Block' },
      '13': { sets: 3, reps: 5, intensityLabel: 'Taper Start' }, '14': { sets: 3, reps: 5, intensityLabel: 'Taper' },
      '15': { sets: 2, reps: 6, intensityLabel: 'Taper' }, '16': { sets: 1, reps: 5, intensityLabel: 'Race Week' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Hyrox Performance', philosophy: 'Periodised 16-week preparation designed to significantly improve Hyrox race time through concurrent strength and conditioning.' },
  },

  // ── STRENGTH ──────────────────────────────────────────────────────────────

  {
    id: 'stronglifts_5x5',
    name: 'StrongLifts 5×5',
    tagline: 'The internet\'s most popular beginner strength program',
    description: 'The simplest effective strength program ever created. Three days per week, two alternating sessions, five core barbell movements. Linear progression on every session. Perfect for beginners building their first real base of strength.',
    author: { name: 'Mehdi (StrongLifts)', type: 'coach', verified: true },
    category: 'strength',
    subcategory: 'linear-progression',
    tags: ['beginner', 'strength', '5x5', 'barbell', 'linear-progression', 'simple', 'compound'],
    durationWeeks: 12,
    sessionsPerWeek: 3,
    sessionDurationMinutes: { min: 30, max: 50 },
    difficulty: 'beginner',
    equipment: ['barbell', 'rack', 'bench'],
    equipmentTier: 'gym',
    goals: ['strength', 'beginner-gains', 'barbell-fundamentals'],
    metrics: { strengthEmphasis: 95, hypertrophyEmphasis: 40, enduranceEmphasis: 5, conditioningEmphasis: 5, recoveryDemand: 45, weeklyVolumeScore: 40 },
    highlights: ['3 days/week only', 'Linear progression every session', '5 movements mastered', 'Beginner-perfect'],
    expectedOutcomes: ['Rapid strength gains', 'Barbell technique mastered', 'Squat/Bench/Deadlift PRs', 'Confidence in the gym'],
    popularity: 97, rating: 4.8, ratingCount: 2140, completionRate: 0.58, enrolledCount: 9800,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0a0a', '#3d1515'], accentColor: '#ef4444', icon: '🏋️',
    collections: ['most-popular', 'beginner-friendly', 'strength-collection', 'highest-rated'],
    days: {
      mon: { title: 'Workout A', badge: 'SL 5x5', color: 'var(--accent-blue)', desc: 'Squat + Bench Press + Barbell Row. 5×5 across.', runs: 'Rest', lifts: ['Back Squat', 'Bench Press', 'Barbell Row'] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Workout B', badge: 'SL 5x5', color: 'var(--accent-green)', desc: 'Squat + OHP + Deadlift. 5×5 on Squat/OHP, 1×5 Deadlift.', runs: 'Rest', lifts: ['Back Squat', 'Standing OHP', 'Deadlift'] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Workout A', badge: 'SL 5x5', color: 'var(--accent-blue)', desc: 'Squat + Bench Press + Barbell Row. 5×5 across.', runs: 'Rest', lifts: ['Back Squat', 'Bench Press', 'Barbell Row'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 5, reps: 5, intensityLabel: 'Linear Progression — add 2.5kg each session' },
      '2': { sets: 5, reps: 5, intensityLabel: 'Linear Progression — add 2.5kg each session' },
      '3': { sets: 5, reps: 5, intensityLabel: 'Linear Progression — add 2.5kg each session' },
      '4': { sets: 5, reps: 5, intensityLabel: 'Linear Progression — add 2.5kg each session' },
      '5': { sets: 5, reps: 5, intensityLabel: 'Linear Progression — add 2.5kg each session' },
      '6': { sets: 5, reps: 5, intensityLabel: 'Deload if stalling — reset 10%' },
      '7': { sets: 5, reps: 5, intensityLabel: 'Linear Progression continues' },
      '8': { sets: 5, reps: 5, intensityLabel: 'Linear Progression continues' },
      '9': { sets: 5, reps: 5, intensityLabel: 'Linear Progression continues' },
      '10': { sets: 5, reps: 5, intensityLabel: 'Linear Progression continues' },
      '11': { sets: 5, reps: 5, intensityLabel: 'Final push block' },
      '12': { sets: 5, reps: 5, intensityLabel: 'Peak week — test maxes' },
    },
    dossier: { creator: 'Mehdi (StrongLifts)', focus: 'Beginner Strength', philosophy: 'Simple is effective. Master the squat, bench, deadlift, row, and OHP with linear progression every session.' },
  },

  {
    id: 'nsuns_531',
    name: 'nSuns 5/3/1 (4-Day)',
    tagline: 'The hardest 5/3/1 variant ever programmed',
    description: 'Not for the faint of heart. nSuns uses a demanding 9-set progression scheme for main lifts based on Jim Wendler\'s 5/3/1 math. Forces rapid strength adaptation through sheer volume and heavy loads across 4 brutal days.',
    author: { name: 'nSuns', type: 'community', verified: true },
    category: 'strength',
    subcategory: 'powerlifting-style',
    tags: ['531', 'nsuns', 'strength', 'powerlifting', 'volume', 'advanced', 'barbell', 'intermediate'],
    durationWeeks: 12,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 75, max: 100 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells'],
    equipmentTier: 'gym',
    goals: ['strength', 'powerlifting-total', 'main-lift-prs'],
    metrics: { strengthEmphasis: 92, hypertrophyEmphasis: 45, enduranceEmphasis: 5, conditioningEmphasis: 10, recoveryDemand: 80, weeklyVolumeScore: 85 },
    highlights: ['9-set main lift scheme', '5/3/1 progression system', '4 days/week', 'Rapid strength gains'],
    expectedOutcomes: ['Significant strength PRs', 'Improved power output', 'Dense muscle mass', 'Competition readiness'],
    popularity: 90, rating: 4.7, ratingCount: 834, completionRate: 0.42, enrolledCount: 5600,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0a0a', '#2d0a0a'], accentColor: '#ef4444', icon: '🏋️',
    collections: ['strength-collection', 'most-popular', 'highest-rated'],
  },

  {
    id: 'gzclp',
    name: 'GZCLP',
    tagline: 'The most intelligent beginner program on the internet',
    description: 'GZCL\'s tiered progression system adapted for beginners. Three tiers of exercises with different set/rep schemes create a self-regulating program that responds to your actual performance rather than a fixed schedule.',
    author: { name: 'Cody Lefever (GZCL)', type: 'coach', verified: true },
    category: 'strength',
    subcategory: 'linear-progression',
    tags: ['gzcl', 'beginner', 'strength', 'tiered', 'intelligent', 'barbell', 'progression'],
    durationWeeks: 16,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 50, max: 70 },
    difficulty: 'beginner',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells'],
    equipmentTier: 'gym',
    goals: ['strength', 'beginner-gains', 'barbell-fundamentals'],
    metrics: { strengthEmphasis: 88, hypertrophyEmphasis: 55, enduranceEmphasis: 5, conditioningEmphasis: 5, recoveryDemand: 55, weeklyVolumeScore: 65 },
    highlights: ['Self-regulating progression', 'Intelligent tier system', '4 days/week', 'Beginner-perfect'],
    expectedOutcomes: ['Strong linear gains', 'Barbell movement mastery', 'Solid strength base', 'Understanding of training'],
    popularity: 84, rating: 4.6, ratingCount: 612, completionRate: 0.62, enrolledCount: 4200,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0a0a', '#3d1515'], accentColor: '#f97316', icon: '🏋️',
    collections: ['beginner-friendly', 'strength-collection', 'most-popular'],
    days: {
      mon: { title: 'T1 Squat Day', badge: 'GZCLP', color: 'var(--accent-green)', desc: 'T1: Back Squat 5×3+. T2: OHP 3×10. T3 accessories.', runs: 'Rest', lifts: ['Back Squat', 'Standing OHP', 'Lat Pulldown', 'Lateral Raise', 'Tricep Band Pushdown'] },
      tue: { title: 'T1 Bench Day', badge: 'GZCLP', color: 'var(--accent-blue)', desc: 'T1: Bench Press 5×3+. T2: Deadlift 3×8. T3 accessories.', runs: 'Rest', lifts: ['Bench Press', 'Deadlift', 'Barbell Row', 'Hammer Curl', 'Core/Plank'] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day.', runs: 'Rest', lifts: [] },
      thu: { title: 'T1 Squat Day B', badge: 'GZCLP', color: 'var(--accent-green)', desc: 'T1: Squat. T2: OHP. T3: Accessories.', runs: 'Rest', lifts: ['Back Squat', 'Standing OHP', 'Pull-Ups', 'Lateral Raise', 'Ab Wheel Rollouts'] },
      fri: { title: 'T1 Bench Day B', badge: 'GZCLP', color: 'var(--accent-blue)', desc: 'T1: Bench. T2: Deadlift. T3 accessories.', runs: 'Rest', lifts: ['Bench Press', 'Deadlift', 'Chin-Ups', 'Barbell Curl', 'Hanging Leg Raises'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 5, reps: 3, intensityLabel: 'T1: 5×3+ (AMRAP last set)' },
      '2': { sets: 5, reps: 3, intensityLabel: 'T1: 5×3+ (AMRAP last set)' },
      '3': { sets: 5, reps: 3, intensityLabel: 'T1: 5×3+ (AMRAP last set)' },
      '4': { sets: 5, reps: 3, intensityLabel: 'T1: 5×3+ (AMRAP last set)' },
      '5': { sets: 6, reps: 2, intensityLabel: 'T1 advancement: 6×2+' },
      '6': { sets: 6, reps: 2, intensityLabel: 'T1: 6×2+ (AMRAP last set)' },
      '7': { sets: 6, reps: 2, intensityLabel: 'T1: 6×2+' },
      '8': { sets: 6, reps: 2, intensityLabel: 'T1: 6×2+' },
      '9': { sets: 10, reps: 1, intensityLabel: 'T1 advancement: 10×1+' },
      '10': { sets: 10, reps: 1, intensityLabel: 'T1: 10×1+' },
      '11': { sets: 10, reps: 1, intensityLabel: 'T1: 10×1+' },
      '12': { sets: 10, reps: 1, intensityLabel: 'T1: 10×1+' },
      '13': { sets: 5, reps: 3, intensityLabel: 'Cycle 2 begins at new weight' },
      '14': { sets: 5, reps: 3, intensityLabel: 'Cycle 2' },
      '15': { sets: 6, reps: 2, intensityLabel: 'Cycle 2 advancement' },
      '16': { sets: 6, reps: 2, intensityLabel: 'Cycle 2 peak' },
    },
    dossier: { creator: 'Cody Lefever (GZCL)', focus: 'Beginner Strength', philosophy: 'Tiered training where T1 compounds drive strength, T2 builds volume, and T3 targets weaknesses.' },
  },

  {
    id: 'texas_method',
    name: 'Texas Method',
    tagline: 'Volume Monday, Recovery Wednesday, Intensity Friday',
    description: 'A classic intermediate strength program using a three-day weekly template. Monday accumulates volume, Wednesday promotes recovery, and Friday tests intensity with heavy singles and triples. Perfect for lifters who have exhausted linear progression.',
    author: { name: 'Mark Rippetoe', type: 'coach', verified: true },
    category: 'strength',
    subcategory: 'intermediate',
    tags: ['texas-method', 'intermediate', 'strength', 'barbell', 'volume-intensity', '5x5', 'classic'],
    durationWeeks: 12,
    sessionsPerWeek: 3,
    sessionDurationMinutes: { min: 60, max: 90 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack', 'bench'],
    equipmentTier: 'gym',
    goals: ['strength', 'intermediate-progression', 'powerlifting-base'],
    metrics: { strengthEmphasis: 90, hypertrophyEmphasis: 35, enduranceEmphasis: 5, conditioningEmphasis: 5, recoveryDemand: 65, weeklyVolumeScore: 60 },
    highlights: ['Classic V/R/I template', 'Weekly PRs possible', '3 days/week', 'Intermediate bridge'],
    expectedOutcomes: ['Break through plateaus', 'Weekly strength PRs', 'Solid powerlifting base', 'Improved 1RM'],
    popularity: 78, rating: 4.5, ratingCount: 389, completionRate: 0.52, enrolledCount: 2800,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0a0a', '#3d1515'], accentColor: '#dc2626', icon: '🏋️',
    collections: ['strength-collection', 'most-popular'],
    days: {
      mon: { title: 'Volume Day', badge: 'Texas Method', color: 'var(--accent-blue)', desc: '5×5 at 90% of Friday weight. High volume.', runs: 'Rest', lifts: ['Back Squat', 'Bench Press', 'Deadlift'] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Recovery Day', badge: 'Texas Method', color: 'var(--accent-green)', desc: 'Light squats, OHP, and chin-ups. 80% intensity.', runs: 'Rest', lifts: ['Back Squat', 'Standing OHP', 'Chin-Ups'] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Intensity Day', badge: 'Texas Method', color: 'var(--accent-amber)', desc: '1×5 PR attempt. Heavy singles. Test your strength.', runs: 'Rest', lifts: ['Back Squat', 'Bench Press', 'Deadlift', 'Barbell Row'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 5, reps: 5, intensityLabel: 'Volume: 5×5 / Intensity: 1×5 PR' },
      '2': { sets: 5, reps: 5, intensityLabel: 'Volume: 5×5 / Intensity: 1×5 PR' },
      '3': { sets: 5, reps: 5, intensityLabel: 'Volume: 5×5 / Intensity: 1×5 PR' },
      '4': { sets: 5, reps: 5, intensityLabel: 'Volume: 5×5 / Intensity: 1×5 PR' },
      '5': { sets: 5, reps: 5, intensityLabel: 'Volume: 5×5 / Intensity: 1×5 PR' },
      '6': { sets: 5, reps: 5, intensityLabel: 'Deload if stalling' },
      '7': { sets: 5, reps: 5, intensityLabel: 'Texas Method continues' },
      '8': { sets: 5, reps: 5, intensityLabel: 'Texas Method continues' },
      '9': { sets: 5, reps: 5, intensityLabel: 'Texas Method continues' },
      '10': { sets: 5, reps: 5, intensityLabel: 'Texas Method continues' },
      '11': { sets: 5, reps: 5, intensityLabel: 'Final push' },
      '12': { sets: 5, reps: 5, intensityLabel: 'Peak' },
    },
    dossier: { creator: 'Mark Rippetoe', focus: 'Intermediate Strength', philosophy: 'Weekly periodisation — volume on Monday, recovery on Wednesday, intensity on Friday.' },
  },

  {
    id: 'candito_6_week',
    name: 'Candito 6-Week Strength',
    tagline: 'Six weeks to a new strength PR',
    description: 'Jonnie Candito\'s legendary 6-week peaking program. Builds volume, transitions to intensity, then peaks with heavy triples and singles. One of the most effective short-term strength programs ever designed.',
    author: { name: 'Jonnie Candito', type: 'coach', verified: true },
    category: 'strength',
    subcategory: 'peaking',
    tags: ['candito', 'strength', 'peaking', '6-week', 'powerlifting', 'PR', 'advanced'],
    durationWeeks: 6,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 60, max: 90 },
    difficulty: 'advanced',
    equipment: ['barbell', 'rack', 'bench'],
    equipmentTier: 'gym',
    goals: ['strength-pr', 'peaking', 'powerlifting'],
    metrics: { strengthEmphasis: 95, hypertrophyEmphasis: 25, enduranceEmphasis: 5, conditioningEmphasis: 5, recoveryDemand: 75, weeklyVolumeScore: 70 },
    highlights: ['6-week peaking protocol', 'Strategic volume to intensity', 'Proven PR system', 'Deload + peak structure'],
    expectedOutcomes: ['New strength PRs', 'Competition readiness', 'Optimised strength expression', 'PR on all main lifts'],
    popularity: 85, rating: 4.8, ratingCount: 567, completionRate: 0.60, enrolledCount: 3400,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0a0a', '#2d0a0a'], accentColor: '#ef4444', icon: '🔱',
    collections: ['strength-collection', 'highest-rated'],
    days: {
      mon: { title: 'Upper Hypertrophy', badge: 'Candito', color: 'var(--accent-blue)', desc: 'Volume upper body work.', runs: 'Rest', lifts: ['Bench Press', 'Barbell Row', 'Incline DB Press', 'Lateral Raise', 'Tricep Band Pushdown'] },
      tue: { title: 'Lower Hypertrophy', badge: 'Candito', color: 'var(--accent-green)', desc: 'Volume lower body work.', runs: 'Rest', lifts: ['Back Squat', 'Romanian Deadlift', 'Bulgarian Split Squat', 'Leg Press'] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: { title: 'Bench Intensity', badge: 'Candito', color: 'var(--accent-blue)', desc: 'Heavy bench + OHP accessory.', runs: 'Rest', lifts: ['Bench Press', 'Standing OHP', 'Barbell Row'] },
      fri: { title: 'Squat + Deadlift', badge: 'Candito', color: 'var(--accent-green)', desc: 'Heavy squat + deadlift.', runs: 'Rest', lifts: ['Back Squat', 'Deadlift'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 4, reps: 10, intensityLabel: 'Week 1-2: Hypertrophy Phase' },
      '2': { sets: 4, reps: 8, intensityLabel: 'Week 1-2: Hypertrophy Phase' },
      '3': { sets: 4, reps: 6, intensityLabel: 'Week 3-4: Strength Phase (70-85%)' },
      '4': { sets: 4, reps: 4, intensityLabel: 'Week 3-4: Strength Phase (80-90%)' },
      '5': { sets: 3, reps: 3, intensityLabel: 'Week 5: Heavy (85-95%) — Reduce volume' },
      '6': { sets: 1, reps: 1, intensityLabel: 'Week 6: Peak + PR Test' },
    },
    dossier: { creator: 'Jonnie Candito', focus: 'Strength Peaking', philosophy: 'Six weeks of strategic periodisation from hypertrophy to strength to peak performance.' },
  },

  // ── HYPERTROPHY ───────────────────────────────────────────────────────────

  {
    id: 'ppl_hypertrophy',
    name: 'Push Pull Legs (Hypertrophy)',
    tagline: 'The gold standard 6-day muscle building split',
    description: 'The classic PPL split that built a million physiques. Six training days targeting each muscle group twice per week through mechanical tension and metabolic stress. The ideal program for maximizing muscle protein synthesis.',
    author: { name: 'Classic Blueprint', type: 'community', verified: true },
    category: 'hypertrophy',
    subcategory: 'ppl',
    tags: ['ppl', 'push-pull-legs', 'hypertrophy', 'muscle', '6-day', 'bodybuilding', 'intermediate'],
    durationWeeks: 8,
    sessionsPerWeek: 6,
    sessionDurationMinutes: { min: 50, max: 70 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells', 'cables'],
    equipmentTier: 'gym',
    goals: ['muscle-gain', 'hypertrophy', 'body-composition'],
    metrics: { strengthEmphasis: 40, hypertrophyEmphasis: 92, enduranceEmphasis: 5, conditioningEmphasis: 5, recoveryDemand: 65, weeklyVolumeScore: 90 },
    highlights: ['6-day split', 'Each muscle 2× per week', 'Progression built-in', 'Classic hypertrophy protocol'],
    expectedOutcomes: ['Significant muscle gain', 'Improved symmetry', 'Strength increases', 'Better body composition'],
    popularity: 93, rating: 4.7, ratingCount: 1456, completionRate: 0.46, enrolledCount: 7800,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a1628', '#1e3a5f'], accentColor: '#3b82f6', icon: '💪',
    collections: ['hypertrophy-collection', 'most-popular'],
  },

  {
    id: 'reddit_ppl',
    name: 'Reddit PPL (6-Day)',
    tagline: 'Community-built, battle-tested muscle building',
    description: 'One of the most battle-tested routines on the internet. Alternates between heavy, low-rep compound days and high-volume hypertrophy days to build a dense, aesthetic physique. Community-refined over years.',
    author: { name: 'Reddit Fitness Community', type: 'community', verified: false },
    category: 'hypertrophy',
    subcategory: 'ppl',
    tags: ['reddit', 'ppl', 'hypertrophy', 'strength', '6-day', 'community', 'barbell', 'intermediate'],
    durationWeeks: 12,
    sessionsPerWeek: 6,
    sessionDurationMinutes: { min: 55, max: 75 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells', 'cables'],
    equipmentTier: 'gym',
    goals: ['muscle-gain', 'strength', 'aesthetics'],
    metrics: { strengthEmphasis: 55, hypertrophyEmphasis: 88, enduranceEmphasis: 5, conditioningEmphasis: 5, recoveryDemand: 70, weeklyVolumeScore: 85 },
    highlights: ['Heavy + volume day alternation', 'Community favourite', '12-week cycle', 'Proven results'],
    expectedOutcomes: ['Strength and size gains', 'Aesthetic physique', 'Improved compound lifts', 'Work capacity'],
    popularity: 94, rating: 4.6, ratingCount: 2340, completionRate: 0.40, enrolledCount: 9200,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a1628', '#1e3a5f'], accentColor: '#6366f1', icon: '💪',
    collections: ['hypertrophy-collection', 'most-popular', 'community-favourites'],
  },

  {
    id: 'kong_savage_size',
    name: 'KONG: Savage Size',
    tagline: 'Alex Bromley\'s brutal 12-week size protocol',
    description: 'Three distinct phases. A 4-week Volumizing block, a Pyramids block, and finally heavy Reverse Pyramids. Eat big to survive this. Alex Bromley\'s most popular hypertrophy program produces exceptional size gains.',
    author: { name: 'Alex Bromley', type: 'coach', verified: true },
    category: 'hypertrophy',
    subcategory: 'bodybuilding',
    tags: ['kong', 'alex-bromley', 'hypertrophy', 'size', 'bodybuilding', 'advanced', 'phases'],
    durationWeeks: 12,
    sessionsPerWeek: 5,
    sessionDurationMinutes: { min: 65, max: 85 },
    difficulty: 'advanced',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells', 'cables'],
    equipmentTier: 'gym',
    goals: ['muscle-gain', 'hypertrophy', 'size'],
    metrics: { strengthEmphasis: 60, hypertrophyEmphasis: 95, enduranceEmphasis: 5, conditioningEmphasis: 5, recoveryDemand: 75, weeklyVolumeScore: 92 },
    highlights: ['3-phase progression', 'Reverse pyramid technique', 'Alex Bromley methodology', 'Maximum size focus'],
    expectedOutcomes: ['Exceptional muscle gain', 'Improved symmetry', 'Strength foundation', 'Stage-ready physique'],
    popularity: 86, rating: 4.8, ratingCount: 456, completionRate: 0.47, enrolledCount: 3200,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a1628', '#0f3460'], accentColor: '#8b5cf6', icon: '💪',
    collections: ['hypertrophy-collection', 'highest-rated', 'most-popular'],
  },

  {
    id: 'phul',
    name: 'PHUL — Power Hypertrophy Upper Lower',
    tagline: 'Four days of power and hypertrophy combined',
    description: 'Power Hypertrophy Upper Lower. Four training days covering both power (heavy, low rep) and hypertrophy (moderate rep) work. The gold standard 4-day split for athletes who want strength and size simultaneously.',
    author: { name: 'Brandon Campbell', type: 'coach', verified: true },
    category: 'hypertrophy',
    subcategory: 'upper-lower',
    tags: ['phul', 'power', 'hypertrophy', 'upper-lower', '4-day', 'strength', 'intermediate', 'barbell'],
    durationWeeks: 12,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 60, max: 80 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells', 'cables'],
    equipmentTier: 'gym',
    goals: ['muscle-gain', 'strength', 'powerbuilding'],
    metrics: { strengthEmphasis: 70, hypertrophyEmphasis: 80, enduranceEmphasis: 5, conditioningEmphasis: 10, recoveryDemand: 60, weeklyVolumeScore: 75 },
    highlights: ['Power + hypertrophy days', '4-day schedule', 'Upper/lower split', 'Strength + size'],
    expectedOutcomes: ['Strength and size gains', 'Well-balanced physique', 'Improved main lifts', 'Functional muscle mass'],
    popularity: 88, rating: 4.6, ratingCount: 789, completionRate: 0.52, enrolledCount: 5100,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a1628', '#1e3a5f'], accentColor: '#3b82f6', icon: '💪',
    collections: ['hypertrophy-collection', 'strength-collection', 'most-popular'],
    days: {
      mon: { title: 'Upper Power', badge: 'PHUL', color: 'var(--accent-blue)', desc: 'Heavy compounds. Bench + Row. 3-5 rep ranges.', runs: 'Rest', lifts: ['Bench Press', 'Barbell Row', 'Incline Bench Press', 'Lat Pulldown', 'Barbell Curl', 'Tricep Band Pushdown'] },
      tue: { title: 'Lower Power', badge: 'PHUL', color: 'var(--accent-green)', desc: 'Heavy squat + deadlift. Low rep power work.', runs: 'Rest', lifts: ['Back Squat', 'Deadlift', 'Leg Press', 'Calf Raises'] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: { title: 'Upper Hypertrophy', badge: 'PHUL', color: 'var(--accent-blue)', desc: 'Volume upper work. 8-12 rep ranges.', runs: 'Rest', lifts: ['Incline DB Press', 'Seated DB Shoulder Press', 'Chest Supported Row', 'Lateral Raise', 'Incline DB Curl', 'Lying DB Tricep Extension'] },
      fri: { title: 'Lower Hypertrophy', badge: 'PHUL', color: 'var(--accent-green)', desc: 'Volume lower work. 8-12 rep ranges.', runs: 'Rest', lifts: ['Back Squat', 'Romanian Deadlift', 'Bulgarian Split Squat', 'Hamstring Curl', 'Calf Raises'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 8, intensityLabel: 'Power Days: 3-5 reps | Hypertrophy Days: 8-12 reps' },
      '2': { sets: 4, reps: 8, intensityLabel: 'Power Days: 3-5 reps | Hypertrophy Days: 8-12 reps' },
      '3': { sets: 4, reps: 6, intensityLabel: 'Power Days: 3-5 reps | Hypertrophy Days: 8-12 reps' },
      '4': { sets: 2, reps: 10, intensityLabel: 'Deload week' },
      '5': { sets: 4, reps: 6, intensityLabel: 'Increasing intensity' },
      '6': { sets: 4, reps: 5, intensityLabel: 'Increasing intensity' },
      '7': { sets: 4, reps: 5, intensityLabel: 'Heavy block' },
      '8': { sets: 2, reps: 8, intensityLabel: 'Deload' },
      '9': { sets: 5, reps: 5, intensityLabel: 'Peak block' },
      '10': { sets: 5, reps: 4, intensityLabel: 'Peak block' },
      '11': { sets: 4, reps: 4, intensityLabel: 'Peak block' },
      '12': { sets: 3, reps: 3, intensityLabel: 'Final peak' },
    },
    dossier: { creator: 'Brandon Campbell', focus: 'Power & Hypertrophy', philosophy: 'Four days combining power training for strength and hypertrophy training for size.' },
  },

  // ── RUNNING ───────────────────────────────────────────────────────────────

  {
    id: 'couch_to_5k',
    name: 'Couch to 5K',
    tagline: 'Go from the sofa to running 5K in 9 weeks',
    description: 'The world\'s most popular running program for absolute beginners. Gentle walk-run intervals progressively build your endurance until you can run 5K continuously. Used by millions worldwide to start their running journey.',
    author: { name: 'Josh Clark', type: 'coach', verified: true },
    category: 'running',
    subcategory: 'beginner',
    tags: ['beginner', 'running', '5k', 'walk-run', 'couch-to-5k', 'c25k', 'no-equipment', 'cardio'],
    durationWeeks: 9,
    sessionsPerWeek: 3,
    sessionDurationMinutes: { min: 20, max: 35 },
    difficulty: 'beginner',
    equipment: ['running-shoes'],
    equipmentTier: 'minimal',
    goals: ['run-5k', 'fitness', 'general-health', 'cardio'],
    metrics: { strengthEmphasis: 5, hypertrophyEmphasis: 5, enduranceEmphasis: 88, conditioningEmphasis: 60, recoveryDemand: 30, weeklyVolumeScore: 30 },
    highlights: ['Walk-run intervals', '9 weeks to 5K', 'Beginner-friendly', 'No equipment needed'],
    expectedOutcomes: ['Run 5K continuously', 'Running habit established', 'Improved cardio', 'Confidence to race'],
    popularity: 98, rating: 4.9, ratingCount: 5600, completionRate: 0.72, enrolledCount: 24000,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a1628', '#1e3a5f'], accentColor: '#22d3ee', icon: '🏃',
    collections: ['beginner-friendly', 'running-collection', 'most-popular', 'highest-rated', 'time-efficient'],
    days: {
      mon: { title: 'Run Session 1', badge: 'C25K', color: 'var(--accent-cyan)', desc: 'Walk-run intervals as per week schedule.', runs: '🏃 Walk/Run intervals — see week schedule', lifts: [] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest. Let your body adapt.', runs: 'Rest', lifts: [] },
      wed: { title: 'Run Session 2', badge: 'C25K', color: 'var(--accent-cyan)', desc: 'Walk-run intervals as per week schedule.', runs: '🏃 Walk/Run intervals — see week schedule', lifts: [] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Run Session 3', badge: 'C25K', color: 'var(--accent-cyan)', desc: 'Walk-run intervals as per week schedule.', runs: '🏃 Walk/Run intervals — see week schedule', lifts: [] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest or light walking.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 0, reps: 0, intensityLabel: 'Run 1min, Walk 1.5min × 8 reps' },
      '2': { sets: 0, reps: 0, intensityLabel: 'Run 1.5min, Walk 2min × 6 reps' },
      '3': { sets: 0, reps: 0, intensityLabel: 'Run 3min, Walk 1.5min / Run 5min, Walk 2.5min alternating' },
      '4': { sets: 0, reps: 0, intensityLabel: 'Run 5min, Walk 2.5min × 3 reps' },
      '5': { sets: 0, reps: 0, intensityLabel: 'Run 8min, Walk 5min / Run 20min continuous on Day 3' },
      '6': { sets: 0, reps: 0, intensityLabel: 'Run 25min continuous' },
      '7': { sets: 0, reps: 0, intensityLabel: 'Run 25min continuous' },
      '8': { sets: 0, reps: 0, intensityLabel: 'Run 28min continuous' },
      '9': { sets: 0, reps: 0, intensityLabel: 'Run 30min (approx 5K)' },
    },
    dossier: { creator: 'Josh Clark / NHS', focus: 'Beginner Running', philosophy: 'Gradual walk-run interval progression builds running capacity without injury risk.' },
  },

  {
    id: 'half_marathon_foundation',
    name: 'Half Marathon Foundation',
    tagline: 'Build to 21.1km from a solid running base',
    description: 'A 16-week program for runners with a 5K base who want to complete their first half marathon. Builds weekly mileage progressively with easy runs, tempo work, and long run development. Safe, structured, and proven.',
    author: { name: 'HybridHQ Running', type: 'official', verified: true },
    category: 'running',
    subcategory: 'race-prep',
    tags: ['half-marathon', 'running', 'race-prep', 'endurance', 'long-run', 'tempo', 'intermediate'],
    durationWeeks: 16,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 35, max: 120 },
    difficulty: 'intermediate',
    equipment: ['running-shoes'],
    equipmentTier: 'minimal',
    goals: ['half-marathon', 'race-completion', 'running-endurance'],
    metrics: { strengthEmphasis: 5, hypertrophyEmphasis: 5, enduranceEmphasis: 95, conditioningEmphasis: 50, recoveryDemand: 60, weeklyVolumeScore: 70 },
    highlights: ['16-week structured plan', 'Progressive long runs', 'Tempo + easy mix', 'Race week taper'],
    expectedOutcomes: ['Complete first half marathon', 'Build to 21.1km', 'Improved running economy', 'Race confidence'],
    popularity: 84, rating: 4.7, ratingCount: 892, completionRate: 0.68, enrolledCount: 5800,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a1628', '#1e3a5f'], accentColor: '#22d3ee', icon: '🏃',
    collections: ['running-collection', 'most-popular', 'highest-rated'],
    days: {
      mon: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest.', runs: 'Rest', lifts: [] },
      tue: { title: 'Easy Run', badge: 'Zone 2', color: 'var(--accent-cyan)', desc: 'Easy conversational pace.', runs: '🏃 Easy run — see week schedule', lifts: [] },
      wed: { title: 'Tempo Run', badge: 'Threshold', color: 'var(--accent-amber)', desc: 'Comfortably hard sustained effort.', runs: '🔥 Tempo intervals — see week schedule', lifts: [] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest or easy walk.', runs: 'Rest', lifts: [] },
      fri: { title: 'Easy Run', badge: 'Zone 2', color: 'var(--accent-cyan)', desc: 'Easy recovery run.', runs: '🏃 Easy run — see week schedule', lifts: [] },
      sat: { title: 'Long Run', badge: 'Endurance', color: 'var(--accent-pink)', desc: 'Progressive long run. Very easy pace.', runs: '🏃 Long run — see week schedule', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 0, reps: 0, intensityLabel: 'Long run: 12km | Weekly: ~30km' },
      '2': { sets: 0, reps: 0, intensityLabel: 'Long run: 13km | Weekly: ~32km' },
      '3': { sets: 0, reps: 0, intensityLabel: 'Long run: 15km | Weekly: ~35km' },
      '4': { sets: 0, reps: 0, intensityLabel: 'CUTBACK: Long run: 10km | Recovery week' },
      '5': { sets: 0, reps: 0, intensityLabel: 'Long run: 16km | Weekly: ~38km' },
      '6': { sets: 0, reps: 0, intensityLabel: 'Long run: 17km | Weekly: ~40km' },
      '7': { sets: 0, reps: 0, intensityLabel: 'Long run: 19km | Weekly: ~43km' },
      '8': { sets: 0, reps: 0, intensityLabel: 'CUTBACK: Long run: 13km | Recovery week' },
      '9': { sets: 0, reps: 0, intensityLabel: 'Long run: 19km | Weekly: ~43km' },
      '10': { sets: 0, reps: 0, intensityLabel: 'Long run: 21km | Weekly: ~46km' },
      '11': { sets: 0, reps: 0, intensityLabel: 'Long run: 21km | Weekly: ~46km' },
      '12': { sets: 0, reps: 0, intensityLabel: 'CUTBACK: Long run: 15km | Recovery' },
      '13': { sets: 0, reps: 0, intensityLabel: 'Long run: 21km | Weekly: ~45km' },
      '14': { sets: 0, reps: 0, intensityLabel: 'Long run: 19km | Taper begins' },
      '15': { sets: 0, reps: 0, intensityLabel: 'Long run: 15km | Taper' },
      '16': { sets: 0, reps: 0, intensityLabel: 'RACE WEEK: 21.1km race day' },
    },
    dossier: { creator: 'HybridHQ Running', focus: 'Half Marathon Preparation', philosophy: 'Gradual mileage build with strategic cutback weeks for safe adaptation and race day success.' },
  },

  {
    id: 'marathon_base_builder',
    name: 'Marathon Base Builder',
    tagline: 'Build the aerobic engine for 42.2km',
    description: 'An 18-week first marathon program for runners who can comfortably run 10K. Progressive mileage build with strategic cutback weeks, multiple long runs over 30km, and a structured 3-week taper into race day.',
    author: { name: 'HybridHQ Running', type: 'official', verified: true },
    category: 'running',
    subcategory: 'marathon',
    tags: ['marathon', 'running', 'race-prep', 'endurance', 'long-run', 'aerobic', 'advanced'],
    durationWeeks: 18,
    sessionsPerWeek: 5,
    sessionDurationMinutes: { min: 40, max: 180 },
    difficulty: 'advanced',
    equipment: ['running-shoes'],
    equipmentTier: 'minimal',
    goals: ['marathon', 'race-completion', 'endurance'],
    metrics: { strengthEmphasis: 5, hypertrophyEmphasis: 5, enduranceEmphasis: 98, conditioningEmphasis: 40, recoveryDemand: 75, weeklyVolumeScore: 85 },
    highlights: ['18-week full plan', '3-week structured taper', 'Multiple 30km+ long runs', 'Race day ready'],
    expectedOutcomes: ['Complete first marathon', 'Build to 42.2km', 'Strong aerobic base', 'Race confidence'],
    popularity: 76, rating: 4.7, ratingCount: 423, completionRate: 0.64, enrolledCount: 3100,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a1628', '#1e3a5f'], accentColor: '#06b6d4', icon: '🏃',
    collections: ['running-collection', 'endurance-collection'],
    days: {
      mon: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest.', runs: 'Rest', lifts: [] },
      tue: { title: 'Easy Run', badge: 'Zone 2', color: 'var(--accent-cyan)', desc: 'Easy conversational run.', runs: '🏃 Easy run — see week schedule', lifts: [] },
      wed: { title: 'Medium Run + Tempo', badge: 'Threshold', color: 'var(--accent-amber)', desc: 'Medium distance with tempo section.', runs: '🔥 Medium run with tempo — see week schedule', lifts: [] },
      thu: { title: 'Easy Run', badge: 'Zone 2', color: 'var(--accent-cyan)', desc: 'Easy recovery run.', runs: '🏃 Easy run — see week schedule', lifts: [] },
      fri: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sat: { title: 'Long Run', badge: 'Endurance', color: 'var(--accent-pink)', desc: 'Primary long run. Very easy pace.', runs: '🏃 Long run — see week schedule', lifts: [] },
      sun: { title: 'Easy Recovery Run', badge: 'Zone 2', color: 'var(--accent-cyan)', desc: 'Short easy run post long run.', runs: '🏃 20-30min very easy', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 0, reps: 0, intensityLabel: 'Long: 19km | Weekly: ~48km' },
      '2': { sets: 0, reps: 0, intensityLabel: 'Long: 21km | Weekly: ~51km' },
      '3': { sets: 0, reps: 0, intensityLabel: 'Long: 24km | Weekly: ~55km' },
      '4': { sets: 0, reps: 0, intensityLabel: 'CUTBACK: Long: 16km | Recovery' },
      '5': { sets: 0, reps: 0, intensityLabel: 'Long: 26km | Weekly: ~58km' },
      '6': { sets: 0, reps: 0, intensityLabel: 'Long: 27km | Weekly: ~61km' },
      '7': { sets: 0, reps: 0, intensityLabel: 'Long: 29km | Weekly: ~64km' },
      '8': { sets: 0, reps: 0, intensityLabel: 'CUTBACK: Long: 19km | Recovery' },
      '9': { sets: 0, reps: 0, intensityLabel: 'Long: 29km | Weekly: ~64km' },
      '10': { sets: 0, reps: 0, intensityLabel: 'Long: 32km | Weekly: ~68km' },
      '11': { sets: 0, reps: 0, intensityLabel: 'Long: 32km | Weekly: ~68km' },
      '12': { sets: 0, reps: 0, intensityLabel: 'CUTBACK: Long: 21km | Recovery' },
      '13': { sets: 0, reps: 0, intensityLabel: 'Long: 34km | Weekly: ~70km' },
      '14': { sets: 0, reps: 0, intensityLabel: 'Long: 32km | Weekly: ~67km' },
      '15': { sets: 0, reps: 0, intensityLabel: 'TAPER: Long: 27km | Weekly: ~55km' },
      '16': { sets: 0, reps: 0, intensityLabel: 'TAPER: Long: 21km | Weekly: ~44km' },
      '17': { sets: 0, reps: 0, intensityLabel: 'TAPER: Long: 16km | Weekly: ~35km' },
      '18': { sets: 0, reps: 0, intensityLabel: 'RACE WEEK: 42.2km race day' },
    },
    dossier: { creator: 'HybridHQ Running', focus: 'Marathon Preparation', philosophy: 'Safe aerobic mileage build with strategic cutback weeks and evidence-based taper for first marathon success.' },
  },

  // ── ENDURANCE ─────────────────────────────────────────────────────────────

  {
    id: 'zone2_foundation',
    name: 'Zone 2 Aerobic Foundation',
    tagline: 'Build your aerobic engine from the ground up',
    description: 'A 12-week program built entirely around Zone 2 heart rate training. Develop your mitochondrial density, fat oxidation, and aerobic efficiency through consistent easy effort work. The foundation all other training is built on.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'endurance',
    subcategory: 'zone2',
    tags: ['zone2', 'aerobic', 'endurance', 'heart-rate', 'easy', 'mitochondria', 'foundation', 'beginner'],
    durationWeeks: 12,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 30, max: 75 },
    difficulty: 'beginner',
    equipment: ['running-shoes'],
    equipmentTier: 'minimal',
    goals: ['aerobic-base', 'endurance', 'health', 'fat-adaptation'],
    metrics: { strengthEmphasis: 5, hypertrophyEmphasis: 5, enduranceEmphasis: 95, conditioningEmphasis: 30, recoveryDemand: 35, weeklyVolumeScore: 50 },
    highlights: ['Pure Zone 2 focus', 'Heart rate guided', 'Sustainable volume build', 'Foundation for everything'],
    expectedOutcomes: ['Improved aerobic efficiency', 'Lower resting HR', 'Better fat oxidation', 'Endurance base'],
    popularity: 72, rating: 4.5, ratingCount: 234, completionRate: 0.71, enrolledCount: 1800,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a2818', '#1a4731'], accentColor: '#10b981', icon: '🫀',
    collections: ['endurance-collection', 'beginner-friendly', 'time-efficient'],
    days: {
      mon: { title: 'Zone 2 Run', badge: 'Aerobic', color: 'var(--accent-green)', desc: 'Easy conversational run. HR 130-150bpm.', runs: '🏃 Zone 2 run — see week schedule', lifts: [] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Zone 2 Run', badge: 'Aerobic', color: 'var(--accent-green)', desc: 'Easy conversational run. HR 130-150bpm.', runs: '🏃 Zone 2 run — see week schedule', lifts: [] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest or light mobility.', runs: 'Rest', lifts: [] },
      fri: { title: 'Zone 2 Run', badge: 'Aerobic', color: 'var(--accent-green)', desc: 'Easy conversational run.', runs: '🏃 Zone 2 run — see week schedule', lifts: [] },
      sat: { title: 'Long Zone 2', badge: 'Long Aerobic', color: 'var(--accent-green)', desc: 'Longest run of the week. Very easy pace.', runs: '🏃 Long Zone 2 — see week schedule', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 0, reps: 0, intensityLabel: 'Long: 35min | 3 sessions × 25min' },
      '2': { sets: 0, reps: 0, intensityLabel: 'Long: 40min | 3 sessions × 28min' },
      '3': { sets: 0, reps: 0, intensityLabel: 'Long: 45min | 3 sessions × 30min' },
      '4': { sets: 0, reps: 0, intensityLabel: 'CUTBACK: Long: 30min | Recovery week' },
      '5': { sets: 0, reps: 0, intensityLabel: 'Long: 50min | 3 sessions × 32min' },
      '6': { sets: 0, reps: 0, intensityLabel: 'Long: 55min | 3 sessions × 35min' },
      '7': { sets: 0, reps: 0, intensityLabel: 'Long: 60min | 3 sessions × 38min' },
      '8': { sets: 0, reps: 0, intensityLabel: 'CUTBACK: Long: 40min | Recovery' },
      '9': { sets: 0, reps: 0, intensityLabel: 'Long: 65min | 3 sessions × 40min' },
      '10': { sets: 0, reps: 0, intensityLabel: 'Long: 70min | 3 sessions × 45min' },
      '11': { sets: 0, reps: 0, intensityLabel: 'Long: 75min | 3 sessions × 45min' },
      '12': { sets: 0, reps: 0, intensityLabel: 'Peak week — assess improvement' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Aerobic Foundation', philosophy: 'Consistent Zone 2 training builds the mitochondrial base that powers all athletic performance.' },
  },

  // ── BODY COMPOSITION ──────────────────────────────────────────────────────

  {
    id: 'cut_phase',
    name: 'Cut Phase — Fat Loss Protocol',
    tagline: 'Preserve muscle while shedding body fat',
    description: 'An 8-week fat loss program designed to preserve maximum muscle mass during a caloric deficit. Higher frequency lifting, strategic cardio, and progressive overload combine to maintain strength while body composition transforms.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'body_composition',
    subcategory: 'fat-loss',
    tags: ['fat-loss', 'cutting', 'body-composition', 'cardio', 'muscle-preservation', 'deficit', 'intermediate'],
    durationWeeks: 8,
    sessionsPerWeek: 5,
    sessionDurationMinutes: { min: 45, max: 65 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'dumbbells', 'rack', 'bench'],
    equipmentTier: 'gym',
    goals: ['fat-loss', 'body-composition', 'muscle-preservation'],
    metrics: { strengthEmphasis: 55, hypertrophyEmphasis: 45, enduranceEmphasis: 40, conditioningEmphasis: 55, recoveryDemand: 55, weeklyVolumeScore: 65 },
    highlights: ['Muscle preservation focus', 'Strategic cardio included', 'Higher frequency', 'Evidence-based approach'],
    expectedOutcomes: ['Significant fat loss', 'Maintained muscle mass', 'Improved definition', 'Better body composition'],
    popularity: 81, rating: 4.5, ratingCount: 534, completionRate: 0.54, enrolledCount: 3600,
    featured: false, verified: true, isNew: true,
    coverGradient: ['#1a0e0e', '#3d2222'], accentColor: '#f59e0b', icon: '🔥',
    collections: ['body-composition-collection', 'most-popular', 'new-programs'],
    days: {
      mon: { title: 'Upper A', badge: 'Cut Phase', color: 'var(--accent-blue)', desc: 'Push + pull with moderate volume.', runs: 'Optional: 20min Zone 2 cardio', lifts: ['Bench Press', 'Pull-Ups', 'Incline DB Press', 'Barbell Row', 'Lateral Raise'] },
      tue: { title: 'Lower A + Cardio', badge: 'Cut Phase', color: 'var(--accent-green)', desc: 'Legs + cardio conditioning.', runs: '🏃 20-30min cardio (HIIT or Zone 2)', lifts: ['Back Squat', 'Romanian Deadlift', 'Leg Press', 'Calf Raises'] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest or light walk.', runs: 'Rest', lifts: [] },
      thu: { title: 'Upper B', badge: 'Cut Phase', color: 'var(--accent-blue)', desc: 'Push + pull volume focus.', runs: 'Optional: 20min Zone 2', lifts: ['Standing OHP', 'Deadlift', 'Dips', 'Chin-Ups', 'Face Pull'] },
      fri: { title: 'Lower B + Cardio', badge: 'Cut Phase', color: 'var(--accent-green)', desc: 'Lower body + conditioning.', runs: '🏃 25-35min cardio', lifts: ['Front Squat', 'Bulgarian Split Squat', 'Hamstring Curl', 'Calf Raises'] },
      sat: { title: 'Cardio Day', badge: 'Zone 2', color: 'var(--accent-amber)', desc: 'Steady state cardio day.', runs: '🏃 40-50min Zone 2 steady state', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 12, intensityLabel: 'Volume focus — muscle preservation' },
      '2': { sets: 3, reps: 12, intensityLabel: 'Volume focus' },
      '3': { sets: 4, reps: 10, intensityLabel: 'Build intensity' },
      '4': { sets: 4, reps: 10, intensityLabel: 'Build intensity' },
      '5': { sets: 4, reps: 8, intensityLabel: 'Strength focus begins' },
      '6': { sets: 4, reps: 8, intensityLabel: 'Strength focus' },
      '7': { sets: 4, reps: 6, intensityLabel: 'Heavy strength phase' },
      '8': { sets: 3, reps: 8, intensityLabel: 'Final week — assessment' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Fat Loss & Muscle Preservation', philosophy: 'Strategic fat loss through higher frequency training, progressive overload, and structured cardio.' },
  },

  {
    id: 'body_recomp',
    name: 'Body Recomposition Protocol',
    tagline: 'Lose fat and gain muscle simultaneously',
    description: 'A 16-week program targeting body recomposition — the simultaneous loss of fat and gain of muscle. Achievable for beginners and those returning to training. Combines progressive overload with moderate cardio at maintenance calories.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'body_composition',
    subcategory: 'recomposition',
    tags: ['recomposition', 'fat-loss', 'muscle-gain', 'beginner', 'intermediate', 'body-composition', 'cardio'],
    durationWeeks: 16,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 40, max: 60 },
    difficulty: 'beginner',
    equipment: ['dumbbells', 'barbell', 'rack', 'bench'],
    equipmentTier: 'gym',
    goals: ['body-composition', 'fat-loss', 'muscle-gain', 'general-health'],
    metrics: { strengthEmphasis: 55, hypertrophyEmphasis: 60, enduranceEmphasis: 35, conditioningEmphasis: 40, recoveryDemand: 45, weeklyVolumeScore: 55 },
    highlights: ['Simultaneous fat loss + muscle gain', 'Beginner-friendly structure', '4 days/week', 'Nutrition-agnostic'],
    expectedOutcomes: ['Improved body composition', 'Visible muscle definition', 'Strength improvements', 'Healthier lifestyle'],
    popularity: 79, rating: 4.5, ratingCount: 467, completionRate: 0.60, enrolledCount: 3400,
    featured: false, verified: true, isNew: true,
    coverGradient: ['#1a0e0e', '#3d2222'], accentColor: '#f59e0b', icon: '🔥',
    collections: ['body-composition-collection', 'beginner-friendly', 'new-programs'],
    days: {
      mon: { title: 'Full Body A', badge: 'Recomp', color: 'var(--accent-blue)', desc: 'Full body strength circuit.', runs: 'Optional: 15min easy cardio', lifts: ['Back Squat', 'Bench Press', 'Barbell Row', 'Lateral Raise', 'Hammer Curl'] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest or light walk.', runs: 'Rest', lifts: [] },
      wed: { title: 'Full Body B', badge: 'Recomp', color: 'var(--accent-green)', desc: 'Full body strength — different movements.', runs: 'Optional: 15min easy cardio', lifts: ['Deadlift', 'Standing OHP', 'Pull-Ups', 'Romanian Deadlift', 'Tricep Band Pushdown'] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Full Body C', badge: 'Recomp', color: 'var(--accent-blue)', desc: 'Volume focus full body.', runs: 'Optional: 20min cardio', lifts: ['Back Squat', 'Incline DB Press', 'Chin-Ups', 'Bulgarian Split Squat', 'Face Pull'] },
      sat: { title: 'Cardio + Core', badge: 'Conditioning', color: 'var(--accent-amber)', desc: 'Optional cardio and core work.', runs: '🏃 30-45min Zone 2 cardio', lifts: ['Core/Plank', 'Hanging Leg Raises', 'Ab Wheel Rollouts'] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 12, intensityLabel: 'Base volume establishment' },
      '2': { sets: 3, reps: 12, intensityLabel: 'Base volume' },
      '3': { sets: 3, reps: 10, intensityLabel: 'Slight intensity increase' },
      '4': { sets: 3, reps: 10, intensityLabel: 'Volume build' },
      '5': { sets: 4, reps: 10, intensityLabel: 'Volume increase' },
      '6': { sets: 4, reps: 10, intensityLabel: 'Volume peak' },
      '7': { sets: 4, reps: 8, intensityLabel: 'Intensity phase' },
      '8': { sets: 2, reps: 12, intensityLabel: 'Deload' },
      '9': { sets: 4, reps: 8, intensityLabel: 'Strength phase' },
      '10': { sets: 4, reps: 8, intensityLabel: 'Strength phase' },
      '11': { sets: 4, reps: 6, intensityLabel: 'Heavy strength' },
      '12': { sets: 4, reps: 6, intensityLabel: 'Heavy strength' },
      '13': { sets: 4, reps: 8, intensityLabel: 'Back to volume' },
      '14': { sets: 4, reps: 8, intensityLabel: 'Volume + strength blend' },
      '15': { sets: 4, reps: 6, intensityLabel: 'Final strength block' },
      '16': { sets: 2, reps: 10, intensityLabel: 'Final assessment week' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Body Recomposition', philosophy: 'Progressive overload combined with cardio at maintenance calories achieves simultaneous fat loss and muscle gain.' },
  },

  // ── GENERAL FITNESS ───────────────────────────────────────────────────────

  {
    id: 'beginner_full_body',
    name: 'Beginner Full Body',
    tagline: 'The perfect starting point for complete beginners',
    description: 'An 8-week introduction to structured training. Three full-body sessions per week teaching fundamental movement patterns while building initial strength and conditioning. Designed for those brand new to the gym.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'general_fitness',
    subcategory: 'beginner',
    tags: ['beginner', 'full-body', 'fundamentals', '3-day', 'gym-newbie', 'foundation', 'simple'],
    durationWeeks: 8,
    sessionsPerWeek: 3,
    sessionDurationMinutes: { min: 30, max: 45 },
    difficulty: 'beginner',
    equipment: ['dumbbells', 'barbell', 'rack', 'bench'],
    equipmentTier: 'gym',
    goals: ['beginner-gains', 'general-health', 'movement-fundamentals'],
    metrics: { strengthEmphasis: 60, hypertrophyEmphasis: 50, enduranceEmphasis: 15, conditioningEmphasis: 20, recoveryDemand: 30, weeklyVolumeScore: 35 },
    highlights: ['3 days/week only', 'Full body each session', 'Beginner-perfect', 'Fundamental movements'],
    expectedOutcomes: ['Strength foundation built', 'Movement patterns mastered', 'Gym confidence gained', 'First real gains'],
    popularity: 88, rating: 4.7, ratingCount: 1230, completionRate: 0.69, enrolledCount: 7200,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0e1a1e', '#1a3040'], accentColor: '#06b6d4', icon: '🎯',
    collections: ['beginner-friendly', 'most-popular', 'time-efficient', 'general-fitness-collection'],
    days: {
      mon: { title: 'Full Body A', badge: 'Beginner', color: 'var(--accent-blue)', desc: 'Squat, Push, Pull fundamentals.', runs: 'Rest', lifts: ['Back Squat', 'Bench Press', 'Barbell Row', 'Lateral Raise', 'Hammer Curl'] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest. Let your body adapt.', runs: 'Rest', lifts: [] },
      wed: { title: 'Full Body B', badge: 'Beginner', color: 'var(--accent-green)', desc: 'Hinge, Press, Row variations.', runs: 'Rest', lifts: ['Deadlift', 'Standing OHP', 'Lat Pulldown', 'Romanian Deadlift', 'Tricep Band Pushdown'] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Full Body C', badge: 'Beginner', color: 'var(--accent-amber)', desc: 'Compound movement variety.', runs: 'Rest', lifts: ['Back Squat', 'Incline DB Press', 'Pull-Ups', 'Bulgarian Split Squat', 'Barbell Curl'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest or light activity.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 8, intensityLabel: 'Foundation — focus on form' },
      '2': { sets: 3, reps: 8, intensityLabel: 'Foundation — add weight slowly' },
      '3': { sets: 3, reps: 10, intensityLabel: 'Volume build' },
      '4': { sets: 3, reps: 10, intensityLabel: 'Volume build' },
      '5': { sets: 4, reps: 8, intensityLabel: 'Intensity increase' },
      '6': { sets: 4, reps: 8, intensityLabel: 'Intensity increase' },
      '7': { sets: 4, reps: 6, intensityLabel: 'Heavier focus' },
      '8': { sets: 3, reps: 8, intensityLabel: 'Final week — celebrate progress' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Beginner Fundamentals', philosophy: 'Master the six fundamental movement patterns through progressive overload across an 8-week foundation.' },
  },

  {
    id: 'athletic_base',
    name: 'Athletic Base Builder',
    tagline: 'All-around athleticism for the everyday athlete',
    description: 'A 12-week general athletic development program. Combines strength, power, conditioning, and mobility work into a balanced program that improves performance across all physical domains. Suitable for anyone who wants to be genuinely fit.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'general_fitness',
    subcategory: 'athletic',
    tags: ['athletic', 'general-fitness', 'strength', 'conditioning', 'cardio', 'balanced', 'intermediate'],
    durationWeeks: 12,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 45, max: 65 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'dumbbells', 'rack', 'bench'],
    equipmentTier: 'gym',
    goals: ['general-athleticism', 'fitness', 'conditioning', 'strength'],
    metrics: { strengthEmphasis: 60, hypertrophyEmphasis: 50, enduranceEmphasis: 50, conditioningEmphasis: 60, recoveryDemand: 55, weeklyVolumeScore: 60 },
    highlights: ['Well-rounded athletic development', '4 days/week', 'Strength + cardio balance', 'Progressive structure'],
    expectedOutcomes: ['Improved all-round fitness', 'Stronger and fitter', 'Better conditioning', 'Athletic physique'],
    popularity: 76, rating: 4.5, ratingCount: 312, completionRate: 0.62, enrolledCount: 2400,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0e1a1e', '#1a3040'], accentColor: '#06b6d4', icon: '🎯',
    collections: ['general-fitness-collection', 'time-efficient'],
    days: {
      mon: { title: 'Strength A', badge: 'Athletic', color: 'var(--accent-blue)', desc: 'Compound strength focus.', runs: 'Rest', lifts: ['Back Squat', 'Bench Press', 'Pull-Ups', 'Lateral Raise', 'Hammer Curl'] },
      tue: { title: 'Conditioning', badge: 'Athletic', color: 'var(--accent-amber)', desc: 'Cardio + conditioning circuit.', runs: '🏃 30min run + 3×circuit work', lifts: [] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: { title: 'Strength B', badge: 'Athletic', color: 'var(--accent-green)', desc: 'Hinge, row, press focus.', runs: 'Rest', lifts: ['Deadlift', 'Barbell Row', 'Standing OHP', 'Romanian Deadlift', 'Tricep Band Pushdown'] },
      fri: { title: 'Mixed Cardio', badge: 'Athletic', color: 'var(--accent-pink)', desc: 'Mixed effort cardio work.', runs: '🏃 40min mixed effort run', lifts: [] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest or light activity.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 10, intensityLabel: 'Foundation' }, '2': { sets: 3, reps: 10, intensityLabel: 'Foundation' },
      '3': { sets: 4, reps: 8, intensityLabel: 'Build' }, '4': { sets: 2, reps: 10, intensityLabel: 'Deload' },
      '5': { sets: 4, reps: 8, intensityLabel: 'Intensity block' }, '6': { sets: 4, reps: 6, intensityLabel: 'Intensity block' },
      '7': { sets: 4, reps: 6, intensityLabel: 'Strength block' }, '8': { sets: 2, reps: 8, intensityLabel: 'Deload' },
      '9': { sets: 4, reps: 5, intensityLabel: 'Peak strength' }, '10': { sets: 4, reps: 5, intensityLabel: 'Peak strength' },
      '11': { sets: 4, reps: 5, intensityLabel: 'Peak strength' }, '12': { sets: 2, reps: 6, intensityLabel: 'Final assessment' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Athletic Development', philosophy: 'Balanced athletic development through concurrent strength and conditioning across a 12-week cycle.' },
  },

  // ── TACTICAL ──────────────────────────────────────────────────────────────

  {
    id: 'tactical_athlete',
    name: 'Tactical Athlete Program',
    tagline: 'Military & first responder performance standard',
    description: 'A 12-week program built around tactical fitness standards. Combines heavy strength work, high-rep calisthenics, loaded carries, and sustained running capacity. Designed for military, police, firefighters, and those who want to meet that standard.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'tactical',
    subcategory: 'military-fitness',
    tags: ['tactical', 'military', 'fitness-test', 'strength', 'running', 'calisthenics', 'advanced', 'first-responder'],
    durationWeeks: 12,
    sessionsPerWeek: 5,
    sessionDurationMinutes: { min: 55, max: 80 },
    difficulty: 'advanced',
    equipment: ['barbell', 'dumbbells', 'rack', 'bench', 'pull-up-bar'],
    equipmentTier: 'gym',
    goals: ['tactical-fitness', 'strength', 'running', 'military-standards'],
    metrics: { strengthEmphasis: 70, hypertrophyEmphasis: 40, enduranceEmphasis: 75, conditioningEmphasis: 80, recoveryDemand: 80, weeklyVolumeScore: 80 },
    highlights: ['Military fitness standards', 'Strength + running + calisthenics', 'Loaded carry emphasis', 'Tactical conditioning'],
    expectedOutcomes: ['Pass any fitness test', 'Real-world strength', 'Running endurance', 'Elite work capacity'],
    popularity: 74, rating: 4.6, ratingCount: 189, completionRate: 0.49, enrolledCount: 1340,
    featured: false, verified: true, isNew: true,
    coverGradient: ['#0a1208', '#1a2618'], accentColor: '#84cc16', icon: '🎖️',
    collections: ['tactical-collection', 'new-programs'],
    days: {
      mon: { title: 'Strength + Calisthenics', badge: 'Tactical', color: 'var(--accent-green)', desc: 'Heavy compounds + high-rep pull-ups/push-ups.', runs: 'Rest', lifts: ['Deadlift', 'Pull-Ups', 'Bench Press', 'Back Squat', 'Hanging Leg Raises'] },
      tue: { title: 'Run + Loaded Carry', badge: 'Tactical', color: 'var(--accent-amber)', desc: 'Run intervals + loaded carries.', runs: '🏃 5km timed + 3×400m loaded carry', lifts: [] },
      wed: { title: 'Upper Strength', badge: 'Tactical', color: 'var(--accent-blue)', desc: 'Upper body strength and calisthenics.', runs: 'Rest', lifts: ['Standing OHP', 'Barbell Row', 'Dips', 'Chin-Ups', 'Push-Ups'] },
      thu: { title: 'Long Run', badge: 'Tactical', color: 'var(--accent-green)', desc: 'Sustained aerobic run.', runs: '🏃 45-60min Zone 2 run', lifts: [] },
      fri: { title: 'Lower Strength + Conditioning', badge: 'Tactical', color: 'var(--accent-pink)', desc: 'Heavy lower body + conditioning.', runs: '🔥 Conditioning circuit post-lift', lifts: ['Back Squat', 'Romanian Deadlift', 'Bulgarian Split Squat', 'Calf Raises'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 8, intensityLabel: 'Foundation — establish baselines' },
      '2': { sets: 4, reps: 8, intensityLabel: 'Build volume' },
      '3': { sets: 4, reps: 6, intensityLabel: 'Intensity increase' },
      '4': { sets: 2, reps: 8, intensityLabel: 'Deload' },
      '5': { sets: 4, reps: 6, intensityLabel: 'Strength block' },
      '6': { sets: 4, reps: 5, intensityLabel: 'Heavy strength' },
      '7': { sets: 5, reps: 5, intensityLabel: 'Peak strength' },
      '8': { sets: 2, reps: 6, intensityLabel: 'Deload' },
      '9': { sets: 4, reps: 5, intensityLabel: 'Final strength block' },
      '10': { sets: 4, reps: 4, intensityLabel: 'Peak block' },
      '11': { sets: 3, reps: 5, intensityLabel: 'Taper strength' },
      '12': { sets: 2, reps: 5, intensityLabel: 'Test week' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Tactical Fitness', philosophy: 'Develop the full tactical fitness profile: strength, endurance, calisthenics, and loaded movement.' },
  },

];

// Quick lookup map by ID
export const CATALOG_MAP = Object.fromEntries(
  PROGRAM_CATALOG.map(p => [p.id, p])
);

// Get catalog entry for a program ID
export function getCatalogEntry(id) {
  return CATALOG_MAP[id] || null;
}

// Get all programs for a category
export function getProgramsByCategory(category) {
  return PROGRAM_CATALOG.filter(p => p.category === category);
}

// Get featured programs
export function getFeaturedPrograms() {
  return PROGRAM_CATALOG.filter(p => p.featured);
}

// Get programs for a collection key
export function getProgramsForCollection(collectionKey) {
  return PROGRAM_CATALOG.filter(p => p.collections?.includes(collectionKey));
}
