// =============================================================================
// AUTO-GENERATED — split from catalog.js. Edit individual entries here.
// =============================================================================

export default [
  // ── BODY COMPOSITION ──────────────────────────────────────────────────────

  {
    id: 'cut_phase',
    name: 'Cut Phase — Fat Loss Protocol',
    tagline: 'Preserve muscle while shedding body fat',
    description: 'An 8-week fat loss program designed to preserve maximum muscle mass during a caloric deficit. Higher frequency lifting, strategic cardio, and progressive overload combine to maintain strength while body composition transforms.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'body_composition',
    subcategory: 'fat-loss',
    tags: ['fat-loss', 'cutting', 'body-composition', 'cardio', 'muscle-preservation', 'deficit', 'intermediate'],
    durationWeeks: 8,
    sessionsPerWeek: 5,
    sessionDurationMinutes: { min: 45, max: 65 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'dumbbells', 'rack', 'bench'],
    equipmentTier: 'gym',
    goals: ['fat-loss', 'body-composition', 'muscle-preservation'],
    metrics: { strengthEmphasis: 55, hypertrophyEmphasis: 45, enduranceEmphasis: 40, conditioningEmphasis: 55, recoveryDemand: 55, weeklyVolumeScore: 65 },
    highlights: ['Muscle preservation focus', 'Strategic cardio included', 'Higher frequency', 'Evidence-based approach'],
    expectedOutcomes: ['Significant fat loss', 'Maintained muscle mass', 'Improved definition', 'Better body composition'],
    popularity: 81, rating: 4.5, ratingCount: 534, completionRate: 0.54, enrolledCount: 3600,
    featured: false, verified: true, isNew: true,
    coverGradient: ['#1a0e0e', '#3d2222'], accentColor: '#f59e0b', icon: '🔥',
    collections: ['body-composition-collection', 'most-popular', 'new-programs'],
    days: {
      mon: { title: 'Upper A', badge: 'Cut Phase', color: 'var(--accent-blue)', desc: 'Push + pull with moderate volume.', runs: 'Optional: 20min Zone 2 cardio', lifts: ['Bench Press', 'Pull-Ups', 'Incline DB Press', 'Barbell Row', 'Lateral Raise'] },
      tue: { title: 'Lower A + Cardio', badge: 'Cut Phase', color: 'var(--accent-green)', desc: 'Legs + cardio conditioning.', runs: '🏃 20-30min cardio (HIIT or Zone 2)', lifts: ['Back Squat', 'Romanian Deadlift', 'Leg Press', 'Calf Raises'] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest or light walk.', runs: 'Rest', lifts: [] },
      thu: { title: 'Upper B', badge: 'Cut Phase', color: 'var(--accent-blue)', desc: 'Push + pull volume focus.', runs: 'Optional: 20min Zone 2', lifts: ['Standing OHP', 'Deadlift', 'Dips', 'Chin-Ups', 'Face Pull'] },
      fri: { title: 'Lower B + Cardio', badge: 'Cut Phase', color: 'var(--accent-green)', desc: 'Lower body + conditioning.', runs: '🏃 25-35min cardio', lifts: ['Front Squat', 'Bulgarian Split Squat', 'Hamstring Curl', 'Calf Raises'] },
      sat: { title: 'Cardio Day', badge: 'Zone 2', color: 'var(--accent-amber)', desc: 'Steady state cardio day.', runs: '🏃 40-50min Zone 2 steady state', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 12, intensityLabel: 'Volume focus — muscle preservation' },
      '2': { sets: 3, reps: 12, intensityLabel: 'Volume focus' },
      '3': { sets: 4, reps: 10, intensityLabel: 'Build intensity' },
      '4': { sets: 4, reps: 10, intensityLabel: 'Build intensity' },
      '5': { sets: 4, reps: 8, intensityLabel: 'Strength focus begins' },
      '6': { sets: 4, reps: 8, intensityLabel: 'Strength focus' },
      '7': { sets: 4, reps: 6, intensityLabel: 'Heavy strength phase' },
      '8': { sets: 3, reps: 8, intensityLabel: 'Final week — assessment' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Fat Loss & Muscle Preservation', philosophy: 'Strategic fat loss through higher frequency training, progressive overload, and structured cardio.' },
  },

  {
    id: 'body_recomp',
    name: 'Body Recomposition Protocol',
    tagline: 'Lose fat and gain muscle simultaneously',
    description: 'A 16-week program targeting body recomposition — the simultaneous loss of fat and gain of muscle. Achievable for beginners and those returning to training. Combines progressive overload with moderate cardio at maintenance calories.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'body_composition',
    subcategory: 'recomposition',
    tags: ['recomposition', 'fat-loss', 'muscle-gain', 'beginner', 'intermediate', 'body-composition', 'cardio'],
    durationWeeks: 16,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 40, max: 60 },
    difficulty: 'beginner',
    equipment: ['dumbbells', 'barbell', 'rack', 'bench'],
    equipmentTier: 'gym',
    goals: ['body-composition', 'fat-loss', 'muscle-gain', 'general-health'],
    metrics: { strengthEmphasis: 55, hypertrophyEmphasis: 60, enduranceEmphasis: 35, conditioningEmphasis: 40, recoveryDemand: 45, weeklyVolumeScore: 55 },
    highlights: ['Simultaneous fat loss + muscle gain', 'Beginner-friendly structure', '4 days/week', 'Nutrition-agnostic'],
    expectedOutcomes: ['Improved body composition', 'Visible muscle definition', 'Strength improvements', 'Healthier lifestyle'],
    popularity: 79, rating: 4.5, ratingCount: 467, completionRate: 0.60, enrolledCount: 3400,
    featured: false, verified: true, isNew: true,
    coverGradient: ['#1a0e0e', '#3d2222'], accentColor: '#f59e0b', icon: '🔥',
    collections: ['body-composition-collection', 'beginner-friendly', 'new-programs'],
    days: {
      mon: { title: 'Full Body A', badge: 'Recomp', color: 'var(--accent-blue)', desc: 'Full body strength circuit.', runs: 'Optional: 15min easy cardio', lifts: ['Back Squat', 'Bench Press', 'Barbell Row', 'Lateral Raise', 'Hammer Curl'] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest or light walk.', runs: 'Rest', lifts: [] },
      wed: { title: 'Full Body B', badge: 'Recomp', color: 'var(--accent-green)', desc: 'Full body strength — different movements.', runs: 'Optional: 15min easy cardio', lifts: ['Deadlift', 'Standing OHP', 'Pull-Ups', 'Romanian Deadlift', 'Tricep Band Pushdown'] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Full Body C', badge: 'Recomp', color: 'var(--accent-blue)', desc: 'Volume focus full body.', runs: 'Optional: 20min cardio', lifts: ['Back Squat', 'Incline DB Press', 'Chin-Ups', 'Bulgarian Split Squat', 'Face Pull'] },
      sat: { title: 'Cardio + Core', badge: 'Conditioning', color: 'var(--accent-amber)', desc: 'Optional cardio and core work.', runs: '🏃 30-45min Zone 2 cardio', lifts: ['Core/Plank', 'Hanging Leg Raises', 'Ab Wheel Rollouts'] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 12, intensityLabel: 'Base volume establishment' },
      '2': { sets: 3, reps: 12, intensityLabel: 'Base volume' },
      '3': { sets: 3, reps: 10, intensityLabel: 'Slight intensity increase' },
      '4': { sets: 3, reps: 10, intensityLabel: 'Volume build' },
      '5': { sets: 4, reps: 10, intensityLabel: 'Volume increase' },
      '6': { sets: 4, reps: 10, intensityLabel: 'Volume peak' },
      '7': { sets: 4, reps: 8, intensityLabel: 'Intensity phase' },
      '8': { sets: 2, reps: 12, intensityLabel: 'Deload' },
      '9': { sets: 4, reps: 8, intensityLabel: 'Strength phase' },
      '10': { sets: 4, reps: 8, intensityLabel: 'Strength phase' },
      '11': { sets: 4, reps: 6, intensityLabel: 'Heavy strength' },
      '12': { sets: 4, reps: 6, intensityLabel: 'Heavy strength' },
      '13': { sets: 4, reps: 8, intensityLabel: 'Back to volume' },
      '14': { sets: 4, reps: 8, intensityLabel: 'Volume + strength blend' },
      '15': { sets: 4, reps: 6, intensityLabel: 'Final strength block' },
      '16': { sets: 2, reps: 10, intensityLabel: 'Final assessment week' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Body Recomposition', philosophy: 'Progressive overload combined with cardio at maintenance calories achieves simultaneous fat loss and muscle gain.' },
  },
  // ── GENERAL FITNESS ───────────────────────────────────────────────────────

  {
    id: 'beginner_full_body',
    name: 'Beginner Full Body',
    tagline: 'The perfect starting point for complete beginners',
    description: 'An 8-week introduction to structured training. Three full-body sessions per week teaching fundamental movement patterns while building initial strength and conditioning. Designed for those brand new to the gym.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'general_fitness',
    subcategory: 'beginner',
    tags: ['beginner', 'full-body', 'fundamentals', '3-day', 'gym-newbie', 'foundation', 'simple'],
    durationWeeks: 8,
    sessionsPerWeek: 3,
    sessionDurationMinutes: { min: 30, max: 45 },
    difficulty: 'beginner',
    equipment: ['dumbbells', 'barbell', 'rack', 'bench'],
    equipmentTier: 'gym',
    goals: ['beginner-gains', 'general-health', 'movement-fundamentals'],
    metrics: { strengthEmphasis: 60, hypertrophyEmphasis: 50, enduranceEmphasis: 15, conditioningEmphasis: 20, recoveryDemand: 30, weeklyVolumeScore: 35 },
    highlights: ['3 days/week only', 'Full body each session', 'Beginner-perfect', 'Fundamental movements'],
    expectedOutcomes: ['Strength foundation built', 'Movement patterns mastered', 'Gym confidence gained', 'First real gains'],
    popularity: 88, rating: 4.7, ratingCount: 1230, completionRate: 0.69, enrolledCount: 7200,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0e1a1e', '#1a3040'], accentColor: '#06b6d4', icon: '🎯',
    collections: ['beginner-friendly', 'most-popular', 'time-efficient', 'general-fitness-collection'],
    days: {
      mon: { title: 'Full Body A', badge: 'Beginner', color: 'var(--accent-blue)', desc: 'Squat, Push, Pull fundamentals.', runs: 'Rest', lifts: ['Back Squat', 'Bench Press', 'Barbell Row', 'Lateral Raise', 'Hammer Curl'] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest. Let your body adapt.', runs: 'Rest', lifts: [] },
      wed: { title: 'Full Body B', badge: 'Beginner', color: 'var(--accent-green)', desc: 'Hinge, Press, Row variations.', runs: 'Rest', lifts: ['Deadlift', 'Standing OHP', 'Lat Pulldown', 'Romanian Deadlift', 'Tricep Band Pushdown'] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Full Body C', badge: 'Beginner', color: 'var(--accent-amber)', desc: 'Compound movement variety.', runs: 'Rest', lifts: ['Back Squat', 'Incline DB Press', 'Pull-Ups', 'Bulgarian Split Squat', 'Barbell Curl'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest or light activity.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 8, intensityLabel: 'Foundation — focus on form' },
      '2': { sets: 3, reps: 8, intensityLabel: 'Foundation — add weight slowly' },
      '3': { sets: 3, reps: 10, intensityLabel: 'Volume build' },
      '4': { sets: 3, reps: 10, intensityLabel: 'Volume build' },
      '5': { sets: 4, reps: 8, intensityLabel: 'Intensity increase' },
      '6': { sets: 4, reps: 8, intensityLabel: 'Intensity increase' },
      '7': { sets: 4, reps: 6, intensityLabel: 'Heavier focus' },
      '8': { sets: 3, reps: 8, intensityLabel: 'Final week — celebrate progress' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Beginner Fundamentals', philosophy: 'Master the six fundamental movement patterns through progressive overload across an 8-week foundation.' },
  },

  {
    id: 'athletic_base',
    name: 'Athletic Base Builder',
    tagline: 'All-around athleticism for the everyday athlete',
    description: 'A 12-week general athletic development program. Combines strength, power, conditioning, and mobility work into a balanced program that improves performance across all physical domains. Suitable for anyone who wants to be genuinely fit.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'general_fitness',
    subcategory: 'athletic',
    tags: ['athletic', 'general-fitness', 'strength', 'conditioning', 'cardio', 'balanced', 'intermediate'],
    durationWeeks: 12,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 45, max: 65 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'dumbbells', 'rack', 'bench'],
    equipmentTier: 'gym',
    goals: ['general-athleticism', 'fitness', 'conditioning', 'strength'],
    metrics: { strengthEmphasis: 60, hypertrophyEmphasis: 50, enduranceEmphasis: 50, conditioningEmphasis: 60, recoveryDemand: 55, weeklyVolumeScore: 60 },
    highlights: ['Well-rounded athletic development', '4 days/week', 'Strength + cardio balance', 'Progressive structure'],
    expectedOutcomes: ['Improved all-round fitness', 'Stronger and fitter', 'Better conditioning', 'Athletic physique'],
    popularity: 76, rating: 4.5, ratingCount: 312, completionRate: 0.62, enrolledCount: 2400,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0e1a1e', '#1a3040'], accentColor: '#06b6d4', icon: '🎯',
    collections: ['general-fitness-collection', 'time-efficient'],
    days: {
      mon: { title: 'Strength A', badge: 'Athletic', color: 'var(--accent-blue)', desc: 'Compound strength focus.', runs: 'Rest', lifts: ['Back Squat', 'Bench Press', 'Pull-Ups', 'Lateral Raise', 'Hammer Curl'] },
      tue: { title: 'Conditioning', badge: 'Athletic', color: 'var(--accent-amber)', desc: 'Cardio + conditioning circuit.', runs: '🏃 30min run + 3×circuit work', lifts: [] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: { title: 'Strength B', badge: 'Athletic', color: 'var(--accent-green)', desc: 'Hinge, row, press focus.', runs: 'Rest', lifts: ['Deadlift', 'Barbell Row', 'Standing OHP', 'Romanian Deadlift', 'Tricep Band Pushdown'] },
      fri: { title: 'Mixed Cardio', badge: 'Athletic', color: 'var(--accent-pink)', desc: 'Mixed effort cardio work.', runs: '🏃 40min mixed effort run', lifts: [] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest or light activity.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 10, intensityLabel: 'Foundation' }, '2': { sets: 3, reps: 10, intensityLabel: 'Foundation' },
      '3': { sets: 4, reps: 8, intensityLabel: 'Build' }, '4': { sets: 2, reps: 10, intensityLabel: 'Deload' },
      '5': { sets: 4, reps: 8, intensityLabel: 'Intensity block' }, '6': { sets: 4, reps: 6, intensityLabel: 'Intensity block' },
      '7': { sets: 4, reps: 6, intensityLabel: 'Strength block' }, '8': { sets: 2, reps: 8, intensityLabel: 'Deload' },
      '9': { sets: 4, reps: 5, intensityLabel: 'Peak strength' }, '10': { sets: 4, reps: 5, intensityLabel: 'Peak strength' },
      '11': { sets: 4, reps: 5, intensityLabel: 'Peak strength' }, '12': { sets: 2, reps: 6, intensityLabel: 'Final assessment' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Athletic Development', philosophy: 'Balanced athletic development through concurrent strength and conditioning across a 12-week cycle.' },
  },
  // ── BODY COMPOSITION — ADDITIONAL ─────────────────────────────────────────

  {
    id: 'lean_bulk',
    name: 'Lean Bulk Protocol',
    tagline: 'Build maximum muscle with minimum fat — the smart way',
    description: 'A 16-week lean bulking program designed to maximise muscle gain while keeping fat gain to an absolute minimum. Higher-volume hypertrophy training, strategic calorie surplus guidance, and built-in cardio to maintain conditioning. The anti-bulk bulk.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'body_composition',
    subcategory: 'lean-bulk',
    tags: ['lean-bulk', 'muscle', 'hypertrophy', 'body-composition', 'bulk', 'mass', 'nutrition', 'recomp'],
    durationWeeks: 16,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 55, max: 80 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'dumbbells', 'cables', 'rack', 'bench'],
    equipmentTier: 'full-gym',
    goals: ['muscle-gain', 'lean-bulk', 'body-composition', 'hypertrophy'],
    metrics: { strengthEmphasis: 65, hypertrophyEmphasis: 90, enduranceEmphasis: 25, conditioningEmphasis: 30, recoveryDemand: 60, weeklyVolumeScore: 70 },
    highlights: ['Muscle-first approach', 'Cardio included to manage fat', 'Calorie surplus guidance', 'Upper/lower split for frequency'],
    expectedOutcomes: ['Significant lean muscle gain', 'Minimal fat accumulation', 'Strength PRs', 'Improved body composition'],
    popularity: 81, rating: 4.5, ratingCount: 720, completionRate: 0.61, enrolledCount: 4500,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a1520', '#14253a'], accentColor: '#3b82f6', icon: '📈',
    collections: ['body-composition-collection', 'most-popular', 'hypertrophy-collection'],
    days: {
      mon: { title: 'Upper — Push Focus', badge: 'Lean Bulk', color: 'var(--accent-blue)', desc: 'Chest, shoulders, triceps — volume focus.', runs: 'Rest', lifts: ['Bench Press 4×8', 'Incline DB Press 4×10', 'Standing OHP 3×8', 'Lateral Raise 3×12', 'Tricep Extension 3×12'] },
      tue: { title: 'Lower — Quad Focus', badge: 'Lean Bulk', color: 'var(--accent-purple)', desc: 'Squat pattern + accessories.', runs: '🏃 20min easy cardio post-session', lifts: ['Back Squat 4×8', 'Leg Press 4×12', 'Walking Lunges 3×20', 'Leg Extension 3×12', 'Calf Raises 3×15'] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: { title: 'Upper — Pull Focus', badge: 'Lean Bulk', color: 'var(--accent-green)', desc: 'Back, biceps, rear delts — volume focus.', runs: 'Rest', lifts: ['Barbell Row 4×8', 'Pull-Ups 4×10', 'Seated Cable Row 3×12', 'Face Pulls 3×15', 'Barbell Curl 3×10'] },
      fri: { title: 'Lower — Hinge Focus', badge: 'Lean Bulk', color: 'var(--accent-amber)', desc: 'Deadlift pattern + accessories.', runs: '🏃 20min easy cardio post-session', lifts: ['Deadlift 4×6', 'Romanian Deadlift 3×10', 'Hamstring Curl 3×12', 'Bulgarian Split Squat 3×10', 'Calf Raises 3×15'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 10, intensityLabel: 'Phase 1: Foundation — moderate surplus' },
      '2': { sets: 3, reps: 10, intensityLabel: 'Phase 1: Foundation' },
      '3': { sets: 4, reps: 10, intensityLabel: 'Phase 1: Volume increase' },
      '4': { sets: 4, reps: 8, intensityLabel: 'Phase 1: Intensity build' },
      '5': { sets: 4, reps: 8, intensityLabel: 'Phase 2: Higher intensity, moderate volume' },
      '6': { sets: 4, reps: 6, intensityLabel: 'Phase 2: Strength sub-phase' },
      '7': { sets: 5, reps: 6, intensityLabel: 'Phase 2: Peak strength' },
      '8': { sets: 2, reps: 8, intensityLabel: 'Deload — body recomposition check' },
      '9': { sets: 4, reps: 12, intensityLabel: 'Phase 3: High volume hypertrophy' },
      '10': { sets: 4, reps: 12, intensityLabel: 'Phase 3: High volume hypertrophy' },
      '11': { sets: 5, reps: 10, intensityLabel: 'Phase 3: Moderate intensity, high volume' },
      '12': { sets: 5, reps: 8, intensityLabel: 'Phase 3: Peak volume' },
      '13': { sets: 4, reps: 8, intensityLabel: 'Phase 4: Consolidate gains' },
      '14': { sets: 4, reps: 6, intensityLabel: 'Phase 4: Strength-hypertrophy blend' },
      '15': { sets: 4, reps: 6, intensityLabel: 'Phase 4: Final push' },
      '16': { sets: 2, reps: 8, intensityLabel: 'Deload — assess, photograph, plan next cycle' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Lean Bulk', philosophy: 'Muscle gain without the blubber. A modest surplus, high protein, strategic cardio, and progressive overload builds the lean physique you actually want.' },
  },
  // ── GENERAL FITNESS — ADDITIONAL ──────────────────────────────────────────

  {
    id: 'kettlebell_minimalist',
    name: 'Kettlebell Minimalist',
    tagline: 'One bell. Full body. Anywhere.',
    description: 'A 10-week kettlebell-only program requiring just one bell and minimal space. Based on hardstyle kettlebell principles: the swing, the press, the goblet squat, the get-up. Develops strength, conditioning, and mobility simultaneously. The perfect home or travel program.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'general_fitness',
    subcategory: 'kettlebell',
    tags: ['kettlebell', 'home', 'minimal-equipment', 'conditioning', 'strength', 'swing', 'minimalist', 'time-efficient'],
    durationWeeks: 10,
    sessionsPerWeek: 3,
    sessionDurationMinutes: { min: 25, max: 40 },
    difficulty: 'beginner',
    equipment: ['kettlebell'],
    equipmentTier: 'minimal',
    goals: ['general-health', 'conditioning', 'home-training', 'minimalist'],
    metrics: { strengthEmphasis: 55, hypertrophyEmphasis: 40, enduranceEmphasis: 55, conditioningEmphasis: 70, recoveryDemand: 40, weeklyVolumeScore: 40 },
    highlights: ['Single kettlebell needed', 'Train anywhere', '25-40 min sessions', 'Hardstyle technique focus'],
    expectedOutcomes: ['Full body conditioning', 'Strong hips and core', 'Efficient movement patterns', 'Travel-proof fitness'],
    popularity: 76, rating: 4.6, ratingCount: 540, completionRate: 0.76, enrolledCount: 3800,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#101010', '#1e1e1e'], accentColor: '#9ca3af', icon: '🔔',
    collections: ['time-efficient', 'general-fitness-collection', 'beginner-friendly'],
    days: {
      mon: { title: 'Swing + Press', badge: 'KB', color: 'var(--accent-blue)', desc: 'Posterior chain + push.', runs: 'Rest', lifts: ['KB Swing 5×20', 'KB Press 4×8', 'Goblet Squat 3×12', 'KB Row 3×10', 'Hollow Body Hold 3×30s'] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Turkish Get-Up + Swing', badge: 'KB', color: 'var(--accent-amber)', desc: 'Skill and conditioning.', runs: 'Rest', lifts: ['Turkish Get-Up 5×1 each side', 'KB Swing 5×20', 'KB Clean 3×5 each', 'KB Windmill 3×5 each', 'Farmer Carry 3×40m'] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Full Body Conditioning', badge: 'KB', color: 'var(--accent-green)', desc: 'Circuit for total conditioning.', runs: 'Rest', lifts: ['KB Swing 3×30', 'Goblet Squat 3×15', 'KB Press 3×10', 'KB Row 3×10', 'KB Snatch 3×5 each'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 10, intensityLabel: 'Technique — learn the swing and get-up' },
      '2': { sets: 3, reps: 15, intensityLabel: 'Volume increase — sets the same' },
      '3': { sets: 4, reps: 15, intensityLabel: 'Add a set — density increases' },
      '4': { sets: 4, reps: 20, intensityLabel: 'Condition focus — higher reps' },
      '5': { sets: 5, reps: 15, intensityLabel: 'Volume peak' },
      '6': { sets: 3, reps: 10, intensityLabel: 'Deload — heavier KB if available' },
      '7': { sets: 5, reps: 15, intensityLabel: 'Second volume block' },
      '8': { sets: 5, reps: 20, intensityLabel: 'Peak conditioning' },
      '9': { sets: 4, reps: 15, intensityLabel: 'Consolidation' },
      '10': { sets: 3, reps: 10, intensityLabel: 'Final week — max KB weight throughout' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Kettlebell Training', philosophy: 'The kettlebell swing is the king of exercises. Everything else supports it. Master the fundamentals, build the machine.' },
  },

  {
    id: 'home_athlete',
    name: 'Home Athlete Program',
    tagline: 'No gym. No excuses. Real results.',
    description: 'A 10-week bodyweight and minimal-equipment program for training at home. Three days of structured bodyweight strength work using progressions that make push-ups, pull-ups, and squats genuinely challenging. No equipment required beyond a pull-up bar for some sessions.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'general_fitness',
    subcategory: 'home-training',
    tags: ['home', 'bodyweight', 'no-equipment', 'calisthenics', 'beginner', 'push-ups', 'pull-ups', 'minimal'],
    durationWeeks: 10,
    sessionsPerWeek: 3,
    sessionDurationMinutes: { min: 30, max: 45 },
    difficulty: 'beginner',
    equipment: ['pull-up-bar'],
    equipmentTier: 'minimal',
    goals: ['home-training', 'calisthenics', 'general-health', 'beginner-fitness'],
    metrics: { strengthEmphasis: 60, hypertrophyEmphasis: 45, enduranceEmphasis: 35, conditioningEmphasis: 40, recoveryDemand: 30, weeklyVolumeScore: 35 },
    highlights: ['Zero equipment needed', 'Progressive bodyweight progressions', 'Train at home or travel', 'Beginner-friendly structure'],
    expectedOutcomes: ['10+ pull-ups', '30+ push-ups', 'Pistol squat progress', 'Real bodyweight strength'],
    popularity: 85, rating: 4.5, ratingCount: 1800, completionRate: 0.70, enrolledCount: 11000,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a0a14', '#141426'], accentColor: '#6366f1', icon: '🏠',
    collections: ['beginner-friendly', 'time-efficient', 'most-popular', 'general-fitness-collection'],
    days: {
      mon: { title: 'Push Day', badge: 'Bodyweight', color: 'var(--accent-blue)', desc: 'Push-up progressions and shoulders.', runs: 'Rest', lifts: ['Push-Ups 4×max', 'Pike Push-Ups 3×10', 'Diamond Push-Ups 3×10', 'Plank Hold 3×45s', 'Tricep Dips 3×12'] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Pull Day', badge: 'Bodyweight', color: 'var(--accent-green)', desc: 'Pull-up progressions and rows.', runs: 'Rest', lifts: ['Pull-Ups 4×max', 'Inverted Rows 3×10', 'Chin-Ups 3×8', 'Band Pull-Aparts 3×20', 'Dead Hang 3×30s'] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Legs + Core', badge: 'Bodyweight', color: 'var(--accent-amber)', desc: 'Squat progressions and core work.', runs: 'Rest', lifts: ['Bodyweight Squat 4×20', 'Bulgarian Split Squat 3×10 each', 'Hip Hinge 3×15', 'Hollow Body 3×30s', 'Bicycle Crunches 3×20'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 10, intensityLabel: 'Foundation — find your base reps' },
      '2': { sets: 3, reps: 12, intensityLabel: 'Volume increase' },
      '3': { sets: 4, reps: 10, intensityLabel: 'Add a set' },
      '4': { sets: 4, reps: 12, intensityLabel: 'Volume peak — first block' },
      '5': { sets: 3, reps: 8, intensityLabel: 'Harder progressions — new baseline' },
      '6': { sets: 4, reps: 8, intensityLabel: 'Intensity block' },
      '7': { sets: 4, reps: 10, intensityLabel: 'Volume increases again' },
      '8': { sets: 5, reps: 10, intensityLabel: 'Peak volume' },
      '9': { sets: 4, reps: 8, intensityLabel: 'Advanced progressions' },
      '10': { sets: 3, reps: 5, intensityLabel: 'Hardest progressions — test your ceiling' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Home Training', philosophy: 'Your body is the best training tool available. Master bodyweight movement before loading it.' },
  },
  // ── TACTICAL ──────────────────────────────────────────────────────────────

  {
    id: 'tactical_athlete',
    name: 'Tactical Athlete Program',
    tagline: 'Military & first responder performance standard',
    description: 'A 12-week program built around tactical fitness standards. Combines heavy strength work, high-rep calisthenics, loaded carries, and sustained running capacity. Designed for military, police, firefighters, and those who want to meet that standard.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'tactical',
    subcategory: 'military-fitness',
    tags: ['tactical', 'military', 'fitness-test', 'strength', 'running', 'calisthenics', 'advanced', 'first-responder'],
    durationWeeks: 12,
    sessionsPerWeek: 5,
    sessionDurationMinutes: { min: 55, max: 80 },
    difficulty: 'advanced',
    equipment: ['barbell', 'dumbbells', 'rack', 'bench', 'pull-up-bar'],
    equipmentTier: 'gym',
    goals: ['tactical-fitness', 'strength', 'running', 'military-standards'],
    metrics: { strengthEmphasis: 70, hypertrophyEmphasis: 40, enduranceEmphasis: 75, conditioningEmphasis: 80, recoveryDemand: 80, weeklyVolumeScore: 80 },
    highlights: ['Military fitness standards', 'Strength + running + calisthenics', 'Loaded carry emphasis', 'Tactical conditioning'],
    expectedOutcomes: ['Pass any fitness test', 'Real-world strength', 'Running endurance', 'Elite work capacity'],
    popularity: 74, rating: 4.6, ratingCount: 189, completionRate: 0.49, enrolledCount: 1340,
    featured: false, verified: true, isNew: true,
    coverGradient: ['#0a1208', '#1a2618'], accentColor: '#84cc16', icon: '🎖️',
    collections: ['tactical-collection', 'new-programs'],
    days: {
      mon: { title: 'Strength + Calisthenics', badge: 'Tactical', color: 'var(--accent-green)', desc: 'Heavy compounds + high-rep pull-ups/push-ups.', runs: 'Rest', lifts: ['Deadlift', 'Pull-Ups', 'Bench Press', 'Back Squat', 'Hanging Leg Raises'] },
      tue: { title: 'Run + Loaded Carry', badge: 'Tactical', color: 'var(--accent-amber)', desc: 'Run intervals + loaded carries.', runs: '🏃 5km timed + 3×400m loaded carry', lifts: [] },
      wed: { title: 'Upper Strength', badge: 'Tactical', color: 'var(--accent-blue)', desc: 'Upper body strength and calisthenics.', runs: 'Rest', lifts: ['Standing OHP', 'Barbell Row', 'Dips', 'Chin-Ups', 'Push-Ups'] },
      thu: { title: 'Long Run', badge: 'Tactical', color: 'var(--accent-green)', desc: 'Sustained aerobic run.', runs: '🏃 45-60min Zone 2 run', lifts: [] },
      fri: { title: 'Lower Strength + Conditioning', badge: 'Tactical', color: 'var(--accent-pink)', desc: 'Heavy lower body + conditioning.', runs: '🔥 Conditioning circuit post-lift', lifts: ['Back Squat', 'Romanian Deadlift', 'Bulgarian Split Squat', 'Calf Raises'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 8, intensityLabel: 'Foundation — establish baselines' },
      '2': { sets: 4, reps: 8, intensityLabel: 'Build volume' },
      '3': { sets: 4, reps: 6, intensityLabel: 'Intensity increase' },
      '4': { sets: 2, reps: 8, intensityLabel: 'Deload' },
      '5': { sets: 4, reps: 6, intensityLabel: 'Strength block' },
      '6': { sets: 4, reps: 5, intensityLabel: 'Heavy strength' },
      '7': { sets: 5, reps: 5, intensityLabel: 'Peak strength' },
      '8': { sets: 2, reps: 6, intensityLabel: 'Deload' },
      '9': { sets: 4, reps: 5, intensityLabel: 'Final strength block' },
      '10': { sets: 4, reps: 4, intensityLabel: 'Peak block' },
      '11': { sets: 3, reps: 5, intensityLabel: 'Taper strength' },
      '12': { sets: 2, reps: 5, intensityLabel: 'Test week' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Tactical Fitness', philosophy: 'Develop the full tactical fitness profile: strength, endurance, calisthenics, and loaded movement.' },
  },
  // ── TRIATHLON ─────────────────────────────────────────────────────────────────

  {
    id: 'sprint_triathlon_prep',
    name: 'Sprint Triathlon Prep',
    tagline: '8 weeks to your first sprint triathlon finish line',
    description: 'An 8-week programme preparing you for a 750m swim / 20km bike / 5km run sprint triathlon. Builds swim technique, cycling power, and run fitness simultaneously through carefully structured multi-sport sessions and brick workouts that simulate race-day transitions.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    source: 'internal',
    category: 'triathlon',
    subcategory: 'sprint',
    tags: ['triathlon', 'sprint-tri', 'swimming', 'cycling', 'running', 'multi-sport', 'beginner', '8-week', 'brick'],
    durationWeeks: 8,
    sessionsPerWeek: 5,
    sessionDurationMinutes: { min: 45, max: 75 },
    difficulty: 'intermediate',
    equipment: ['bike', 'swim-access'],
    equipmentTier: 'gym',
    goals: ['triathlon', 'race-completion', 'multi-sport', 'endurance'],
    metrics: { strengthEmphasis: 20, hypertrophyEmphasis: 5, enduranceEmphasis: 90, conditioningEmphasis: 70, recoveryDemand: 60, weeklyVolumeScore: 65 },
    highlights: ['All three tri disciplines', '8-week race preparation', 'Brick sessions every week', 'Structured taper included'],
    expectedOutcomes: ['Complete a sprint triathlon', 'Efficient swim technique', 'Cycling power base', 'Run-off-bike capability'],
    popularity: 72, rating: 4.6, ratingCount: 234, completionRate: 0.60, enrolledCount: 1680,
    featured: false, verified: true, isNew: true,
    coverGradient: ['#0a1020', '#0d2a3d'], accentColor: '#0ea5e9', icon: '🏊',
    collections: ['triathlon-collection', 'new-programs', 'endurance-collection'],
    days: {
      mon: {
        title: 'Swim Technique', badge: 'Triathlon', color: 'var(--accent-blue)',
        desc: 'Pool session — technique drills + aerobic endurance sets.', runs: '🏊 Pool: 45min technique + endurance',
        lifts: [],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Warm-Up',     type: 'warmup',  duration: '200m',  pace: 'Easy freestyle',       description: 'Easy freestyle to warm up the shoulders and establish breathing rhythm' },
            { name: 'Drill Set',   type: 'mainSet', duration: '10 min', pace: 'Technique focus',      description: '4× 50m catch-up drill · 4× 50m high-elbow pull · 4× 50m bilateral breathing', notes: '30 sec rest between each drill 50' },
            { name: 'Endurance',   type: 'mainSet', duration: '800m',   pace: 'Aerobic (Zone 2)',     description: 'Continuous freestyle at comfortable aerobic pace — RPE 5–6', notes: 'Focus on long strokes and hip rotation' },
            { name: 'Cool-Down',   type: 'cooldown', duration: '200m',  pace: 'Easy backstroke',     description: 'Easy backstroke or catch-up drill cool-down' },
          ],
        },
      },
      tue: {
        title: 'Cycle Power', badge: 'Triathlon', color: 'var(--accent-green)',
        desc: 'Cycling intervals — aerobic base + power development.', runs: '🚴 Cycle: 60min with power intervals',
        lifts: [],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Warm-Up',     type: 'warmup',  duration: '15 min', pace: 'Zone 1–2 (easy)',      description: 'Easy cadence cycling to warm up legs — 85–90 rpm target' },
            { name: 'Intervals',   type: 'mainSet', duration: '5×3 min', pace: 'Zone 4 (hard effort)', description: '3 min ON at high effort / 3 min easy between each', notes: 'Target cadence 90+ rpm during hard efforts. Stay seated.' },
            { name: 'Aerobic',     type: 'mainSet', duration: '15 min', pace: 'Zone 2 (steady)',       description: 'Steady aerobic cycling at comfortable effort' },
            { name: 'Cool-Down',   type: 'cooldown', duration: '5 min', pace: 'Zone 1 (very easy)',   description: 'Easy spin to flush the legs' },
          ],
        },
      },
      wed: {
        title: 'Strength + Core', badge: 'Support Session', color: 'var(--accent-amber)',
        desc: 'Gym strength session for injury prevention and power transfer.', runs: 'Rest',
        lifts: ['Back Squat', 'Romanian Deadlift', 'Standing OHP', 'Pull-Ups', 'Core/Plank'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Back Squat',        sets: 3, reps: '8–10', rpe: 7,   rest: '2.5 min', notes: 'Full depth — build the quad strength needed for cycling power' },
            { exercise: 'Romanian Deadlift', sets: 3, reps: '10–12', rpe: 7,  rest: '2 min' },
            { exercise: 'Standing OHP',      sets: 3, reps: '8–10', rpe: 6.5, rest: '90 sec' },
            { exercise: 'Pull-Ups',          sets: 3, reps: 'Max',  rpe: 7,   rest: '2 min', notes: 'Strong lats improve swim pull mechanics' },
            { exercise: 'Core/Plank',        sets: 4, reps: '45 sec', rpe: 7, rest: '30 sec', notes: 'Core stability is your power transfer in all three disciplines' },
          ],
        },
      },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day — your muscles and tendons need this.', runs: 'Rest', lifts: [] },
      fri: {
        title: 'Brick Session', badge: 'Key Workout', color: 'var(--accent-pink)',
        desc: 'Bike-to-run brick — the race day simulator. Do not skip.', runs: '🚴 45min cycle → 🏃 15min run (immediate transition)',
        lifts: [],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Cycle Warm-Up',  type: 'warmup',  duration: '10 min', pace: 'Zone 1–2',           description: 'Easy cycling to warm up — get into your rhythm' },
            { name: 'Cycle Main Set', type: 'mainSet', duration: '35 min', pace: 'Zone 3 (race effort)', description: 'Sustained race-pace cycling effort. Practice your tri position if using a road bike.' },
            { name: 'Transition',     type: 'mainSet', duration: '2 min',  pace: 'Fast',               description: 'Rapid transition to running kit. Practice removing helmet, racking bike, changing shoes.', notes: 'Faster transitions = free time on race day' },
            { name: 'Run Off Bike',   type: 'mainSet', duration: '15 min', pace: 'Zone 3–4',           description: 'Run immediately after cycling — expect heavy legs for first 2 minutes. Push through.', notes: 'This is what makes bricks essential. Your legs will adapt with practice.' },
          ],
        },
      },
      sat: {
        title: 'Long Run', badge: 'Endurance', color: 'var(--accent-green)',
        desc: 'Aerobic long run — building run base for race day.', runs: '🏃 45–60min Zone 2 run',
        lifts: [],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Warm-Up',   type: 'warmup',  duration: '5 min',    pace: 'Walk / Zone 1',       description: 'Brisk walk transitioning to easy jog' },
            { name: 'Long Run',  type: 'mainSet', duration: '45–60 min', pace: 'Zone 2 (conversational)', description: 'Continuous easy aerobic run — you must be able to hold a full conversation', notes: 'Week 1-4: 45 min. Week 5-7: 55 min. Reduce to 30 min Week 8 (taper)' },
            { name: 'Cool-Down', type: 'cooldown', duration: '5 min',   pace: 'Walk',                 description: 'Easy walk + full leg stretch — quads, hamstrings, calves, hip flexors' },
          ],
        },
      },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest day.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 8, intensityLabel: 'Foundation — establish all three aerobic bases' },
      '2': { sets: 3, reps: 8, intensityLabel: 'Build — increase duration 10% across disciplines' },
      '3': { sets: 4, reps: 8, intensityLabel: 'Build — add brick complexity + race pace work' },
      '4': { sets: 3, reps: 8, intensityLabel: 'Recovery week — reduce volume by 20%' },
      '5': { sets: 4, reps: 6, intensityLabel: 'Race specific — increase pace, reduce duration' },
      '6': { sets: 4, reps: 6, intensityLabel: 'Race simulation — practice full event sequence' },
      '7': { sets: 3, reps: 8, intensityLabel: 'Pre-race — taper volume begins' },
      '8': { sets: 2, reps: 8, intensityLabel: 'Race week — full taper. Trust your training.' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Sprint Triathlon', philosophy: 'Every brick session closes the gap between training and race day. The transition from bike to run separates those who trained it from those who did not.' },
  },
  // ── MOBILITY ──────────────────────────────────────────────────────────────────

  {
    id: 'athletic_mobility_foundation',
    name: 'Athletic Mobility Foundation',
    tagline: 'Move better. Lift more. Run faster. Recover quicker.',
    description: 'An 8-week mobility programme designed specifically for strength athletes and runners who want to move better. Combines deep tissue mobility work, active stretching, and movement patterning to eliminate restrictions, reduce injury risk, and improve performance in the gym and on the road.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    source: 'internal',
    category: 'mobility',
    subcategory: 'athletic-mobility',
    tags: ['mobility', 'flexibility', 'movement', 'recovery', 'injury-prevention', 'athletes', '8-week', 'daily'],
    durationWeeks: 8,
    sessionsPerWeek: 5,
    sessionDurationMinutes: { min: 20, max: 35 },
    difficulty: 'beginner',
    equipment: ['foam-roller', 'resistance-band'],
    equipmentTier: 'home',
    goals: ['mobility', 'injury-prevention', 'movement-quality', 'recovery'],
    metrics: { strengthEmphasis: 10, hypertrophyEmphasis: 5, enduranceEmphasis: 10, conditioningEmphasis: 5, recoveryDemand: 20, weeklyVolumeScore: 20 },
    highlights: ['20–35 min sessions', 'Complements any training', 'No gym required', 'Target hip, thoracic + shoulder mobility'],
    expectedOutcomes: ['Improved squat depth', 'Better shoulder mobility for pressing', 'Reduced lower back tension', 'Faster recovery between sessions'],
    popularity: 76, rating: 4.7, ratingCount: 567, completionRate: 0.72, enrolledCount: 3900,
    featured: false, verified: true, isNew: true,
    coverGradient: ['#0a1a0a', '#0d2e1a'], accentColor: '#86efac', icon: '🧘',
    collections: ['mobility-collection', 'beginner-friendly', 'new-programs', 'hybridhq-picks'],
    days: {
      mon: {
        title: 'Hip & Lower Body', badge: 'Mobility', color: 'var(--accent-green)',
        desc: 'Hip flexors, glutes, hamstrings, and ankle mobility.', runs: 'Rest',
        lifts: ['Core/Plank'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: '90/90 Hip Rotations',         sets: 3, reps: '10 each side',  rpe: 4, rest: '30 sec', notes: 'Sit in 90/90 position, rotate front leg back and vice versa. Feel the external/internal rotation.' },
            { exercise: 'Deep Squat Hold',              sets: 3, reps: '60 sec hold',   rpe: 3, rest: '30 sec', notes: 'Use a door frame or rack for support. Shift weight side to side.' },
            { exercise: 'Couch Stretch',                sets: 2, reps: '90 sec/side',   rpe: 4, rest: '30 sec', notes: 'Back knee on floor, front foot forward. Posterior hip capsule and quad.' },
            { exercise: 'Hamstring Elevated Stretch',   sets: 3, reps: '60 sec/side',   rpe: 4, rest: '30 sec', notes: 'Foot elevated on bench, hinge at hips keeping a long spine.' },
            { exercise: 'Ankle Circles + Dorsiflexion', sets: 2, reps: '20 each',       rpe: 2, rest: '15 sec', notes: 'Slow controlled circles, then drive knee over toe against a wall.' },
            { exercise: 'Glute Bridge Holds',           sets: 3, reps: '30 sec',        rpe: 4, rest: '30 sec', notes: 'Squeeze glutes hard at top. Anterior pelvic tilt correction.' },
          ],
        },
      },
      tue: {
        title: 'Thoracic Spine + Shoulders', badge: 'Mobility', color: 'var(--accent-blue)',
        desc: 'Upper back mobility, shoulder rotation, and overhead capacity.', runs: 'Rest',
        lifts: [],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Thoracic Extension over Roller', sets: 3, reps: '60 sec',      rpe: 3, rest: '30 sec', notes: 'Foam roller across upper back segments. Pause at stiff spots.' },
            { exercise: 'Cat-Cow Spinal Waves',           sets: 3, reps: '15 reps',     rpe: 2, rest: '15 sec', notes: 'Slow, controlled. Feel each segment of your spine move separately.' },
            { exercise: 'Open Book Rotations',            sets: 3, reps: '10 each',     rpe: 3, rest: '30 sec', notes: 'Side-lying. Stack knees, reach top arm across body following with eyes.' },
            { exercise: 'Shoulder Capsule Stretch',       sets: 2, reps: '90 sec/side', rpe: 4, rest: '30 sec', notes: 'Sleeper stretch — side lying, internally rotate arm with opposite hand.' },
            { exercise: 'Wall Shoulder Slides',           sets: 3, reps: '15 reps',     rpe: 3, rest: '30 sec', notes: 'Arms in W position on wall, slide up to overhead. Full contact with wall.' },
            { exercise: 'Band Pull-Apart',                sets: 4, reps: '20 reps',     rpe: 5, rest: '30 sec', notes: 'Activate the rear delts and external rotators. Do not shrug.' },
          ],
        },
      },
      wed: {
        title: 'Full Body Mobility Flow', badge: 'Mobility', color: 'var(--accent-amber)',
        desc: 'Connected full body movement sequence — floor to standing.', runs: 'Rest',
        lifts: [],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: "World's Greatest Stretch",  sets: 3, reps: '5 each side', rpe: 3, rest: '15 sec', notes: 'Lunge forward, elbow to floor, rotate and reach overhead. Slow and deliberate.' },
            { exercise: 'Thoracic Windmill',         sets: 3, reps: '8 each side', rpe: 3, rest: '30 sec', notes: 'Hands behind head, rotate upper body while lower stays still.' },
            { exercise: 'Lateral Lunge + Reach',     sets: 3, reps: '8 each side', rpe: 4, rest: '30 sec', notes: 'Wide lateral lunge, reach opposite arm to floor beside foot.' },
            { exercise: 'Turkish Get-Up (bodyweight)', sets: 3, reps: '3 each side', rpe: 4, rest: '60 sec', notes: 'Full movement — slow and intentional. Quality over speed.' },
            { exercise: 'Downward Dog Flow',         sets: 3, reps: '10 cycles',   rpe: 3, rest: '30 sec', notes: 'DD to Upward Dog to DD. Pedal heels and shift hips side to side.' },
          ],
        },
      },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest day.', runs: 'Rest', lifts: [] },
      fri: {
        title: 'Hips + Spine Reset', badge: 'Mobility', color: 'var(--accent-pink)',
        desc: 'Deep hip work and spinal decompression session.', runs: 'Rest',
        lifts: [],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Pigeon Pose',              sets: 2, reps: '2 min/side',  rpe: 4, rest: '30 sec', notes: 'Ground-based external hip rotation. Breathe into the restriction.' },
            { exercise: 'Hip Flexor Kneeling Lunge', sets: 3, reps: '90 sec/side', rpe: 4, rest: '30 sec', notes: 'Add a slight posterior tilt to increase the stretch at the front of the hip.' },
            { exercise: 'Spinal Twist',             sets: 2, reps: '90 sec/side', rpe: 3, rest: '30 sec', notes: 'Supine. Knee drops across body. Opposite shoulder stays flat.' },
            { exercise: 'Cossack Squat',            sets: 3, reps: '8 each side', rpe: 5, rest: '30 sec', notes: 'Lateral squat — keep foot flat on working side, opposite leg straight.' },
            { exercise: 'Prone Hip Extension',      sets: 3, reps: '15 each side', rpe: 4, rest: '30 sec', notes: 'Lying face down, lift one leg straight behind you. Squeeze glute at top.' },
          ],
        },
      },
      sat: {
        title: 'Active Recovery Flow', badge: 'Mobility', color: 'var(--accent-green)',
        desc: 'Gentle full body movement — the perfect post-training session.', runs: 'Optional 20min easy walk',
        lifts: [],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Foam Rolling',     type: 'warmup',  duration: '10 min', pace: 'Slow and deliberate',  description: 'Roll quads, hamstrings, calves, glutes, upper back. 60 sec per area minimum.' },
            { name: 'Gentle Stretching', type: 'mainSet', duration: '15 min', pace: 'No pain — discomfort is OK', description: 'Hold each stretch 60–90 seconds. Breathe through the tension.' },
            { name: 'Light Walking',    type: 'cooldown', duration: '20 min', pace: 'Easy (optional)',       description: 'Optional easy walk to promote blood flow and recovery' },
          ],
        },
      },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest day.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 2, reps: 60, intensityLabel: 'Introduction — learn the movements, mild tension only' },
      '2': { sets: 2, reps: 60, intensityLabel: 'Deepen the holds — push to mild discomfort' },
      '3': { sets: 3, reps: 60, intensityLabel: 'Build duration — 60 second holds throughout' },
      '4': { sets: 3, reps: 90, intensityLabel: 'Increase hold time — 90 seconds per position' },
      '5': { sets: 3, reps: 90, intensityLabel: 'Explore end range — move deeper into restriction' },
      '6': { sets: 3, reps: 90, intensityLabel: 'Active mobility — add light resistance' },
      '7': { sets: 4, reps: 90, intensityLabel: 'Loaded mobility — bodyweight loading at end range' },
      '8': { sets: 3, reps: 90, intensityLabel: 'Consolidation — test new ranges under control' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Athletic Mobility', philosophy: 'Mobility is not just stretching — it is building strength and control at your end ranges. Own the range you train.' },
  },
  // ── FUNCTIONAL FITNESS ────────────────────────────────────────────────────────

  {
    id: 'functional_gpp_12wk',
    name: 'GPP Foundation',
    tagline: 'General Physical Preparedness — be ready for anything',
    description: 'A 12-week General Physical Preparedness programme that builds a complete athletic base: strength, conditioning, aerobic capacity, and movement efficiency. Structured around functional compound movements, EMOMs, AMRAPs, and aerobic work. The ideal programme for athletes who want to be genuinely fit — not just gym-fit.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    source: 'internal',
    category: 'functional',
    subcategory: 'gpp',
    tags: ['functional', 'gpp', 'conditioning', 'strength', 'emom', 'amrap', '5-day', 'athletic', 'all-round'],
    durationWeeks: 12,
    sessionsPerWeek: 5,
    sessionDurationMinutes: { min: 45, max: 65 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'dumbbells', 'kettlebell', 'pull-up-bar', 'rowing-machine'],
    equipmentTier: 'gym',
    goals: ['general-fitness', 'conditioning', 'strength', 'work-capacity'],
    metrics: { strengthEmphasis: 55, hypertrophyEmphasis: 30, enduranceEmphasis: 65, conditioningEmphasis: 80, recoveryDemand: 65, weeklyVolumeScore: 70 },
    highlights: ['EMOM + AMRAP + strength sessions', 'Complete athletic development', 'Scales to any fitness level', '5 structured training days'],
    expectedOutcomes: ['Elite work capacity', 'Improved strength on main lifts', 'Excellent aerobic fitness', 'All-round physical capability'],
    popularity: 78, rating: 4.6, ratingCount: 389, completionRate: 0.55, enrolledCount: 2700,
    featured: false, verified: true, isNew: true,
    coverGradient: ['#1a0e10', '#2d1a10'], accentColor: '#fb923c', icon: '⚙️',
    collections: ['functional-collection', 'new-programs', 'hybridhq-picks'],
    days: {
      mon: {
        title: 'Strength + Conditioning', badge: 'GPP', color: 'var(--accent-blue)',
        desc: 'Compound strength work followed by a conditioning finisher.', runs: 'Rest',
        lifts: ['Back Squat', 'Bench Press', 'Barbell Row'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Back Squat',     sets: 4, reps: '5',        rpe: 8,   rest: '3 min', notes: 'Primary strength movement — heavy and focused' },
            { exercise: 'Bench Press',    sets: 4, reps: '5',        rpe: 8,   rest: '3 min' },
            { exercise: 'Barbell Row',    sets: 4, reps: '6–8',      rpe: 7.5, rest: '2.5 min' },
            { exercise: 'AMRAP Finisher', sets: 1, reps: '10 min',   rpe: 9,   rest: '—',    notes: 'AMRAP 10 min: 10 KB Swings + 10 Box Jumps + 10 Pull-Ups. Log rounds completed.' },
          ],
        },
      },
      tue: {
        title: 'Aerobic Engine', badge: 'GPP', color: 'var(--accent-green)',
        desc: 'Zone 2 aerobic capacity development.', runs: '🏃 35–45min Zone 2 run',
        lifts: [],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Warm-Up',   type: 'warmup',  duration: '5 min',    pace: 'Walk to easy jog',     description: 'Easy walk, then build to relaxed jog' },
            { name: 'Zone 2',    type: 'mainSet', duration: '35–45 min', pace: 'Zone 2 — conversational', description: 'Continuous easy aerobic run. You must be able to speak in full sentences.', notes: 'Increase by 5 min every 3 weeks. Reduce 10 min on deload weeks.' },
            { name: 'Cool-Down', type: 'cooldown', duration: '5 min',   pace: 'Walk',                 description: 'Easy walk + lower body stretch' },
          ],
        },
      },
      wed: {
        title: 'EMOM Strength', badge: 'GPP', color: 'var(--accent-amber)',
        desc: 'Every Minute On the Minute strength and skill work.', runs: 'Rest',
        lifts: ['Deadlift', 'Pull-Ups', 'Standing OHP'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Deadlift',   sets: 1, reps: '3 (EMOM ×10)',  rpe: 8, rest: 'EMOM', notes: 'EMOM 10 min — 3 deadlifts at 80% of 1RM. Quality reps, not speed reps.' },
            { exercise: 'Pull-Ups',   sets: 1, reps: '5 (EMOM ×8)',   rpe: 7, rest: 'EMOM', notes: 'EMOM 8 min — 5 strict pull-ups. Use band assistance if needed to maintain quality.' },
            { exercise: 'Standing OHP', sets: 1, reps: '5 (EMOM ×6)', rpe: 7, rest: 'EMOM', notes: 'EMOM 6 min — 5 overhead press. Lock out at top, full extension.' },
          ],
        },
      },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day — essential for adapting to the conditioning load.', runs: 'Rest', lifts: [] },
      fri: {
        title: 'AMRAP Challenge', badge: 'GPP', color: 'var(--accent-pink)',
        desc: 'As Many Rounds As Possible — maximum work capacity test.', runs: 'Rest',
        lifts: ['Back Squat', 'Standing OHP', 'Pull-Ups'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Strength Work',     sets: 3, reps: '5',     rpe: 7.5, rest: '2.5 min', notes: 'Back Squat + Standing OHP superset — not for max, saving energy for AMRAP' },
            { exercise: 'AMRAP 20 min',      sets: 1, reps: '20 min', rpe: 9,  rest: '—',       notes: '5 Pull-Ups + 10 Push-Ups + 15 Air Squats + 200m Row. Log total rounds + reps.' },
          ],
        },
      },
      sat: {
        title: 'Long Effort + Skill', badge: 'GPP', color: 'var(--accent-green)',
        desc: 'Longer aerobic effort plus movement skill practice.', runs: '🏃 45–60min Zone 2 or bike',
        lifts: [],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Aerobic Base',  type: 'mainSet', duration: '45–60 min', pace: 'Zone 2 (conversational)', description: 'Run, row, cycle, or ski erg — any aerobic modality you enjoy' },
            { name: 'Skill Work',    type: 'mainSet', duration: '15 min',    pace: 'Technique focus',          description: 'Double-unders, handstand holds, muscle-up progressions, or barbell cycling skill', notes: 'Choose one skill to develop — be deliberate, not exhausted' },
          ],
        },
      },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest day.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 5, intensityLabel: 'Foundation — learn the GPP structure' }, '2': { sets: 3, reps: 5, intensityLabel: 'Foundation — build work capacity' },
      '3': { sets: 4, reps: 5, intensityLabel: 'Build block — add volume' }, '4': { sets: 2, reps: 5, intensityLabel: 'Deload — reduce to 60%' },
      '5': { sets: 4, reps: 5, intensityLabel: 'Intensity block' }, '6': { sets: 4, reps: 4, intensityLabel: 'Intensity block — heavier' },
      '7': { sets: 5, reps: 4, intensityLabel: 'Peak volume' }, '8': { sets: 2, reps: 5, intensityLabel: 'Deload' },
      '9': { sets: 4, reps: 3, intensityLabel: 'Strength peak block' }, '10': { sets: 4, reps: 3, intensityLabel: 'Near max efforts' },
      '11': { sets: 4, reps: 3, intensityLabel: 'Final push' }, '12': { sets: 3, reps: 5, intensityLabel: 'Completion — test all benchmarks' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Functional Fitness', philosophy: 'GPP is about being prepared for everything. Strength without endurance has limits. Build the whole engine.' },
  },

];
