// @ts-check
// =============================================================================
// AUTO-GENERATED — split from catalog.js. Edit individual entries here.
// =============================================================================

export default [
  // ── HYBRID ────────────────────────────────────────────────────────────────

  {
    id: 'hybridhq_foundations',
    name: 'Helyx Foundations',
    tagline: 'The definitive starting point for hybrid athletes',
    description: 'A 12-week program designed specifically for athletes who want to build a serious base of strength, muscle, and aerobic capacity simultaneously. Progressive overload drives strength gains while structured running blocks develop your aerobic engine.',
    author: { name: 'Helyx', type: 'official', verified: true },
    category: 'hybrid',
    subcategory: 'strength-endurance',
    tags: ['hybrid', 'strength', 'running', 'concurrent', 'beginner-hybrid', 'barbell', 'zone2'],
    durationWeeks: 12,
    sessionsPerWeek: 5,
    sessionDurationMinutes: { min: 50, max: 70 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells'],
    equipmentTier: 'gym',
    goals: ['strength', 'fitness', 'running', 'general-health'],
    metrics: { strengthEmphasis: 70, hypertrophyEmphasis: 45, enduranceEmphasis: 55, conditioningEmphasis: 40, recoveryDemand: 60, weeklyVolumeScore: 65 },
    highlights: ['5-day/week structure', 'Concurrent strength + running', 'Progressive overload built-in', 'Deload weeks included'],
    expectedOutcomes: ['Improved 5K time', 'Strength gains on main lifts', 'Better body composition', 'Aerobic base development'],
    popularity: 95, rating: 4.8, ratingCount: 312, completionRate: 0.61, enrolledCount: 2840,
    featured: true, verified: true, isNew: false,
    coverGradient: ['#1a0e2e', '#2d1a5c'], accentColor: '#8b5cf6', icon: '⚡',
    collections: ['featured', 'hybridhq-picks', 'hybrid-collection', 'recommended-starters', 'most-popular'],
    days: {
      mon: {
        title: 'Strength A', badge: 'Push + Pull', color: 'var(--accent-blue)',
        desc: 'Full body strength focus. Bench, Row, Squat.', runs: 'Rest',
        lifts: ['Bench Press', 'Barbell Row', 'Back Squat', 'Lateral Raise', 'Hammer Curl'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Bench Press',   sets: 4, reps: '6–8',   rpe: 7,   rest: '3 min' },
            { exercise: 'Barbell Row',   sets: 4, reps: '6–8',   rpe: 7,   rest: '3 min' },
            { exercise: 'Back Squat',    sets: 3, reps: '8–10',  rpe: 6,   rest: '2.5 min' },
            { exercise: 'Lateral Raise', sets: 3, reps: '12–15', rpe: 7,   rest: '90 sec' },
            { exercise: 'Hammer Curl',   sets: 3, reps: '10–12', rpe: 7,   rest: '90 sec' },
          ],
        },
      },
      tue: {
        title: 'Intervals + Arms', badge: 'Run + Accessory', color: 'var(--accent-pink)',
        desc: 'Track intervals followed by arm work.', runs: '⚡ 6×800m (90s recovery)',
        lifts: ['Pull-Ups', 'Incline DB Press', 'Barbell Curl', 'Tricep Band Pushdown'],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Warm-Up',   type: 'warmup',   duration: '10 min',   pace: 'Zone 1–2 (easy)',         description: 'Easy jog + dynamic drills (leg swings, high knees)' },
            { name: 'Intervals', type: 'mainSet',  duration: '6 × 800m', pace: '5K race pace',            description: '90 sec recovery jog between each rep', notes: 'Stay relaxed on recovery; aim for even splits across all 6 reps' },
            { name: 'Arm Work',  type: 'strength', duration: '~20 min',  pace: '—',                       description: 'Pull-Ups 3×max · Incline DB Press 3×10 · Barbell Curl 3×12 · Tricep Pushdown 3×15' },
            { name: 'Cool-Down', type: 'cooldown', duration: '5 min',    pace: 'Zone 1 (very easy)',      description: 'Easy walk + calf & quad stretch' },
          ],
        },
      },
      wed: {
        title: 'Strength B', badge: 'Lower + Pull', color: 'var(--accent-green)',
        desc: 'Lower body focus. Deadlift, Romanian DL.', runs: 'Rest',
        lifts: ['Deadlift', 'Romanian Deadlift', 'Bulgarian Split Squat', 'Calf Raises', 'Face Pull'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Deadlift',              sets: 4, reps: '4–6',   rpe: 8,   rest: '4 min' },
            { exercise: 'Romanian Deadlift',     sets: 3, reps: '8–10',  rpe: 7,   rest: '2.5 min' },
            { exercise: 'Bulgarian Split Squat', sets: 3, reps: '8–10',  rpe: 7.5, rest: '2 min' },
            { exercise: 'Calf Raises',           sets: 4, reps: '15–20', rpe: 6,   rest: '60 sec' },
            { exercise: 'Face Pull',             sets: 3, reps: '15–20', rpe: 6,   rest: '60 sec' },
          ],
        },
      },
      thu: {
        title: 'Tempo Run', badge: 'Threshold', color: 'var(--accent-amber)',
        desc: 'Sustained effort at lactate threshold.', runs: '🔥 Tempo: 4×8 min @ threshold pace (2min rest)',
        lifts: [],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Warm-Up',   type: 'warmup',  duration: '12 min',    pace: 'Zone 1–2 (easy)',          description: 'Easy jog building gradually to a comfortable stride' },
            { name: 'Tempo',     type: 'mainSet', duration: '4 × 8 min', pace: 'Threshold (RPE 7–8)',      description: '2 min walking recovery between each rep', notes: '"Comfortably hard" — can speak short sentences but not hold a full conversation' },
            { name: 'Cool-Down', type: 'cooldown', duration: '8 min',    pace: 'Zone 1 (very easy)',       description: 'Easy jog + full leg stretch (quad, hamstring, calf)' },
          ],
        },
      },
      fri: {
        title: 'Strength C', badge: 'Upper Body', color: 'var(--accent-blue)',
        desc: 'OHP, chin-ups, accessories.', runs: 'Rest',
        lifts: ['Standing OHP', 'Chin-Ups', 'Seated DB Shoulder Press', 'Rear Delt Fly', 'Incline DB Curl'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Standing OHP',             sets: 4, reps: '5–6',   rpe: 8, rest: '3 min' },
            { exercise: 'Chin-Ups',                 sets: 4, reps: 'Max',   rpe: 8, rest: '2.5 min' },
            { exercise: 'Seated DB Shoulder Press', sets: 3, reps: '10–12', rpe: 7, rest: '90 sec' },
            { exercise: 'Rear Delt Fly',            sets: 3, reps: '15–20', rpe: 7, rest: '60 sec' },
            { exercise: 'Incline DB Curl',          sets: 3, reps: '10–12', rpe: 7, rest: '60 sec' },
          ],
        },
      },
      sat: {
        title: 'Long Run', badge: 'Zone 2', color: 'var(--accent-pink)',
        desc: 'Easy aerobic long run. Conversational pace.', runs: 'Zone 2 Long Run: 50-70 min',
        lifts: [],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Warm-Up',   type: 'warmup',  duration: '5 min',     pace: 'Walk / Zone 1',           description: 'Brisk walk + light dynamic warm-up' },
            { name: 'Long Run',  type: 'mainSet', duration: '50–70 min', pace: 'Zone 2 (conversational)', description: 'Continuous easy aerobic run — you should hold a full conversation', notes: 'Never push harder than RPE 5–6. Slow down on hills to keep HR in zone.' },
            { name: 'Cool-Down', type: 'cooldown', duration: '5–10 min', pace: 'Walk / Zone 1',           description: 'Easy walk + full body stretch' },
          ],
        },
      },
      sun: {
        title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)',
        desc: 'Full rest. Sleep, eat, recover.', runs: 'Rest', lifts: [],
      },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 8, intensityLabel: 'Foundation Block' }, '2': { sets: 3, reps: 8, intensityLabel: 'Foundation Block' },
      '3': { sets: 4, reps: 6, intensityLabel: 'Build Block' }, '4': { sets: 2, reps: 8, intensityLabel: 'Deload' },
      '5': { sets: 4, reps: 6, intensityLabel: 'Strength Block' }, '6': { sets: 4, reps: 5, intensityLabel: 'Strength Block' },
      '7': { sets: 4, reps: 5, intensityLabel: 'Strength Block' }, '8': { sets: 2, reps: 6, intensityLabel: 'Deload' },
      '9': { sets: 4, reps: 4, intensityLabel: 'Peak Block' }, '10': { sets: 4, reps: 4, intensityLabel: 'Peak Block' },
      '11': { sets: 4, reps: 3, intensityLabel: 'Peak Block' }, '12': { sets: 2, reps: 5, intensityLabel: 'Taper' },
    },
    dossier: { creator: 'Helyx', focus: 'Strength & Endurance', philosophy: 'Build strength and aerobic capacity concurrently using evidence-based concurrent training principles.' },
  },

  {
    id: 'hybrid_engine',
    name: 'Sub-20 5K Hybrid Engine',
    tagline: 'Break 20 minutes while building serious strength',
    description: 'A 9-week racing protocol that pushes your 5K pace below 20 minutes while maintaining maximal strength. Combines base accumulation, lactate threshold intervals, and heavy compound lifting.',
    author: { name: 'Helyx', type: 'official', verified: true },
    category: 'hybrid',
    subcategory: 'running-strength',
    tags: ['hybrid', '5k', 'running', 'strength', 'sub20', 'intervals', 'tempo', 'zone2'],
    durationWeeks: 9,
    sessionsPerWeek: 6,
    sessionDurationMinutes: { min: 50, max: 75 },
    difficulty: 'advanced',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells'],
    equipmentTier: 'gym',
    goals: ['5k-performance', 'strength', 'hybrid-fitness'],
    metrics: { strengthEmphasis: 75, hypertrophyEmphasis: 35, enduranceEmphasis: 80, conditioningEmphasis: 70, recoveryDemand: 85, weeklyVolumeScore: 80 },
    highlights: ['9-week racing protocol', 'Sub-20 5K focus', 'Heavy compound lifts', 'Interval + tempo structure'],
    expectedOutcomes: ['Sub-20 minute 5K', 'Improved lactate threshold', 'Maintained strength', 'Increased VO2max'],
    popularity: 88, rating: 4.7, ratingCount: 189, completionRate: 0.48, enrolledCount: 1620,
    featured: true, verified: true, isNew: false,
    coverGradient: ['#0d1b2a', '#1b4332'], accentColor: '#22d3ee', icon: '🏃',
    collections: ['featured', 'hybridhq-picks', 'hybrid-collection', 'running-collection', 'most-popular'],
  },

  {
    id: 'hybrid_strength_5k',
    name: 'Hybrid Strength & 5K Builder',
    tagline: 'Build muscle and run faster — no compromise',
    description: 'A 12-week strength-first hybrid program that builds real muscle while systematically improving your 5K performance. Prioritises compound strength movements with progressive overload across every training block.',
    author: { name: 'Helyx', type: 'official', verified: true },
    category: 'hybrid',
    subcategory: 'strength-running',
    tags: ['hybrid', 'strength', '5k', 'running', 'concurrent', 'muscle', 'push-pull-legs'],
    durationWeeks: 12,
    sessionsPerWeek: 6,
    sessionDurationMinutes: { min: 55, max: 80 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells'],
    equipmentTier: 'gym',
    goals: ['strength', 'running', 'muscle', 'hybrid-fitness'],
    metrics: { strengthEmphasis: 80, hypertrophyEmphasis: 55, enduranceEmphasis: 60, conditioningEmphasis: 45, recoveryDemand: 75, weeklyVolumeScore: 75 },
    highlights: ['Strength-first approach', 'PPL structure with running', 'Progressive overload emphasis', '12-week transformation'],
    expectedOutcomes: ['Significant strength gains', 'Faster 5K pace', 'Improved body composition', 'Better work capacity'],
    popularity: 82, rating: 4.6, ratingCount: 143, completionRate: 0.55, enrolledCount: 1240,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0e2e', '#0d3b2e'], accentColor: '#10b981', icon: '⚡',
    collections: ['hybrid-collection', 'hybridhq-picks', 'most-popular'],
  },

  {
    id: 'jacked_and_tan_2',
    name: 'GZCL: Jacked & Tan 2.0',
    tagline: 'Cody Lefever\'s legendary powerbuilding wave',
    description: 'A brutal 12-week powerbuilding program. Each week you hunt a new Rep Max before dropping into high-volume back-off sets. Three distinct waves build absolute strength and conditioning simultaneously.',
    author: { name: 'Cody Lefever (GZCL)', type: 'coach', verified: true },
    category: 'hybrid',
    subcategory: 'powerbuilding',
    tags: ['gzcl', 'powerbuilding', 'strength', 'hypertrophy', 'rep-max', 'advanced', 'barbell'],
    durationWeeks: 12,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 75, max: 105 },
    difficulty: 'advanced',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells'],
    equipmentTier: 'gym',
    goals: ['strength', 'powerbuilding', 'muscle'],
    metrics: { strengthEmphasis: 85, hypertrophyEmphasis: 65, enduranceEmphasis: 10, conditioningEmphasis: 20, recoveryDemand: 80, weeklyVolumeScore: 85 },
    highlights: ['Weekly Rep Max hunting', 'GZCL methodology', 'Strength + volume waves', 'Community favourite'],
    expectedOutcomes: ['New strength PRs', 'Significant muscle gain', 'Improved work capacity', 'Powerlifting total increase'],
    popularity: 91, rating: 4.8, ratingCount: 267, completionRate: 0.44, enrolledCount: 2100,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0a0a', '#3d1515'], accentColor: '#dc2626', icon: '🔱',
    collections: ['most-popular', 'highest-rated', 'hybrid-collection', 'strength-collection'],
  },

  {
    id: 'hyrox_foundations',
    name: 'Hyrox Foundations',
    tagline: 'Your first step toward Hyrox race day',
    description: 'A 12-week entry-level Hyrox preparation program. Builds the strength and conditioning base needed to complete a Hyrox race while developing familiarity with all 8 Hyrox stations.',
    author: { name: 'Helyx', type: 'official', verified: true },
    category: 'hyrox',
    subcategory: 'race-prep',
    tags: ['hyrox', 'hybrid', 'conditioning', 'strength', 'running', 'race-prep', 'beginner-hyrox'],
    durationWeeks: 12,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 50, max: 70 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'dumbbells', 'sled', 'ski-erg', 'rowing-machine', 'kettlebell'],
    equipmentTier: 'gym',
    goals: ['hyrox', 'race-completion', 'conditioning', 'strength'],
    metrics: { strengthEmphasis: 55, hypertrophyEmphasis: 25, enduranceEmphasis: 65, conditioningEmphasis: 80, recoveryDemand: 65, weeklyVolumeScore: 60 },
    highlights: ['All 8 Hyrox stations covered', 'Race-specific conditioning', 'Strength foundation', 'Beginner-friendly structure'],
    expectedOutcomes: ['Hyrox race completion', 'Improved work capacity', 'Functional strength', 'Conditioning base'],
    popularity: 87, rating: 4.7, ratingCount: 198, completionRate: 0.58, enrolledCount: 1890,
    featured: true, verified: true, isNew: false,
    coverGradient: ['#1a0e2e', '#2d1b69'], accentColor: '#7c3aed', icon: '🏟️',
    collections: ['featured', 'hyrox-collection', 'hybridhq-picks', 'most-popular'],
    days: {
      mon: { title: 'Strength A', badge: 'Lower Body', color: 'var(--accent-green)', desc: 'Squat, lunges, sled push prep.', runs: 'Rest', lifts: ['Back Squat', 'Romanian Deadlift', 'Bulgarian Split Squat', 'Calf Raises', 'Core/Plank'] },
      tue: { title: 'Conditioning A', badge: 'Hyrox Sim', color: 'var(--accent-amber)', desc: 'Hyrox station simulation + run.', runs: '🏃 Run 1km @ race pace + Ski Erg 500m + Row 500m', lifts: ['Deadlift'] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest or light mobility.', runs: 'Rest', lifts: [] },
      thu: { title: 'Strength B', badge: 'Upper Body', color: 'var(--accent-blue)', desc: 'Push, pull, core — functional strength.', runs: 'Rest', lifts: ['Bench Press', 'Pull-Ups', 'Standing OHP', 'Barbell Row', 'Hanging Leg Raises'] },
      fri: { title: 'Conditioning B', badge: 'Threshold', color: 'var(--accent-pink)', desc: 'Threshold running + burpee broad jumps.', runs: '🔥 3×1200m threshold + 3×10 burpee broad jumps', lifts: [] },
      sat: { title: 'Long + Stations', badge: 'Race Simulation', color: 'var(--accent-amber)', desc: 'Long run + multi-station simulation.', runs: '🏃 45-60min run + Farmer Carry + Wall Balls', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 10, intensityLabel: 'Base Phase' }, '2': { sets: 3, reps: 10, intensityLabel: 'Base Phase' },
      '3': { sets: 4, reps: 8, intensityLabel: 'Build Phase' }, '4': { sets: 2, reps: 10, intensityLabel: 'Deload' },
      '5': { sets: 4, reps: 8, intensityLabel: 'Conditioning Block' }, '6': { sets: 4, reps: 6, intensityLabel: 'Conditioning Block' },
      '7': { sets: 4, reps: 6, intensityLabel: 'Conditioning Block' }, '8': { sets: 2, reps: 8, intensityLabel: 'Deload' },
      '9': { sets: 4, reps: 5, intensityLabel: 'Race Prep Block' }, '10': { sets: 4, reps: 5, intensityLabel: 'Race Prep Block' },
      '11': { sets: 3, reps: 5, intensityLabel: 'Taper' }, '12': { sets: 2, reps: 5, intensityLabel: 'Race Week Taper' },
    },
    dossier: { creator: 'Helyx', focus: 'Hyrox Race Preparation', philosophy: 'Systematic preparation for Hyrox through concurrent strength and conditioning development.' },
  },

  {
    id: 'hyrox_intermediate',
    name: 'Hyrox Intermediate Prep',
    tagline: 'Chase your Hyrox PB with structured periodisation',
    description: 'A 16-week intermediate Hyrox program for athletes who have completed a race and want to significantly improve their time. Features race-specific conditioning blocks, strength cycles, and a structured taper.',
    author: { name: 'Helyx', type: 'official', verified: true },
    category: 'hyrox',
    subcategory: 'race-prep',
    tags: ['hyrox', 'pb', 'race-prep', 'intermediate', 'conditioning', 'strength', 'intervals'],
    durationWeeks: 16,
    sessionsPerWeek: 5,
    sessionDurationMinutes: { min: 55, max: 80 },
    difficulty: 'advanced',
    equipment: ['barbell', 'dumbbells', 'sled', 'ski-erg', 'rowing-machine', 'kettlebell', 'sandbag'],
    equipmentTier: 'gym',
    goals: ['hyrox-pb', 'race-performance', 'conditioning'],
    metrics: { strengthEmphasis: 60, hypertrophyEmphasis: 20, enduranceEmphasis: 70, conditioningEmphasis: 90, recoveryDemand: 80, weeklyVolumeScore: 75 },
    highlights: ['16-week periodised plan', 'Race-simulation sessions', 'Strength + speed combination', 'Progressive taper'],
    expectedOutcomes: ['Hyrox PB', 'Improved race station times', 'Better running economy', 'Enhanced work capacity'],
    popularity: 79, rating: 4.6, ratingCount: 134, completionRate: 0.51, enrolledCount: 1120,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0e2e', '#2d1b69'], accentColor: '#a78bfa', icon: '🏟️',
    collections: ['hyrox-collection', 'hybridhq-picks'],
    days: {
      mon: { title: 'Strength Lower', badge: 'Leg Power', color: 'var(--accent-green)', desc: 'Sled prep, squat, lunges.', runs: 'Rest', lifts: ['Back Squat', 'Romanian Deadlift', 'Bulgarian Split Squat', 'Leg Press', 'Calf Raises'] },
      tue: { title: 'Conditioning + Run', badge: 'Race Sim', color: 'var(--accent-amber)', desc: 'Station sim + intervals.', runs: '⚡ 4×1km @ race pace + 4 Hyrox stations', lifts: ['Deadlift'] },
      wed: { title: 'Strength Upper', badge: 'Upper Power', color: 'var(--accent-blue)', desc: 'Pushing + pulling strength.', runs: 'Rest', lifts: ['Bench Press', 'Pull-Ups', 'Standing OHP', 'Barbell Row', 'Core/Plank'] },
      thu: { title: 'Threshold Run', badge: 'Tempo', color: 'var(--accent-pink)', desc: 'Sustained threshold effort.', runs: '🔥 2×20min threshold run (3min rest)', lifts: [] },
      fri: { title: 'Full Race Simulation', badge: 'Race Prep', color: 'var(--accent-amber)', desc: 'Race-distance sim with all stations.', runs: '🏟️ Full Hyrox simulation', lifts: [] },
      sat: { title: 'Long Zone 2', badge: 'Aerobic Base', color: 'var(--accent-pink)', desc: 'Easy long run for aerobic development.', runs: 'Zone 2: 60-90min easy', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 10, intensityLabel: 'Base' }, '2': { sets: 4, reps: 8, intensityLabel: 'Base' },
      '3': { sets: 4, reps: 8, intensityLabel: 'Build' }, '4': { sets: 2, reps: 10, intensityLabel: 'Deload' },
      '5': { sets: 4, reps: 6, intensityLabel: 'Strength Block' }, '6': { sets: 4, reps: 6, intensityLabel: 'Strength Block' },
      '7': { sets: 5, reps: 5, intensityLabel: 'Strength Block' }, '8': { sets: 2, reps: 8, intensityLabel: 'Deload' },
      '9': { sets: 4, reps: 5, intensityLabel: 'Race Conditioning' }, '10': { sets: 4, reps: 5, intensityLabel: 'Race Conditioning' },
      '11': { sets: 4, reps: 4, intensityLabel: 'Peak Block' }, '12': { sets: 4, reps: 4, intensityLabel: 'Peak Block' },
      '13': { sets: 3, reps: 5, intensityLabel: 'Taper Start' }, '14': { sets: 3, reps: 5, intensityLabel: 'Taper' },
      '15': { sets: 2, reps: 6, intensityLabel: 'Taper' }, '16': { sets: 1, reps: 5, intensityLabel: 'Race Week' },
    },
    dossier: { creator: 'Helyx', focus: 'Hyrox Performance', philosophy: 'Periodised 16-week preparation designed to significantly improve Hyrox race time through concurrent strength and conditioning.' },
  },
  // ── HYBRID — ADDITIONAL ────────────────────────────────────────────────────

  {
    id: 'hybrid_athlete_12w',
    name: 'Hybrid Athlete 12-Week',
    tagline: 'Run fast. Lift heavy. Do both at once.',
    description: 'Inspired by the Nick Bare methodology, this 12-week concurrent training program builds serious aerobic capacity alongside genuine strength. Four lifting days and three running days per week, structured so the two qualities coexist and reinforce each other rather than compete.',
    author: { name: 'Helyx', type: 'official', verified: true },
    category: 'hybrid',
    subcategory: 'concurrent-training',
    tags: ['hybrid', 'concurrent', 'strength', 'running', 'endurance', 'nick-bare', '5-day', 'advanced', 'lifestyle'],
    durationWeeks: 12,
    sessionsPerWeek: 5,
    sessionDurationMinutes: { min: 60, max: 90 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'dumbbells', 'rack', 'bench', 'running-shoes'],
    equipmentTier: 'gym',
    goals: ['hybrid-fitness', 'strength', 'running', 'endurance', 'body-composition'],
    metrics: { strengthEmphasis: 75, hypertrophyEmphasis: 60, enduranceEmphasis: 80, conditioningEmphasis: 65, recoveryDemand: 75, weeklyVolumeScore: 80 },
    highlights: ['True concurrent training', 'Nick Bare methodology', '5 days/week', 'Strength + running progress simultaneously'],
    expectedOutcomes: ['Hybrid athlete identity', 'Sub-45min 10K + 300lb deadlift', 'Body composition improvement', 'Running and lifting PRs'],
    popularity: 88, rating: 4.8, ratingCount: 1560, completionRate: 0.59, enrolledCount: 9200,
    featured: true, verified: true, isNew: false,
    coverGradient: ['#0d1a2e', '#1a0d2e'], accentColor: '#8b5cf6', icon: '⚡',
    collections: ['hybridhq-picks', 'hybrid-collection', 'most-popular', 'highest-rated'],
    days: {
      mon: { title: 'Lower Strength + Run', badge: 'Hybrid', color: 'var(--accent-purple)', desc: 'Heavy leg day + afternoon easy run.', runs: '🏃 PM: 5km easy run', lifts: ['Back Squat 5×5', 'Romanian Deadlift 3×8', 'Bulgarian Split Squat 3×10', 'Leg Press 3×12'] },
      tue: { title: 'Upper Strength', badge: 'Hybrid', color: 'var(--accent-blue)', desc: 'Chest + back + shoulders.', runs: 'Rest', lifts: ['Bench Press 4×8', 'Barbell Row 4×8', 'Standing OHP 3×8', 'Pull-Ups 3×10', 'Face Pulls 3×15'] },
      wed: { title: 'Long Run', badge: 'Running', color: 'var(--accent-green)', desc: 'Aerobic base run.', runs: '🏃 Long run (8-14km, Zone 2)', lifts: [] },
      thu: { title: 'Lower Strength', badge: 'Hybrid', color: 'var(--accent-amber)', desc: 'Deadlift focus.', runs: 'Rest', lifts: ['Deadlift 5×5', 'Front Squat 3×6', 'Good Mornings 3×10', 'Hamstring Curl 3×12'] },
      fri: { title: 'Upper Strength + Run', badge: 'Hybrid', color: 'var(--accent-pink)', desc: 'Upper body + PM tempo run.', runs: '🏃 PM: 5km @ threshold pace', lifts: ['Incline Bench Press 4×8', 'Cable Row 4×10', 'Arnold Press 3×10', 'Tricep Extension 3×12'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest or light walk.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 8, intensityLabel: 'Adaptation block — establish all baselines' },
      '2': { sets: 3, reps: 8, intensityLabel: 'Adaptation block' },
      '3': { sets: 4, reps: 8, intensityLabel: 'Volume build' },
      '4': { sets: 2, reps: 6, intensityLabel: 'Deload' },
      '5': { sets: 4, reps: 6, intensityLabel: 'Strength block begins' },
      '6': { sets: 4, reps: 6, intensityLabel: 'Strength block' },
      '7': { sets: 5, reps: 5, intensityLabel: 'Heavy strength + running consistency' },
      '8': { sets: 2, reps: 5, intensityLabel: 'Deload' },
      '9': { sets: 5, reps: 4, intensityLabel: 'Peak strength' },
      '10': { sets: 5, reps: 4, intensityLabel: 'Peak strength + long run peak' },
      '11': { sets: 4, reps: 5, intensityLabel: 'Hold strength, taper running' },
      '12': { sets: 2, reps: 5, intensityLabel: 'Test week — new 1RM + run time trial' },
    },
    dossier: { creator: 'Helyx', focus: 'Concurrent Hybrid Training', philosophy: 'The hybrid athlete exists in the space where iron discipline meets aerobic freedom. Train strength and endurance not as opposites but as complements.' },
  },

  {
    id: 'aerobic_capacity_builder',
    name: 'Aerobic Capacity Builder',
    tagline: 'Build an unstoppable aerobic engine in 8 weeks',
    description: 'An 8-week program dedicated to developing aerobic capacity from the ground up. Primarily Zone 2 work with strategic Zone 4 intervals to develop VO2 max. Designed to complement any strength program or serve as a standalone base-building phase before race season.',
    author: { name: 'Helyx', type: 'official', verified: true },
    category: 'hybrid',
    subcategory: 'aerobic-development',
    tags: ['aerobic', 'cardio', 'zone2', 'vo2max', 'endurance', 'base-building', 'running', 'conditioning'],
    durationWeeks: 8,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 40, max: 90 },
    difficulty: 'intermediate',
    equipment: ['running-shoes'],
    equipmentTier: 'minimal',
    goals: ['aerobic-base', 'vo2max', 'endurance', 'running-economy'],
    metrics: { strengthEmphasis: 10, hypertrophyEmphasis: 5, enduranceEmphasis: 98, conditioningEmphasis: 70, recoveryDemand: 50, weeklyVolumeScore: 55 },
    highlights: ['Zone 2 foundations', 'VO2 max interval sessions', 'Structured aerobic periodization', 'Complements any strength program'],
    expectedOutcomes: ['Dramatically improved aerobic base', 'Lower resting heart rate', 'Better recovery between sessions', 'Faster running at same effort'],
    popularity: 74, rating: 4.6, ratingCount: 380, completionRate: 0.71, enrolledCount: 2800,
    featured: false, verified: true, isNew: true,
    coverGradient: ['#001a1a', '#003333'], accentColor: '#22d3ee', icon: '🫀',
    collections: ['hybrid-collection', 'endurance-collection', 'new-programs'],
    days: {
      mon: { title: 'Zone 2 Run', badge: 'Aerobic', color: 'var(--accent-blue)', desc: 'Low-intensity steady state. Should be conversational.', runs: '🏃 45-60min Zone 2 run', lifts: [] },
      tue: { title: 'VO2 Max Intervals', badge: 'Intensity', color: 'var(--accent-pink)', desc: 'Hard intervals for top-end aerobic development.', runs: '🔥 5×3min hard + 3min rest + 10min warm/cool', lifts: [] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest. The adaptations happen here.', runs: 'Rest', lifts: [] },
      thu: { title: 'Zone 2 Run', badge: 'Aerobic', color: 'var(--accent-green)', desc: 'Longer aerobic session.', runs: '🏃 60-80min Zone 2 run', lifts: [] },
      fri: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sat: { title: 'Long Easy Run', badge: 'Aerobic', color: 'var(--accent-blue)', desc: 'Weekly long run at easy pace.', runs: '🏃 Long run (70-90min easy)', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 1, reps: 1, intensityLabel: 'Week 1: Zone 2 only — build the base slowly' },
      '2': { sets: 1, reps: 1, intensityLabel: 'Week 2: Introduce first interval session' },
      '3': { sets: 1, reps: 1, intensityLabel: 'Week 3: Extend Zone 2 duration +10%' },
      '4': { sets: 1, reps: 1, intensityLabel: 'Deload — cut volume 30%' },
      '5': { sets: 1, reps: 1, intensityLabel: 'Week 5: Higher interval volume' },
      '6': { sets: 1, reps: 1, intensityLabel: 'Week 6: Peak Zone 2 volume + intervals' },
      '7': { sets: 1, reps: 1, intensityLabel: 'Week 7: Peak total volume' },
      '8': { sets: 1, reps: 1, intensityLabel: 'Week 8: Taper + assess gains' },
    },
    dossier: { creator: 'Helyx', focus: 'Aerobic Base Development', philosophy: 'Without an aerobic base, every other quality rests on sand. Build the engine first.' },
  },

];
