// @ts-check
// =============================================================================
// AUTO-GENERATED — split from catalog.js. Edit individual entries here.
// =============================================================================

export default [
  // ── HYPERTROPHY ───────────────────────────────────────────────────────────

  {
    id: 'ppl_hypertrophy',
    name: 'Push Pull Legs (Hypertrophy)',
    tagline: 'The gold standard 6-day muscle building split',
    description: 'The classic PPL split that built a million physiques. Six training days targeting each muscle group twice per week through mechanical tension and metabolic stress. The ideal program for maximizing muscle protein synthesis.',
    author: { name: 'Classic Blueprint', type: 'community', verified: true },
    category: 'hypertrophy',
    subcategory: 'ppl',
    tags: ['ppl', 'push-pull-legs', 'hypertrophy', 'muscle', '6-day', 'bodybuilding', 'intermediate'],
    durationWeeks: 8,
    sessionsPerWeek: 6,
    sessionDurationMinutes: { min: 50, max: 70 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells', 'cables'],
    equipmentTier: 'gym',
    goals: ['muscle-gain', 'hypertrophy', 'body-composition'],
    metrics: { strengthEmphasis: 40, hypertrophyEmphasis: 92, enduranceEmphasis: 5, conditioningEmphasis: 5, recoveryDemand: 65, weeklyVolumeScore: 90 },
    highlights: ['6-day split', 'Each muscle 2× per week', 'Progression built-in', 'Classic hypertrophy protocol'],
    expectedOutcomes: ['Significant muscle gain', 'Improved symmetry', 'Strength increases', 'Better body composition'],
    popularity: 93, rating: 4.7, ratingCount: 1456, completionRate: 0.46, enrolledCount: 7800,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a1628', '#1e3a5f'], accentColor: '#3b82f6', icon: '💪',
    collections: ['hypertrophy-collection', 'most-popular'],
  },

  {
    id: 'reddit_ppl',
    name: 'Reddit PPL (6-Day)',
    tagline: 'Community-built, battle-tested muscle building',
    description: 'One of the most battle-tested routines on the internet. Alternates between heavy, low-rep compound days and high-volume hypertrophy days to build a dense, aesthetic physique. Community-refined over years.',
    author: { name: 'Reddit Fitness Community', type: 'community', verified: false },
    category: 'hypertrophy',
    subcategory: 'ppl',
    tags: ['reddit', 'ppl', 'hypertrophy', 'strength', '6-day', 'community', 'barbell', 'intermediate'],
    durationWeeks: 12,
    sessionsPerWeek: 6,
    sessionDurationMinutes: { min: 55, max: 75 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells', 'cables'],
    equipmentTier: 'gym',
    goals: ['muscle-gain', 'strength', 'aesthetics'],
    metrics: { strengthEmphasis: 55, hypertrophyEmphasis: 88, enduranceEmphasis: 5, conditioningEmphasis: 5, recoveryDemand: 70, weeklyVolumeScore: 85 },
    highlights: ['Heavy + volume day alternation', 'Community favourite', '12-week cycle', 'Proven results'],
    expectedOutcomes: ['Strength and size gains', 'Aesthetic physique', 'Improved compound lifts', 'Work capacity'],
    popularity: 94, rating: 4.6, ratingCount: 2340, completionRate: 0.40, enrolledCount: 9200,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a1628', '#1e3a5f'], accentColor: '#6366f1', icon: '💪',
    collections: ['hypertrophy-collection', 'most-popular', 'community-favourites'],
  },

  {
    id: 'kong_savage_size',
    name: 'KONG: Savage Size',
    tagline: 'Alex Bromley\'s brutal 12-week size protocol',
    description: 'Three distinct phases. A 4-week Volumizing block, a Pyramids block, and finally heavy Reverse Pyramids. Eat big to survive this. Alex Bromley\'s most popular hypertrophy program produces exceptional size gains.',
    author: { name: 'Alex Bromley', type: 'coach', verified: true },
    category: 'hypertrophy',
    subcategory: 'bodybuilding',
    tags: ['kong', 'alex-bromley', 'hypertrophy', 'size', 'bodybuilding', 'advanced', 'phases'],
    durationWeeks: 12,
    sessionsPerWeek: 5,
    sessionDurationMinutes: { min: 65, max: 85 },
    difficulty: 'advanced',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells', 'cables'],
    equipmentTier: 'gym',
    goals: ['muscle-gain', 'hypertrophy', 'size'],
    metrics: { strengthEmphasis: 60, hypertrophyEmphasis: 95, enduranceEmphasis: 5, conditioningEmphasis: 5, recoveryDemand: 75, weeklyVolumeScore: 92 },
    highlights: ['3-phase progression', 'Reverse pyramid technique', 'Alex Bromley methodology', 'Maximum size focus'],
    expectedOutcomes: ['Exceptional muscle gain', 'Improved symmetry', 'Strength foundation', 'Stage-ready physique'],
    popularity: 86, rating: 4.8, ratingCount: 456, completionRate: 0.47, enrolledCount: 3200,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a1628', '#0f3460'], accentColor: '#8b5cf6', icon: '💪',
    collections: ['hypertrophy-collection', 'highest-rated', 'most-popular'],
  },

  {
    id: 'phul',
    name: 'PHUL — Power Hypertrophy Upper Lower',
    tagline: 'Four days of power and hypertrophy combined',
    description: 'Power Hypertrophy Upper Lower. Four training days covering both power (heavy, low rep) and hypertrophy (moderate rep) work. The gold standard 4-day split for athletes who want strength and size simultaneously.',
    author: { name: 'Brandon Campbell', type: 'coach', verified: true },
    category: 'hypertrophy',
    subcategory: 'upper-lower',
    tags: ['phul', 'power', 'hypertrophy', 'upper-lower', '4-day', 'strength', 'intermediate', 'barbell'],
    durationWeeks: 12,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 60, max: 80 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells', 'cables'],
    equipmentTier: 'gym',
    goals: ['muscle-gain', 'strength', 'powerbuilding'],
    metrics: { strengthEmphasis: 70, hypertrophyEmphasis: 80, enduranceEmphasis: 5, conditioningEmphasis: 10, recoveryDemand: 60, weeklyVolumeScore: 75 },
    highlights: ['Power + hypertrophy days', '4-day schedule', 'Upper/lower split', 'Strength + size'],
    expectedOutcomes: ['Strength and size gains', 'Well-balanced physique', 'Improved main lifts', 'Functional muscle mass'],
    popularity: 88, rating: 4.6, ratingCount: 789, completionRate: 0.52, enrolledCount: 5100,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a1628', '#1e3a5f'], accentColor: '#3b82f6', icon: '💪',
    collections: ['hypertrophy-collection', 'strength-collection', 'most-popular'],
    days: {
      mon: { title: 'Upper Power', badge: 'PHUL', color: 'var(--accent-blue)', desc: 'Heavy compounds. Bench + Row. 3-5 rep ranges.', runs: 'Rest', lifts: ['Bench Press', 'Barbell Row', 'Incline Bench Press', 'Lat Pulldown', 'Barbell Curl', 'Tricep Band Pushdown'] },
      tue: { title: 'Lower Power', badge: 'PHUL', color: 'var(--accent-green)', desc: 'Heavy squat + deadlift. Low rep power work.', runs: 'Rest', lifts: ['Back Squat', 'Deadlift', 'Leg Press', 'Calf Raises'] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: { title: 'Upper Hypertrophy', badge: 'PHUL', color: 'var(--accent-blue)', desc: 'Volume upper work. 8-12 rep ranges.', runs: 'Rest', lifts: ['Incline DB Press', 'Seated DB Shoulder Press', 'Chest Supported Row', 'Lateral Raise', 'Incline DB Curl', 'Lying DB Tricep Extension'] },
      fri: { title: 'Lower Hypertrophy', badge: 'PHUL', color: 'var(--accent-green)', desc: 'Volume lower work. 8-12 rep ranges.', runs: 'Rest', lifts: ['Back Squat', 'Romanian Deadlift', 'Bulgarian Split Squat', 'Hamstring Curl', 'Calf Raises'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 8, intensityLabel: 'Power Days: 3-5 reps | Hypertrophy Days: 8-12 reps' },
      '2': { sets: 4, reps: 8, intensityLabel: 'Power Days: 3-5 reps | Hypertrophy Days: 8-12 reps' },
      '3': { sets: 4, reps: 6, intensityLabel: 'Power Days: 3-5 reps | Hypertrophy Days: 8-12 reps' },
      '4': { sets: 2, reps: 10, intensityLabel: 'Deload week' },
      '5': { sets: 4, reps: 6, intensityLabel: 'Increasing intensity' },
      '6': { sets: 4, reps: 5, intensityLabel: 'Increasing intensity' },
      '7': { sets: 4, reps: 5, intensityLabel: 'Heavy block' },
      '8': { sets: 2, reps: 8, intensityLabel: 'Deload' },
      '9': { sets: 5, reps: 5, intensityLabel: 'Peak block' },
      '10': { sets: 5, reps: 4, intensityLabel: 'Peak block' },
      '11': { sets: 4, reps: 4, intensityLabel: 'Peak block' },
      '12': { sets: 3, reps: 3, intensityLabel: 'Final peak' },
    },
    dossier: { creator: 'Brandon Campbell', focus: 'Power & Hypertrophy', philosophy: 'Four days combining power training for strength and hypertrophy training for size.' },
  },
  // ── HYPERTROPHY — ADDITIONAL ──────────────────────────────────────────────

  {
    id: 'german_volume_training',
    name: 'German Volume Training',
    tagline: '10 sets of 10 — the most brutal hypertrophy method alive',
    description: 'German Volume Training (GVT) is one of the most effective — and demanding — muscle-building approaches ever devised. 10 sets of 10 reps on a single compound movement per session. Minimal rest. Maximum metabolic stress. Not for the faint of heart.',
    author: { name: 'Charles Poliquin', type: 'coach', verified: true },
    category: 'hypertrophy',
    subcategory: 'classic-bodybuilding',
    tags: ['hypertrophy', 'gvt', 'volume', '10x10', 'bodybuilding', 'advanced', 'muscle', 'intensity'],
    durationWeeks: 6,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 50, max: 75 },
    difficulty: 'advanced',
    equipment: ['barbell', 'dumbbells', 'rack', 'bench', 'cables'],
    equipmentTier: 'full-gym',
    goals: ['hypertrophy', 'muscle-mass', 'volume-adaptation'],
    metrics: { strengthEmphasis: 35, hypertrophyEmphasis: 98, enduranceEmphasis: 15, conditioningEmphasis: 25, recoveryDemand: 90, weeklyVolumeScore: 90 },
    highlights: ['10×10 on main lift', 'Extreme metabolic stress', 'Rapid hypertrophy', 'Minimal accessory work needed'],
    expectedOutcomes: ['Significant muscle gain', 'Mental toughness', 'Volume tolerance', 'Physique transformation'],
    popularity: 72, rating: 4.4, ratingCount: 640, completionRate: 0.48, enrolledCount: 3100,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0520', '#2d0a35'], accentColor: '#a855f7', icon: '💥',
    collections: ['hypertrophy-collection', 'community-favourites'],
    days: {
      mon: { title: 'Chest + Back', badge: 'GVT', color: 'var(--accent-purple)', desc: '10×10 Bench and Row.', runs: 'Rest', lifts: ['Bench Press 10×10', 'Barbell Row 10×10', 'Lateral Raise 3×10-12', 'Cable Curl 3×10-12'] },
      tue: { title: 'Legs + Abs', badge: 'GVT', color: 'var(--accent-pink)', desc: '10×10 Squat and Hamstring.', runs: 'Rest', lifts: ['Back Squat 10×10', 'Hamstring Curl 10×10', 'Calf Raise 3×15', 'Ab Work 3×20'] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest essential.', runs: 'Rest', lifts: [] },
      thu: { title: 'Arms + Shoulders', badge: 'GVT', color: 'var(--accent-amber)', desc: '10×10 Dips and Chin-Ups.', runs: 'Rest', lifts: ['Dips 10×10', 'Chin-Ups 10×10', 'Lateral Raise 3×12', 'Face Pulls 3×15'] },
      fri: { title: 'Deadlift + Pull', badge: 'GVT', color: 'var(--accent-blue)', desc: '10×10 Deadlift.', runs: 'Rest', lifts: ['Romanian Deadlift 10×10', 'Pull-Ups 3×10', 'Shrugs 3×12', 'Cable Row 3×12'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 10, reps: 10, intensityLabel: '60% 1RM — Form check, survive the volume' },
      '2': { sets: 10, reps: 10, intensityLabel: '62% 1RM — Add small weight if all 10×10' },
      '3': { sets: 10, reps: 10, intensityLabel: '65% 1RM — Push the pace' },
      '4': { sets: 10, reps: 10, intensityLabel: '67% 1RM — Mental toughness week' },
      '5': { sets: 10, reps: 10, intensityLabel: '70% 1RM — Peak volume' },
      '6': { sets: 5, reps: 10, intensityLabel: 'Back-off — consolidate gains' },
    },
    dossier: { creator: 'Charles Poliquin', focus: 'Hypertrophy via Volume', philosophy: 'The body adapts to a novel stimulus. 10 sets of 10 with a compound lift provides a metabolic and mechanical stress unlike any other method.' },
  },

  {
    id: 'bodybuilding_5day',
    name: '5-Day Bodybuilding Split',
    tagline: 'Classic bro split reimagined for modern science',
    description: 'A 5-day body-part split that brings the best of classic bodybuilding together with modern evidence-based principles. Each muscle group gets dedicated volume once per week but with enough intensity techniques — drop sets, supersets, forced reps — to maximise growth stimulus.',
    author: { name: 'Helyx', type: 'official', verified: true },
    category: 'hypertrophy',
    subcategory: 'split-training',
    tags: ['bodybuilding', '5-day', 'bro-split', 'hypertrophy', 'muscle', 'advanced', 'physique', 'volume'],
    durationWeeks: 12,
    sessionsPerWeek: 5,
    sessionDurationMinutes: { min: 60, max: 90 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'dumbbells', 'cables', 'rack', 'bench'],
    equipmentTier: 'full-gym',
    goals: ['muscle-mass', 'hypertrophy', 'physique', 'bodybuilding'],
    metrics: { strengthEmphasis: 50, hypertrophyEmphasis: 95, enduranceEmphasis: 5, conditioningEmphasis: 10, recoveryDemand: 65, weeklyVolumeScore: 80 },
    highlights: ['Every muscle gets dedicated day', 'High volume per session', 'Technique intensifiers included', 'Classic + evidence-based'],
    expectedOutcomes: ['Maximum muscle development', 'Balanced physique', 'Strength across all lifts', 'Bodybuilder aesthetics'],
    popularity: 80, rating: 4.4, ratingCount: 1100, completionRate: 0.58, enrolledCount: 6800,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0d0a20', '#1a1540'], accentColor: '#6366f1', icon: '🏅',
    collections: ['hypertrophy-collection', 'most-popular'],
    days: {
      mon: { title: 'Chest Day', badge: 'Hypertrophy', color: 'var(--accent-blue)', desc: 'All chest, all angles.', runs: 'Rest', lifts: ['Bench Press 4×8', 'Incline DB Press 4×10', 'Cable Flye 3×12', 'Chest Dips 3×12', 'Machine Flye 2×15'] },
      tue: { title: 'Back Day', badge: 'Hypertrophy', color: 'var(--accent-green)', desc: 'Width and thickness.', runs: 'Rest', lifts: ['Barbell Row 4×8', 'Pull-Ups 4×10', 'Seated Cable Row 3×12', 'Lat Pulldown 3×10', 'Face Pulls 3×15'] },
      wed: { title: 'Shoulders Day', badge: 'Hypertrophy', color: 'var(--accent-amber)', desc: 'Full delt development.', runs: 'Rest', lifts: ['Standing OHP 4×8', 'DB Lateral Raise 4×12', 'Rear Delt Flye 3×15', 'Arnold Press 3×10', 'Shrugs 3×12'] },
      thu: { title: 'Arms Day', badge: 'Hypertrophy', color: 'var(--accent-pink)', desc: 'Biceps and triceps specialisation.', runs: 'Rest', lifts: ['Barbell Curl 4×10', 'Hammer Curl 3×12', 'Tricep Pushdown 4×10', 'Skull Crushers 3×10', 'Cable Curl 2×15'] },
      fri: { title: 'Leg Day', badge: 'Hypertrophy', color: 'var(--accent-purple)', desc: 'Complete lower body volume.', runs: 'Rest', lifts: ['Back Squat 4×8', 'Leg Press 4×12', 'Romanian Deadlift 3×10', 'Leg Curl 3×12', 'Calf Raises 4×15'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 10, intensityLabel: 'Foundation — establish working weights' },
      '2': { sets: 3, reps: 10, intensityLabel: 'Foundation' },
      '3': { sets: 4, reps: 10, intensityLabel: 'Volume increase' },
      '4': { sets: 4, reps: 8, intensityLabel: 'Volume increase' },
      '5': { sets: 4, reps: 8, intensityLabel: 'Intensity block' },
      '6': { sets: 2, reps: 10, intensityLabel: 'Deload' },
      '7': { sets: 4, reps: 6, intensityLabel: 'Strength sub-block' },
      '8': { sets: 4, reps: 8, intensityLabel: 'Back to hypertrophy' },
      '9': { sets: 5, reps: 8, intensityLabel: 'Peak volume' },
      '10': { sets: 5, reps: 8, intensityLabel: 'Peak volume' },
      '11': { sets: 4, reps: 10, intensityLabel: 'Finisher week' },
      '12': { sets: 2, reps: 10, intensityLabel: 'Deload + assess' },
    },
    dossier: { creator: 'Helyx', focus: 'Bodybuilding Hypertrophy', philosophy: 'The bro split works — dedicate full sessions to each muscle group, apply modern loading strategies, and watch the physique change.' },
  },
  // ── BODYBUILDING ──────────────────────────────────────────────────────────────

  {
    id: 'arnolds_golden_era',
    name: "Arnold's Golden Era Blueprint",
    tagline: 'Train like the Austrian Oak at his absolute prime',
    description: "A 6-day high-volume programme inspired by Arnold Schwarzenegger's classic bodybuilding methodology. Each muscle group is trained twice per week through full range of motion with brutal volume. The foundation of the golden era physique.",
    author: { name: 'Classic Blueprint', type: 'community', verified: true },
    source: 'community',
    category: 'bodybuilding',
    subcategory: 'golden-era',
    tags: ['bodybuilding', 'golden-era', 'arnold', 'volume', '6-day', 'classic', 'mass', 'chest-back'],
    durationWeeks: 12,
    sessionsPerWeek: 6,
    sessionDurationMinutes: { min: 70, max: 100 },
    difficulty: 'advanced',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells', 'cables', 'machines'],
    equipmentTier: 'gym',
    goals: ['muscle-mass', 'aesthetics', 'bodybuilding', 'volume'],
    metrics: { strengthEmphasis: 40, hypertrophyEmphasis: 98, enduranceEmphasis: 5, conditioningEmphasis: 5, recoveryDemand: 80, weeklyVolumeScore: 98 },
    highlights: ['6-day double-split structure', 'Golden era training methods', 'Each muscle group twice weekly', 'Maximum hypertrophy volume'],
    expectedOutcomes: ['Significant muscle mass', 'Classic physique development', 'Lagging muscle correction', 'Mind-muscle connection mastery'],
    popularity: 83, rating: 4.7, ratingCount: 445, completionRate: 0.38, enrolledCount: 3200,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0d2e', '#2d1040'], accentColor: '#e879f9', icon: '🏛️',
    collections: ['bodybuilding-collection', 'most-popular', 'community-favourites'],
    days: {
      mon: {
        title: 'Chest + Back', badge: 'Volume Day', color: 'var(--accent-blue)',
        desc: 'High-volume chest and back superset session.', runs: 'Rest',
        lifts: ['Bench Press', 'Pull-Ups', 'Incline DB Press', 'Barbell Row', 'Cable Fly', 'Seated Cable Row'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Bench Press',      sets: 5, reps: '6–10',  rpe: 8,   rest: '90 sec' },
            { exercise: 'Pull-Ups',         sets: 5, reps: 'Max',   rpe: 8,   rest: '90 sec' },
            { exercise: 'Incline DB Press', sets: 4, reps: '8–12',  rpe: 7.5, rest: '90 sec' },
            { exercise: 'Barbell Row',      sets: 4, reps: '8–10',  rpe: 7.5, rest: '90 sec' },
            { exercise: 'Cable Fly',        sets: 3, reps: '12–15', rpe: 7,   rest: '60 sec' },
            { exercise: 'Seated Cable Row', sets: 3, reps: '12–15', rpe: 7,   rest: '60 sec' },
          ],
        },
      },
      tue: {
        title: 'Shoulders + Arms', badge: 'Volume Day', color: 'var(--accent-pink)',
        desc: 'Shoulders, biceps, and triceps — full arm annihilation.', runs: 'Rest',
        lifts: ['Standing OHP', 'Lateral Raise', 'Barbell Curl', 'Tricep Band Pushdown', 'Hammer Curl', 'Overhead Tricep Extension'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Standing OHP',               sets: 4, reps: '8–10',  rpe: 8,   rest: '90 sec' },
            { exercise: 'Lateral Raise',              sets: 4, reps: '12–15', rpe: 7,   rest: '60 sec' },
            { exercise: 'Barbell Curl',               sets: 4, reps: '8–12',  rpe: 8,   rest: '60 sec' },
            { exercise: 'Tricep Band Pushdown',       sets: 4, reps: '12–15', rpe: 7,   rest: '60 sec' },
            { exercise: 'Hammer Curl',                sets: 3, reps: '10–12', rpe: 7,   rest: '60 sec' },
            { exercise: 'Overhead Tricep Extension',  sets: 3, reps: '12–15', rpe: 7,   rest: '60 sec' },
          ],
        },
      },
      wed: {
        title: 'Legs', badge: 'Volume Day', color: 'var(--accent-green)',
        desc: 'Full quad, hamstring, and calf development.', runs: 'Rest',
        lifts: ['Back Squat', 'Leg Press', 'Romanian Deadlift', 'Leg Curl', 'Calf Raises'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Back Squat',        sets: 5, reps: '6–10',  rpe: 8,   rest: '3 min' },
            { exercise: 'Leg Press',         sets: 4, reps: '10–15', rpe: 7.5, rest: '2 min' },
            { exercise: 'Romanian Deadlift', sets: 4, reps: '10–12', rpe: 7,   rest: '90 sec' },
            { exercise: 'Leg Curl',          sets: 3, reps: '12–15', rpe: 7,   rest: '60 sec' },
            { exercise: 'Calf Raises',       sets: 5, reps: '15–20', rpe: 7,   rest: '60 sec' },
          ],
        },
      },
      thu: {
        title: 'Chest + Back (2)', badge: 'Volume Day', color: 'var(--accent-blue)',
        desc: 'Second chest and back session — variation emphasis.', runs: 'Rest',
        lifts: ['Incline Bench Press', 'Deadlift', 'DB Pullover', 'Chin-Ups', 'Pec Dec Fly', 'Single-Arm DB Row'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Incline Bench Press',  sets: 5, reps: '6–10',  rpe: 8,   rest: '90 sec' },
            { exercise: 'Deadlift',             sets: 4, reps: '5–8',   rpe: 8,   rest: '3 min' },
            { exercise: 'DB Pullover',          sets: 3, reps: '12–15', rpe: 6,   rest: '90 sec' },
            { exercise: 'Chin-Ups',             sets: 4, reps: 'Max',   rpe: 8,   rest: '90 sec' },
            { exercise: 'Pec Dec Fly',          sets: 3, reps: '12–15', rpe: 7,   rest: '60 sec' },
            { exercise: 'Single-Arm DB Row',    sets: 3, reps: '10–12', rpe: 7.5, rest: '60 sec' },
          ],
        },
      },
      fri: {
        title: 'Shoulders + Arms (2)', badge: 'Volume Day', color: 'var(--accent-pink)',
        desc: 'Second shoulder and arms session — isolation emphasis.', runs: 'Rest',
        lifts: ['DB Shoulder Press', 'Front Raise', 'Incline DB Curl', 'Close-Grip Bench Press', 'Face Pull', 'Rear Delt Fly'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'DB Shoulder Press',  sets: 4, reps: '8–12',  rpe: 7.5, rest: '90 sec' },
            { exercise: 'Front Raise',        sets: 3, reps: '12–15', rpe: 6.5, rest: '60 sec' },
            { exercise: 'Incline DB Curl',    sets: 4, reps: '10–12', rpe: 7,   rest: '60 sec' },
            { exercise: 'Close-Grip Bench',   sets: 4, reps: '8–12',  rpe: 7.5, rest: '90 sec' },
            { exercise: 'Face Pull',          sets: 3, reps: '15–20', rpe: 6,   rest: '60 sec' },
            { exercise: 'Rear Delt Fly',      sets: 3, reps: '15–20', rpe: 6,   rest: '60 sec' },
          ],
        },
      },
      sat: {
        title: 'Legs + Core', badge: 'Volume Day', color: 'var(--accent-green)',
        desc: 'Second leg session — hamstring emphasis plus core work.', runs: 'Rest',
        lifts: ['Front Squat', 'Bulgarian Split Squat', 'Stiff-Leg Deadlift', 'Standing Calf Raises', 'Core/Plank'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Front Squat',           sets: 4, reps: '6–10',  rpe: 8,   rest: '3 min' },
            { exercise: 'Bulgarian Split Squat', sets: 3, reps: '10–12', rpe: 7.5, rest: '2 min' },
            { exercise: 'Stiff-Leg Deadlift',    sets: 4, reps: '10–12', rpe: 7,   rest: '90 sec' },
            { exercise: 'Standing Calf Raises',  sets: 5, reps: '15–20', rpe: 7,   rest: '60 sec' },
            { exercise: 'Core/Plank',            sets: 3, reps: '60 sec', rpe: 7,  rest: '45 sec' },
          ],
        },
      },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest and recovery day.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 4, reps: 10, intensityLabel: 'Foundation — moderate weight, establish pump work' },
      '2': { sets: 4, reps: 10, intensityLabel: 'Foundation — increase working weights' },
      '3': { sets: 5, reps: 10, intensityLabel: 'Volume accumulation — add a set' },
      '4': { sets: 5, reps: 8, intensityLabel: 'Volume accumulation — heavier' },
      '5': { sets: 5, reps: 8, intensityLabel: 'Intensity phase begins' },
      '6': { sets: 5, reps: 6, intensityLabel: 'Intensity peak' },
      '7': { sets: 5, reps: 6, intensityLabel: 'Strength block — heavy compound focus' },
      '8': { sets: 3, reps: 10, intensityLabel: 'Deload — reduce volume and intensity' },
      '9': { sets: 5, reps: 8, intensityLabel: 'Final volume block' },
      '10': { sets: 5, reps: 8, intensityLabel: 'Final volume — push hard' },
      '11': { sets: 6, reps: 10, intensityLabel: 'Volume peak — maximum stimulus' },
      '12': { sets: 4, reps: 10, intensityLabel: 'Final week — full pump, assess progress' },
    },
    dossier: { creator: 'Classic Blueprint', focus: 'Bodybuilding Volume', philosophy: 'Train with maximum intensity, shock the muscle, and maintain the pump across all sessions. Volume is king.' },
  },

  {
    id: 'beginner_bodybuilding',
    name: 'Beginner Bodybuilding Foundation',
    tagline: 'Your first 12 weeks of serious muscle building',
    description: 'A 3-day full body programme built specifically for beginners entering bodybuilding. Introduces fundamental compound movements, builds the mind-muscle connection, and delivers rapid early gains through consistent progressive overload. No fluff — just the exercises that actually work.',
    author: { name: 'Helyx', type: 'official', verified: true },
    source: 'internal',
    category: 'bodybuilding',
    subcategory: 'beginner',
    tags: ['beginner', 'bodybuilding', '3-day', 'full-body', 'foundation', 'first-program', 'starter', 'progressive-overload'],
    durationWeeks: 12,
    sessionsPerWeek: 3,
    sessionDurationMinutes: { min: 45, max: 60 },
    difficulty: 'beginner',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells'],
    equipmentTier: 'gym',
    goals: ['muscle-gain', 'strength-foundation', 'learn-lifting'],
    metrics: { strengthEmphasis: 50, hypertrophyEmphasis: 70, enduranceEmphasis: 10, conditioningEmphasis: 10, recoveryDemand: 35, weeklyVolumeScore: 45 },
    highlights: ['3 days per week', 'Full body compound focus', 'Perfect for beginners', 'Master the fundamental lifts'],
    expectedOutcomes: ['Rapid beginner strength gains', 'Solid muscle foundation', 'Master all compound movements', 'Improved body composition'],
    popularity: 88, rating: 4.8, ratingCount: 923, completionRate: 0.70, enrolledCount: 6200,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a0a1a', '#1a0d2e'], accentColor: '#e879f9', icon: '🌱',
    collections: ['bodybuilding-collection', 'beginner-friendly', 'hybridhq-picks'],
    days: {
      mon: {
        title: 'Full Body A', badge: 'Push Focus', color: 'var(--accent-blue)',
        desc: 'Full body session A — squat, bench, row.', runs: 'Rest',
        lifts: ['Back Squat', 'Bench Press', 'Barbell Row', 'Lateral Raise', 'Barbell Curl'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Back Squat',    sets: 3, reps: '8–10',  rpe: 7, rest: '3 min' },
            { exercise: 'Bench Press',   sets: 3, reps: '8–10',  rpe: 7, rest: '2.5 min' },
            { exercise: 'Barbell Row',   sets: 3, reps: '8–10',  rpe: 7, rest: '2.5 min' },
            { exercise: 'Lateral Raise', sets: 3, reps: '12–15', rpe: 6, rest: '60 sec' },
            { exercise: 'Barbell Curl',  sets: 3, reps: '10–12', rpe: 6, rest: '60 sec' },
          ],
        },
      },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day.', runs: 'Rest', lifts: [] },
      wed: {
        title: 'Full Body B', badge: 'Hinge Focus', color: 'var(--accent-green)',
        desc: 'Full body session B — deadlift, OHP, pull-ups.', runs: 'Rest',
        lifts: ['Deadlift', 'Standing OHP', 'Pull-Ups', 'Romanian Deadlift', 'Tricep Band Pushdown'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Deadlift',             sets: 3, reps: '6–8',   rpe: 7.5, rest: '4 min' },
            { exercise: 'Standing OHP',         sets: 3, reps: '8–10',  rpe: 7,   rest: '2.5 min' },
            { exercise: 'Pull-Ups',             sets: 3, reps: 'Max',   rpe: 7,   rest: '2.5 min' },
            { exercise: 'Romanian Deadlift',    sets: 3, reps: '10–12', rpe: 6.5, rest: '2 min' },
            { exercise: 'Tricep Band Pushdown', sets: 3, reps: '12–15', rpe: 6,   rest: '60 sec' },
          ],
        },
      },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day.', runs: 'Rest', lifts: [] },
      fri: {
        title: 'Full Body C', badge: 'Variation Day', color: 'var(--accent-amber)',
        desc: 'Full body session C — squat variation, upper accessories.', runs: 'Rest',
        lifts: ['Back Squat', 'Incline DB Press', 'Single-Arm DB Row', 'Face Pull', 'Calf Raises'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Back Squat',         sets: 3, reps: '8–10',  rpe: 7,   rest: '3 min' },
            { exercise: 'Incline DB Press',   sets: 3, reps: '10–12', rpe: 7,   rest: '2 min' },
            { exercise: 'Single-Arm DB Row',  sets: 3, reps: '10–12', rpe: 7,   rest: '90 sec' },
            { exercise: 'Face Pull',          sets: 3, reps: '15–20', rpe: 6,   rest: '60 sec' },
            { exercise: 'Calf Raises',        sets: 4, reps: '15–20', rpe: 6,   rest: '60 sec' },
          ],
        },
      },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 10, intensityLabel: 'Foundation — light weights, perfect form' },
      '2': { sets: 3, reps: 10, intensityLabel: 'Add 2.5kg per session where possible' },
      '3': { sets: 3, reps: 8, intensityLabel: 'Intensity increase — keep adding weight' },
      '4': { sets: 3, reps: 10, intensityLabel: 'Deload — back off weight by 10%' },
      '5': { sets: 3, reps: 8, intensityLabel: 'Build phase — resuming progression' },
      '6': { sets: 4, reps: 8, intensityLabel: 'Volume increase — add a set per exercise' },
      '7': { sets: 4, reps: 8, intensityLabel: 'Continue building — consistent progression' },
      '8': { sets: 3, reps: 10, intensityLabel: 'Deload — active recovery' },
      '9': { sets: 4, reps: 6, intensityLabel: 'Strength focus — heavier loads' },
      '10': { sets: 4, reps: 8, intensityLabel: 'Volume focus — more reps, moderate load' },
      '11': { sets: 4, reps: 8, intensityLabel: 'Final push — give everything' },
      '12': { sets: 3, reps: 10, intensityLabel: 'Assessment week — test your 3-rep maxes' },
    },
    dossier: { creator: 'Helyx', focus: 'Beginner Bodybuilding', philosophy: 'The fastest gains happen at the start. Master the fundamentals, add weight consistently, and the muscle follows.' },
  },
  // ── HOME GYM ──────────────────────────────────────────────────────────────

  {
    id: 'home_gym_rebuild_5day',
    name: '5-Day Home Gym Strength + Size Rebuild',
    tagline: 'Rebuild strength and fullness with a barbell, dumbbells and bands',
    description: 'A 5-day powerbuilding split designed for a home gym — barbell, squat rack, dumbbells up to 30kg and resistance bands. Two heavy strength days rebuild the main lifts, three hypertrophy days chase arm, shoulder and chest size. Built to regain momentum and fullness, not to max out early: main lifts stop 1–2 reps shy of failure while isolation work is pushed hard.',
    author: { name: 'Helyx', type: 'official', verified: true },
    source: 'internal',
    category: 'hypertrophy',
    subcategory: 'powerbuilding',
    tags: ['home-gym', 'powerbuilding', 'strength', 'hypertrophy', 'size', '5-day', 'bands', 'dumbbells', 'intermediate', 'rebuild'],
    durationWeeks: 10,
    sessionsPerWeek: 5,
    sessionDurationMinutes: { min: 50, max: 75 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack', 'dumbbells', 'bands'],
    equipmentTier: 'home',
    goals: ['strength', 'muscle-gain', 'hypertrophy', 'body-composition'],
    metrics: { strengthEmphasis: 70, hypertrophyEmphasis: 85, enduranceEmphasis: 5, conditioningEmphasis: 5, recoveryDemand: 55, weeklyVolumeScore: 72 },
    highlights: ['5-day strength + size split', 'Home-gym kit only (barbell, DBs, bands)', 'Two heavy days + three pump days', 'RIR-based — no early maxing'],
    expectedOutcomes: ['Regained strength on the main lifts', 'Visible arm, shoulder and chest size', 'Overall muscular fullness', 'Rebuilt training momentum'],
    popularity: 60, rating: 4.7, ratingCount: 12, completionRate: 0.55, enrolledCount: 40,
    featured: false, verified: true, isNew: true,
    coverGradient: ['#0a1628', '#1e3a5f'], accentColor: '#f59e0b', icon: '🏠',
    collections: ['hypertrophy-collection', 'strength-collection', 'home-gym-collection'],
    days: {
      mon: {
        title: 'Upper Strength', badge: 'Strength', color: 'var(--accent-blue)',
        desc: 'Heavy horizontal + vertical push/pull. Barbell Bench Press (4×5-8). Barbell Row (4×6-10). Standing Barbell Overhead Press (3×5-8). One-Arm Dumbbell Row (3×8-12). Close-Grip Bench Press (3×6-10). Band Face Pull (3×15-25). Dumbbell Curl (3×8-12).',
        runs: 'Rest',
        lifts: ['Barbell Bench Press', 'Barbell Row', 'Standing Barbell Overhead Press', 'One-Arm Dumbbell Row', 'Close-Grip Bench Press', 'Band Face Pull', 'Dumbbell Curl'],
      },
      tue: {
        title: 'Lower Strength', badge: 'Strength', color: 'var(--accent-green)',
        desc: 'Squat + hinge foundation. Back Squat (4×5-8). Romanian Deadlift (4×6-10). Dumbbell Bulgarian Split Squat (3×8-12). Dumbbell Calf Raise (4×10-20). Weighted Sit-Up (3×15).',
        runs: 'Rest',
        lifts: ['Back Squat', 'Romanian Deadlift', 'Dumbbell Bulgarian Split Squat', 'Dumbbell Calf Raise', 'Weighted Sit-Up'],
      },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: {
        title: 'Push Hypertrophy', badge: 'Hypertrophy', color: 'var(--accent-amber)',
        desc: 'Chest, shoulders and triceps volume. Incline Dumbbell Press (4×8-12). Dumbbell Shoulder Press (3×8-12). Dumbbell Lateral Raise (4×12-25). Push-Ups (3×max). Band Triceps Pushdown (4×12-25). Dumbbell Skull Crusher (3×10-15).',
        runs: 'Rest',
        lifts: ['Incline Dumbbell Press', 'Dumbbell Shoulder Press', 'Dumbbell Lateral Raise', 'Push-Ups', 'Band Triceps Pushdown', 'Dumbbell Skull Crusher'],
      },
      fri: {
        title: 'Pull Hypertrophy', badge: 'Hypertrophy', color: 'var(--accent-purple)',
        desc: 'Back, rear delts and biceps volume. Barbell Row (4×8-12). One-Arm Dumbbell Row (4×10-15). Band Face Pull (4×15-25). Dumbbell Rear Delt Raise (3×15-25). Barbell Curl (3×8-12). Dumbbell Hammer Curl (3×10-15). Dumbbell Shrug (3×10-15).',
        runs: 'Rest',
        lifts: ['Barbell Row', 'One-Arm Dumbbell Row', 'Band Face Pull', 'Dumbbell Rear Delt Raise', 'Barbell Curl', 'Dumbbell Hammer Curl', 'Dumbbell Shrug'],
      },
      sat: {
        title: 'Arms / Shoulders / Chest Pump', badge: 'Pump', color: 'var(--accent-pink)',
        desc: 'Full upper-body pump finisher. Standing Overhead Press (3×5-8). Dumbbell Lateral Raise (5×15-25). Close-Grip Bench Press (4×6-10). Band Triceps Pushdown (4×15-25). Dumbbell Curl (4×8-12). Incline Dumbbell Press (3×10-15). Band Face Pull (3×20-30). Push-Ups (2×max).',
        runs: 'Rest',
        lifts: ['Standing Overhead Press', 'Dumbbell Lateral Raise', 'Close-Grip Bench Press', 'Band Triceps Pushdown', 'Dumbbell Curl', 'Incline Dumbbell Press', 'Band Face Pull', 'Push-Ups'],
      },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1':  { sets: 3, reps: 10, intensityLabel: 'Rebuild — controlled reps, 2–3 in reserve' },
      '2':  { sets: 3, reps: 10, intensityLabel: 'Rebuild — same loads, add reps toward the top' },
      '3':  { sets: 4, reps: 8,  intensityLabel: 'Add load where all sets hit the top of the range' },
      '4':  { sets: 4, reps: 8,  intensityLabel: 'Keep 2 in reserve on main lifts' },
      '5':  { sets: 4, reps: 8,  intensityLabel: 'Push isolation closer to failure' },
      '6':  { sets: 2, reps: 10, intensityLabel: 'Deload — drop a set, back off ~10%' },
      '7':  { sets: 4, reps: 6,  intensityLabel: 'Strength emphasis — heavier compounds, 1–2 in reserve' },
      '8':  { sets: 4, reps: 8,  intensityLabel: 'Volume back up — chase the pump' },
      '9':  { sets: 5, reps: 8,  intensityLabel: 'Peak volume — isolation to failure' },
      '10': { sets: 3, reps: 10, intensityLabel: 'Deload + assess — retest working weights' },
    },
    dossier: { creator: 'Helyx', focus: 'Home-Gym Powerbuilding', philosophy: 'You do not need a commercial gym to rebuild. Anchor the week on two heavy strength days, chase size on three hypertrophy days, leave 1–2 reps in reserve on the big lifts, and push the isolation work — the fullness follows.' },
  },

];
