// =============================================================================
// AUTO-GENERATED — split from catalog.js. Edit individual entries here.
// =============================================================================

export default [
  // ── HYROX — ADDITIONAL ────────────────────────────────────────────────────

  {
    id: 'hyrox_advanced',
    name: 'Hyrox Advanced Competitor',
    tagline: 'Train for a podium finish at Hyrox',
    description: 'A 20-week elite Hyrox preparation program for experienced athletes targeting sub-60min male or sub-70min female performance. High volume, high intensity, race-specific simulation weeks, and advanced sled/ski work. This program demands everything.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'hyrox',
    subcategory: 'elite-prep',
    tags: ['hyrox', 'race', 'hyrox-collection', 'competition', 'advanced', 'sled', 'ski-erg', 'elite', 'sub-60', 'functional'],
    durationWeeks: 20,
    sessionsPerWeek: 6,
    sessionDurationMinutes: { min: 60, max: 100 },
    difficulty: 'advanced',
    equipment: ['ski-erg', 'sled', 'rowing-machine', 'kettlebell', 'sandbag', 'running-shoes', 'barbell', 'rack'],
    equipmentTier: 'full-gym',
    goals: ['hyrox-performance', 'sub-60', 'podium', 'elite-fitness'],
    metrics: { strengthEmphasis: 65, hypertrophyEmphasis: 30, enduranceEmphasis: 85, conditioningEmphasis: 95, recoveryDemand: 90, weeklyVolumeScore: 90 },
    highlights: ['20-week competition prep', 'Race simulations monthly', 'Sub-60 pacing strategy', 'All 8 Hyrox stations programmed'],
    expectedOutcomes: ['Sub-60min Hyrox time', 'Elite work capacity', 'Station proficiency', 'Podium-ready'],
    popularity: 77, rating: 4.9, ratingCount: 290, completionRate: 0.44, enrolledCount: 1800,
    featured: true, verified: true, isNew: true,
    coverGradient: ['#1a0e00', '#2d1a00'], accentColor: '#f59e0b', icon: '🏅',
    collections: ['hyrox-collection', 'hybridhq-picks', 'new-programs', 'highest-rated'],
    days: {
      mon: { title: 'Strength + Ski Erg', badge: 'Hyrox', color: 'var(--accent-amber)', desc: 'Heavy compound lifting + ski erg intervals.', runs: '🎿 Ski Erg 4×250m hard', lifts: ['Back Squat 5×5', 'Barbell Row 4×6', 'Farmers Carry 3×40m'] },
      tue: { title: 'Long Run + Row', badge: 'Hyrox', color: 'var(--accent-blue)', desc: 'Aerobic base + rowing.', runs: '🏃 8-14km Zone 2 + 🚣 1000m Row cool-down', lifts: [] },
      wed: { title: 'Hyrox Stations', badge: 'Hyrox', color: 'var(--accent-pink)', desc: 'Specific station work.', runs: 'Rest', lifts: ['Sled Push 6×25m', 'Sled Pull 6×25m', 'Wall Balls 5×20', 'Burpee Broad Jump 4×10', 'KB Farmer Carry 4×50m'] },
      thu: { title: 'Strength + Conditioning', badge: 'Hyrox', color: 'var(--accent-green)', desc: 'Deadlift + conditioning circuit.', runs: '🔥 20min Hyrox-style conditioning circuit', lifts: ['Deadlift 4×5', 'Sandbag Lunges 3×20', 'Pull-Ups 3×10'] },
      fri: { title: 'Run + Row + Ski', badge: 'Hyrox', color: 'var(--accent-purple)', desc: 'Multi-modal cardio.', runs: '🏃 5km run + 🚣 500m row + 🎿 500m ski erg', lifts: [] },
      sat: { title: 'Race Simulation', badge: 'Race', color: 'var(--accent-amber)', desc: 'Full or half Hyrox simulation.', runs: '🏅 Full race simulation (monthly) or half sim', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Mandatory rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 8, intensityLabel: 'Phase 1: Aerobic base + station intro' },
      '2': { sets: 3, reps: 8, intensityLabel: 'Phase 1: Volume increase' },
      '3': { sets: 4, reps: 6, intensityLabel: 'Phase 1: Intensity introduction' },
      '4': { sets: 2, reps: 5, intensityLabel: 'Deload + Half Hyrox Simulation' },
      '5': { sets: 4, reps: 6, intensityLabel: 'Phase 2: Build strength base' },
      '6': { sets: 4, reps: 6, intensityLabel: 'Phase 2: Add station volume' },
      '7': { sets: 4, reps: 5, intensityLabel: 'Phase 2: Strength emphasis' },
      '8': { sets: 2, reps: 5, intensityLabel: 'Deload + Full Hyrox Simulation' },
      '9': { sets: 4, reps: 5, intensityLabel: 'Phase 3: Competition specific' },
      '10': { sets: 4, reps: 4, intensityLabel: 'Phase 3: High intensity' },
      '11': { sets: 5, reps: 4, intensityLabel: 'Phase 3: Peak volume' },
      '12': { sets: 2, reps: 3, intensityLabel: 'Deload + Race Simulation' },
      '13': { sets: 4, reps: 5, intensityLabel: 'Phase 4: Final competition prep' },
      '14': { sets: 4, reps: 4, intensityLabel: 'Phase 4: Peak intensity' },
      '15': { sets: 5, reps: 3, intensityLabel: 'Phase 4: Top-end conditioning' },
      '16': { sets: 2, reps: 3, intensityLabel: 'Deload + Pre-race tune-up' },
      '17': { sets: 3, reps: 4, intensityLabel: 'Phase 5: Race-sharp' },
      '18': { sets: 3, reps: 3, intensityLabel: 'Phase 5: Maintain fitness' },
      '19': { sets: 2, reps: 3, intensityLabel: 'Taper begins' },
      '20': { sets: 1, reps: 2, intensityLabel: 'Race week — rest, visualise, execute' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Elite Hyrox', philosophy: 'A podium Hyrox time demands concurrent excellence across running, ski erg, sled, and functional stations. This program develops all simultaneously.' },
  },
  // ── HOME GYM ─────────────────────────────────────────────────────────────────

  {
    id: 'dumbbell_home_programme',
    name: 'Dumbbell Home Programme',
    tagline: 'A complete strength programme — no gym required',
    description: 'A 10-week full-body programme requiring nothing but a pair of adjustable dumbbells. Covers every major muscle group with intelligent exercise selection, progressive overload built through rep ranges and tempo, and time-efficient sessions that deliver real results from home.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    source: 'internal',
    category: 'strength',
    subcategory: 'home-gym',
    tags: ['home', 'dumbbells', 'home-gym', 'no-equipment', 'strength', 'hypertrophy', '4-day', 'accessible'],
    durationWeeks: 10,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 40, max: 55 },
    difficulty: 'beginner',
    equipment: ['dumbbells'],
    equipmentTier: 'home',
    goals: ['strength', 'muscle-gain', 'home-training', 'body-composition'],
    metrics: { strengthEmphasis: 55, hypertrophyEmphasis: 70, enduranceEmphasis: 15, conditioningEmphasis: 25, recoveryDemand: 40, weeklyVolumeScore: 60 },
    highlights: ['Dumbbells only', '40–55 min sessions', 'Train anywhere', 'Full body split structure'],
    expectedOutcomes: ['Real strength gains at home', 'Muscle development', 'No gym? No problem', 'Consistent training habit'],
    popularity: 85, rating: 4.7, ratingCount: 1123, completionRate: 0.68, enrolledCount: 6800,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a140a', '#0d2e14'], accentColor: '#10b981', icon: '🏠',
    collections: ['home-gym-collection', 'beginner-friendly', 'most-popular', 'hybridhq-picks'],
    days: {
      mon: {
        title: 'Upper A — Push Focus', badge: 'Home', color: 'var(--accent-blue)',
        desc: 'Chest, shoulders, triceps — push emphasis.', runs: 'Rest',
        lifts: ['Incline DB Press', 'DB Shoulder Press', 'Lateral Raise', 'Tricep Kickback', 'Push-Ups'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Incline DB Press',  sets: 4, reps: '8–12',  rpe: 7.5, rest: '90 sec', notes: 'Use pillows or books under one end of a bench, or lie on your stairs.' },
            { exercise: 'DB Shoulder Press', sets: 3, reps: '10–12', rpe: 7,   rest: '90 sec' },
            { exercise: 'Lateral Raise',     sets: 3, reps: '12–15', rpe: 7,   rest: '60 sec' },
            { exercise: 'Tricep Kickback',   sets: 3, reps: '12–15', rpe: 7,   rest: '60 sec' },
            { exercise: 'Push-Ups',          sets: 3, reps: 'Max',   rpe: 7,   rest: '60 sec', notes: 'Add weight to back if bodyweight becomes easy. Or elevate feet for more challenge.' },
          ],
        },
      },
      tue: {
        title: 'Lower A — Quad Focus', badge: 'Home', color: 'var(--accent-green)',
        desc: 'Quad-dominant legs — DB goblet squat, lunges, step-ups.', runs: 'Rest',
        lifts: ['DB Goblet Squat', 'DB Lunge', 'DB Step-Up', 'DB Romanian Deadlift', 'Calf Raises'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'DB Goblet Squat',      sets: 4, reps: '10–15', rpe: 7.5, rest: '2 min', notes: 'Hold one DB at chest height. Deep squat — sit into it.' },
            { exercise: 'DB Reverse Lunge',     sets: 3, reps: '10 each', rpe: 7,  rest: '90 sec' },
            { exercise: 'DB Step-Up',           sets: 3, reps: '10 each', rpe: 7,  rest: '90 sec', notes: 'Use a sturdy box, chair, or stairs. Knee should track over toe.' },
            { exercise: 'DB Romanian Deadlift', sets: 4, reps: '10–12', rpe: 7,   rest: '90 sec', notes: 'Hinge at the hips. Feel the hamstring stretch at the bottom.' },
            { exercise: 'Calf Raises',          sets: 4, reps: '20–25', rpe: 6,   rest: '45 sec', notes: 'Use a step for full range. Hold DBs at sides for load.' },
          ],
        },
      },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day.', runs: 'Rest', lifts: [] },
      thu: {
        title: 'Upper B — Pull Focus', badge: 'Home', color: 'var(--accent-blue)',
        desc: 'Back and biceps — pull emphasis.', runs: 'Rest',
        lifts: ['DB Row', 'Renegade Row', 'DB Rear Delt Fly', 'Hammer Curl', 'DB Curl'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Single-Arm DB Row',  sets: 4, reps: '10–12', rpe: 7.5, rest: '90 sec', notes: 'Brace knee on bench or chair. Pull elbow to hip — not to shoulder.' },
            { exercise: 'Renegade Row',       sets: 3, reps: '8 each', rpe: 8,   rest: '90 sec', notes: 'Plank position, row DB to hip. Avoid rotation.' },
            { exercise: 'DB Rear Delt Fly',   sets: 3, reps: '15–20', rpe: 6.5, rest: '60 sec', notes: 'Hinge forward 45°. Lead with elbows, squeeze rear delts.' },
            { exercise: 'Hammer Curl',        sets: 3, reps: '10–12', rpe: 7,   rest: '60 sec' },
            { exercise: 'DB Curl',            sets: 3, reps: '10–12', rpe: 7,   rest: '60 sec' },
          ],
        },
      },
      fri: {
        title: 'Lower B — Ham Focus', badge: 'Home', color: 'var(--accent-green)',
        desc: 'Hamstring and glute dominant — hip hinges and single leg work.', runs: 'Rest',
        lifts: ['DB Romanian Deadlift', 'DB Hip Thrust', 'DB Single-Leg Deadlift', 'DB Sumo Squat', 'Core/Plank'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'DB Romanian Deadlift',     sets: 4, reps: '10–12', rpe: 7.5, rest: '90 sec' },
            { exercise: 'DB Hip Thrust',            sets: 4, reps: '12–15', rpe: 7.5, rest: '90 sec', notes: 'Shoulders on bench, DB on hips. Drive through heels and squeeze hard at top.' },
            { exercise: 'DB Single-Leg Deadlift',   sets: 3, reps: '8–10 each', rpe: 7, rest: '90 sec', notes: 'Balance on one leg — slow and controlled. Hip hinge, not a squat.' },
            { exercise: 'DB Sumo Squat',            sets: 3, reps: '12–15', rpe: 7,   rest: '90 sec' },
            { exercise: 'Core/Plank',               sets: 3, reps: '45 sec', rpe: 7,  rest: '30 sec' },
          ],
        },
      },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 12, intensityLabel: 'Foundation — learn movements, moderate weight' },
      '2': { sets: 3, reps: 12, intensityLabel: 'Foundation — increase weight if 12 reps feel easy' },
      '3': { sets: 4, reps: 10, intensityLabel: 'Volume increase — add a set' },
      '4': { sets: 4, reps: 10, intensityLabel: 'Build — push loads up' },
      '5': { sets: 4, reps: 8, intensityLabel: 'Intensity — heavier, fewer reps' },
      '6': { sets: 3, reps: 12, intensityLabel: 'Deload — drop weight 15%, same volume' },
      '7': { sets: 4, reps: 8, intensityLabel: 'Intensity block — near your limit' },
      '8': { sets: 5, reps: 8, intensityLabel: 'Volume peak — 5 sets' },
      '9': { sets: 5, reps: 10, intensityLabel: 'Peak — high effort across all sets' },
      '10': { sets: 4, reps: 10, intensityLabel: 'Completion — test final rep maxes' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Home Gym Strength', philosophy: 'You do not need a full gym to get strong. A pair of adjustable dumbbells and consistency beats the most expensive equipment used inconsistently.' },
  },
  // ── HYROX ────────────────────────────────────────────────────────────────────

  {
    id: 'hyrox_first_timer',
    name: 'Hyrox First Timer',
    tagline: 'Cross your first Hyrox finish line with confidence',
    description: 'A 12-week programme purpose-built for first-time Hyrox competitors. Introduces all 8 Hyrox stations, builds the running base needed to cover 8km across the event, and develops the strength-endurance capacity to complete every station without stopping. No prior Hyrox experience required.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    source: 'internal',
    category: 'hyrox',
    subcategory: 'first-timer',
    tags: ['hyrox', 'first-timer', 'beginner-hyrox', 'race-prep', 'conditioning', 'running', 'strength-endurance', '12-week'],
    durationWeeks: 12,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 50, max: 70 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'dumbbells', 'sled', 'ski-erg', 'rowing-machine', 'kettlebell', 'sandbag'],
    equipmentTier: 'gym',
    goals: ['hyrox', 'race-completion', 'conditioning', 'strength-endurance'],
    metrics: { strengthEmphasis: 45, hypertrophyEmphasis: 15, enduranceEmphasis: 70, conditioningEmphasis: 90, recoveryDemand: 65, weeklyVolumeScore: 70 },
    highlights: ['All 8 Hyrox stations trained', '4 sessions per week', 'Running base included', 'Race-day simulation sessions'],
    expectedOutcomes: ['Complete your first Hyrox', 'Confidence at every station', 'Strong running endurance', 'Under 90-minute finish time'],
    popularity: 80, rating: 4.8, ratingCount: 467, completionRate: 0.62, enrolledCount: 3100,
    featured: false, verified: true, isNew: true,
    coverGradient: ['#1a0e2e', '#2d1a4e'], accentColor: '#7c3aed', icon: '🏟️',
    collections: ['hyrox-collection', 'new-programs', 'hybridhq-picks'],
    days: {
      mon: {
        title: 'Run + Strength', badge: 'Hyrox', color: 'var(--accent-green)',
        desc: 'Aerobic run followed by compound strength work.', runs: '🏃 3–5km easy Zone 2 run',
        lifts: ['Back Squat', 'Romanian Deadlift', 'Barbell Row', 'Farmers Carry'],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Zone 2 Run',       type: 'warmup',  duration: '3–5km',  pace: 'Zone 2 — conversational', description: 'Easy aerobic run — builds the running base for 8× 1km race sections' },
            { name: 'Strength Block',   type: 'mainSet', duration: '30 min',  pace: '—',                      description: 'Back Squat 4×6 · Romanian Deadlift 3×10 · Barbell Row 3×8 · Farmers Carry 4×30m', notes: 'Keep strength work quality high even after the run' },
          ],
        },
      },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day.', runs: 'Rest', lifts: [] },
      wed: {
        title: 'Hyrox Station Skill', badge: 'Hyrox', color: 'var(--accent-amber)',
        desc: 'Learn and drill all 8 Hyrox stations at race-pace intensity.', runs: '400m warm-up run',
        lifts: ['Sled Push', 'Sled Pull', 'Burpee Broad Jump', 'Rowing', 'Farmers Carry', 'Sandbag Lunges', 'Wall Balls', 'KB Single-Arm Farmers Carry'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'SkiErg',             sets: 1, reps: '1km',    rpe: 7,   rest: '2 min',  notes: 'Weeks 1-4: 500m. Weeks 5-8: 750m. Weeks 9-12: 1km. Steady push, even split.' },
            { exercise: 'Sled Push',           sets: 1, reps: '50m',   rpe: 8,   rest: '2 min',  notes: 'Load: bodyweight. Drive from hips, short powerful steps.' },
            { exercise: 'Sled Pull',           sets: 1, reps: '50m',   rpe: 8,   rest: '2 min',  notes: 'Row the rope hand-over-hand. Brace your core.' },
            { exercise: 'Burpee Broad Jump',   sets: 1, reps: '80m',   rpe: 8.5, rest: '2 min',  notes: 'Race quantity (80). Jump forward as far as possible each rep.' },
            { exercise: 'Rowing',              sets: 1, reps: '1km',   rpe: 7,   rest: '2 min',  notes: 'Maintain a consistent stroke rate (22–24 spm). Legs drive first.' },
            { exercise: 'Farmers Carry',       sets: 1, reps: '200m',  rpe: 7,   rest: '2 min',  notes: 'Two KBs or DBs. Stand tall, short fast steps.' },
            { exercise: 'Sandbag Lunges',      sets: 1, reps: '100m',  rpe: 8,   rest: '2 min',  notes: 'Sandbag on shoulder. Walking lunges — full extension at top.' },
            { exercise: 'Wall Balls',          sets: 1, reps: '75 reps', rpe: 8.5, rest: '—',    notes: 'Drive from squat, throw ball to target height. Catch and go again.' },
          ],
        },
      },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day.', runs: 'Rest', lifts: [] },
      fri: {
        title: 'Upper Body + Conditioning', badge: 'Hyrox', color: 'var(--accent-blue)',
        desc: 'Upper body strength and arm/shoulder conditioning for station work.', runs: 'Rest',
        lifts: ['Bench Press', 'Barbell Row', 'Pull-Ups', 'Standing OHP', 'KB Swing'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Bench Press',         sets: 4, reps: '6–8',   rpe: 7.5, rest: '2 min' },
            { exercise: 'Barbell Row',         sets: 4, reps: '8',     rpe: 7.5, rest: '2 min' },
            { exercise: 'Pull-Ups',            sets: 4, reps: 'Max',   rpe: 8,   rest: '90 sec' },
            { exercise: 'Standing OHP',        sets: 3, reps: '8–10',  rpe: 7,   rest: '90 sec' },
            { exercise: 'KB Swing (Finisher)', sets: 1, reps: '5×20',  rpe: 8.5, rest: '45 sec each', notes: 'EMOM 5 min — 20 KB swings at the start of each minute' },
          ],
        },
      },
      sat: {
        title: 'Long Run + Mini Race', badge: 'Hyrox Simulation', color: 'var(--accent-pink)',
        desc: 'Long aerobic run + mini Hyrox race simulation.', runs: '🏃 5–8km long run',
        lifts: ['Burpee Broad Jump', 'Wall Balls', 'Sled Push', 'KB Farmers Carry'],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Long Run',      type: 'mainSet', duration: '5–8km',  pace: 'Zone 2–3',         description: 'Increasing each week — 5km in Week 1 to 8km by Week 9', notes: 'This builds the running base for the 8× 1km sections between stations in a Hyrox race' },
            { name: 'Race Sim',      type: 'mainSet', duration: '15–20 min', pace: 'Race intensity', description: 'Mini Hyrox circuit: Burpee Broad Jump 80 + Wall Balls 30 + Sled Push 25m + KB Carry 50m', notes: 'Do this with as little rest as possible. Simulate race day transitions.' },
          ],
        },
      },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest day.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 8, intensityLabel: 'Foundation — learn all stations, low intensity' },
      '2': { sets: 3, reps: 8, intensityLabel: 'Foundation — increase station durations/distances' },
      '3': { sets: 4, reps: 8, intensityLabel: 'Build — increase all volumes 10%' },
      '4': { sets: 2, reps: 8, intensityLabel: 'Deload — reduce volume 30%' },
      '5': { sets: 4, reps: 6, intensityLabel: 'Intensity — increase loads, maintain durations' },
      '6': { sets: 4, reps: 6, intensityLabel: 'Intensity — race-specific pacing practice' },
      '7': { sets: 4, reps: 6, intensityLabel: 'Peak block — maximum volume' },
      '8': { sets: 2, reps: 8, intensityLabel: 'Deload' },
      '9': { sets: 4, reps: 5, intensityLabel: 'Race specific — full station distances' },
      '10': { sets: 4, reps: 5, intensityLabel: 'Race specific — race pace efforts' },
      '11': { sets: 3, reps: 6, intensityLabel: 'Pre-race taper — reduce volume 20%' },
      '12': { sets: 2, reps: 6, intensityLabel: 'Race week — HYROX DAY' },
    },
    dossier: { creator: 'HybridHQ', focus: 'Hyrox Race Preparation', philosophy: 'The athletes who suffer most in Hyrox are those who never practised the stations at race pace. Train the transitions. Train the suffering. Race day becomes easy.' },
  },
  // ── HYROX WODs ───────────────────────────────────────────────────────────────

  {
    id: 'hyrox_wod_race_sim',
    name: 'HYROX Race Simulation',
    tagline: 'The full HYROX race — 8km run + 8 stations',
    description: 'The standard HYROX competition format in full. Eight 1km runs, each followed by one of the iconic HYROX functional stations. The total distance is 8km of running plus all eight stations completed in sequence. This is the benchmark — know exactly what race day feels like before you get there.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'hyrox',
    subcategory: 'race-simulation',
    tags: ['hyrox', 'hyrox-wod', 'race-sim', 'singles', 'functional', 'running', 'conditioning', 'benchmark'],
    durationWeeks: 1,
    sessionsPerWeek: 1,
    sessionDurationMinutes: { min: 60, max: 90 },
    difficulty: 'advanced',
    equipment: ['ski-erg', 'sled', 'rowing-machine', 'kettlebell', 'sandbag', 'running-shoes'],
    equipmentTier: 'gym',
    goals: ['hyrox', 'race-completion', 'conditioning'],
    metrics: { strengthEmphasis: 40, hypertrophyEmphasis: 10, enduranceEmphasis: 80, conditioningEmphasis: 95, recoveryDemand: 85, weeklyVolumeScore: 90 },
    highlights: ['Full HYROX race format', '8km total running', 'All 8 official stations', 'Race-day experience'],
    expectedOutcomes: ['Race readiness', 'Pacing strategy', 'Transitions practice', 'Time benchmark'],
    popularity: 96, rating: 4.9, ratingCount: 1840, completionRate: 0.71, enrolledCount: 9200,
    featured: true, verified: true, isNew: false,
    coverGradient: ['#1a0520', '#2d1060'], accentColor: '#7c3aed', icon: '🏟️',
    collections: ['hyrox-collection', 'hyrox-wods', 'hybridhq-picks', 'most-popular', 'highest-rated'],
    days: {
      mon: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sat: {
        title: 'HYROX Race Simulation', badge: 'Full Race', color: 'var(--accent-purple)',
        desc: 'Full HYROX race: 8×1km runs alternating with 8 functional stations. Go for time.',
        runs: '🏃 8×1km at race pace (between each station)',
        lifts: ['SkiErg 1000m', 'Sled Push 50m', 'Sled Pull 50m', 'Burpee Broad Jump 80m', 'Rowing 1000m', 'Farmers Carry 200m', 'Sandbag Lunges 100m', 'Wall Balls 100 reps'],
        workoutPreview: {
          type: 'HYROX',
          format: 'race',
          totalTime: '~60–90 min',
          notes: 'Men\'s Open: Sled 152/103kg, Farmers 2×24kg, Sandbag 20kg, Wall Ball 6kg/10ft. Women\'s Open: Sled 102/78kg, Farmers 2×16kg, Sandbag 10kg, Wall Ball 4kg/9ft. Start a running clock and do not stop.',
          stations: [
            { run: '1km', station: 'SkiErg — 1,000m', weight: null, notes: 'Set a sustainable pace from rep 1' },
            { run: '1km', station: 'Sled Push — 50m', weight: '152kg (M) / 102kg (F)' },
            { run: '1km', station: 'Sled Pull — 50m', weight: '103kg (M) / 78kg (F)' },
            { run: '1km', station: 'Burpee Broad Jump — 80m', weight: null, notes: 'Full burpee + broad jump per rep' },
            { run: '1km', station: 'Rowing — 1,000m', weight: null },
            { run: '1km', station: 'Farmers Carry — 200m', weight: '2×24kg (M) / 2×16kg (F)' },
            { run: '1km', station: 'Sandbag Lunges — 100m', weight: '20kg (M) / 10kg (F)', notes: 'Alternate legs, bag on shoulder or held at chest' },
            { run: '1km', station: 'Wall Balls — 100 reps', weight: '6kg/10ft target (M) / 4kg/9ft (F)' },
          ],
        },
      },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: { '1': { sets: 1, reps: 1, intensityLabel: 'Race simulation — full effort' } },
    dossier: { creator: 'HybridHQ', focus: 'HYROX Race Simulation', philosophy: 'You cannot prepare for a HYROX race without experiencing the suffering of the full format. This WOD gives you exactly that — before race day.' },
  },

  {
    id: 'hyrox_wod_doubles',
    name: 'HYROX Doubles Simulation',
    tagline: 'Partner race format — split the work, share the pain',
    description: 'The official HYROX Doubles format with a partner. Each athlete runs every 1km section independently, but stations are split 50/50. Both athletes must work simultaneously during station blocks. A great way to introduce the HYROX format with a training partner or as a step toward singles.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'hyrox',
    subcategory: 'race-simulation',
    tags: ['hyrox', 'hyrox-wod', 'doubles', 'partner', 'race-sim', 'functional', 'conditioning'],
    durationWeeks: 1,
    sessionsPerWeek: 1,
    sessionDurationMinutes: { min: 45, max: 70 },
    difficulty: 'intermediate',
    equipment: ['ski-erg', 'sled', 'rowing-machine', 'kettlebell', 'sandbag', 'running-shoes'],
    equipmentTier: 'gym',
    goals: ['hyrox', 'conditioning', 'race-completion'],
    metrics: { strengthEmphasis: 35, hypertrophyEmphasis: 10, enduranceEmphasis: 75, conditioningEmphasis: 90, recoveryDemand: 70, weeklyVolumeScore: 75 },
    highlights: ['Partner format', 'Stations split 50/50', 'Both athletes run each 1km', 'Great entry point to HYROX'],
    expectedOutcomes: ['HYROX doubles race ready', 'Station familiarity', 'Race pacing experience', 'Teamwork under fatigue'],
    popularity: 88, rating: 4.7, ratingCount: 920, completionRate: 0.75, enrolledCount: 5400,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0d1a2e', '#1a2d5c'], accentColor: '#3b82f6', icon: '👥',
    collections: ['hyrox-collection', 'hyrox-wods', 'hybridhq-picks'],
    days: {
      mon: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sat: {
        title: 'HYROX Doubles Simulation', badge: 'Partner Race', color: 'var(--accent-blue)',
        desc: 'HYROX Doubles: both athletes run every 1km. Stations split 50/50 between partners working simultaneously.',
        runs: '🏃 Both athletes run each 1km (×8)',
        lifts: ['SkiErg 500m each', 'Sled Push 25m each', 'Sled Pull 25m each', 'Burpee Broad Jump 40m each', 'Rowing 500m each', 'Farmers Carry 100m each', 'Sandbag Lunges 50m each', 'Wall Balls 50 reps each'],
        workoutPreview: {
          type: 'HYROX',
          format: 'doubles',
          totalTime: '~45–70 min',
          notes: 'Both athletes run the 1km together (or back-to-back). During stations, both athletes work simultaneously, each completing their half. Same weights as singles.',
          stations: [
            { run: '1km (both)', station: 'SkiErg — 500m each', weight: null },
            { run: '1km (both)', station: 'Sled Push — 25m each', weight: '152kg (M) / 102kg (F)' },
            { run: '1km (both)', station: 'Sled Pull — 25m each', weight: '103kg (M) / 78kg (F)' },
            { run: '1km (both)', station: 'Burpee Broad Jump — 40m each', weight: null },
            { run: '1km (both)', station: 'Rowing — 500m each', weight: null },
            { run: '1km (both)', station: 'Farmers Carry — 100m each', weight: '2×24kg (M) / 2×16kg (F)' },
            { run: '1km (both)', station: 'Sandbag Lunges — 50m each', weight: '20kg (M) / 10kg (F)' },
            { run: '1km (both)', station: 'Wall Balls — 50 reps each', weight: '6kg/10ft (M) / 4kg/9ft (F)' },
          ],
        },
      },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: { '1': { sets: 1, reps: 1, intensityLabel: 'Race simulation — full effort' } },
    dossier: { creator: 'HybridHQ', focus: 'HYROX Doubles', philosophy: 'The Doubles format is how thousands of athletes first experience HYROX. Sharing the station work means you can push harder on each effort — and accountability to a partner is powerful.' },
  },

  {
    id: 'hyrox_wod_pro',
    name: 'HYROX PRO Simulation',
    tagline: 'Elite competition weights — for serious competitors only',
    description: 'The HYROX PRO division format runs the exact same race structure as the standard race but with significantly heavier station loads. This simulation is reserved for experienced HYROX athletes preparing for the elite competition category. Do not attempt without a strong singles base.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'hyrox',
    subcategory: 'race-simulation',
    tags: ['hyrox', 'hyrox-wod', 'pro', 'elite', 'race-sim', 'advanced', 'competition', 'heavy'],
    durationWeeks: 1,
    sessionsPerWeek: 1,
    sessionDurationMinutes: { min: 70, max: 105 },
    difficulty: 'elite',
    equipment: ['ski-erg', 'sled', 'rowing-machine', 'kettlebell', 'sandbag', 'running-shoes'],
    equipmentTier: 'gym',
    goals: ['hyrox-pb', 'elite-fitness', 'competition'],
    metrics: { strengthEmphasis: 55, hypertrophyEmphasis: 10, enduranceEmphasis: 85, conditioningEmphasis: 98, recoveryDemand: 95, weeklyVolumeScore: 95 },
    highlights: ['PRO division weights', 'Elite competition format', 'Maximum intensity', 'Sub-60 pacing required'],
    expectedOutcomes: ['PRO race readiness', 'Elite capacity benchmark', 'Heavy station proficiency'],
    popularity: 74, rating: 4.9, ratingCount: 412, completionRate: 0.38, enrolledCount: 2100,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0900', '#2d1600'], accentColor: '#f59e0b', icon: '🏅',
    collections: ['hyrox-collection', 'hyrox-wods', 'highest-rated'],
    days: {
      mon: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sat: {
        title: 'HYROX PRO Simulation', badge: 'Elite Race', color: 'var(--accent-amber)',
        desc: 'Full HYROX race format with PRO division weights. For competitive athletes targeting the elite category.',
        runs: '🏃 8×1km at sub-4:30/km pace',
        lifts: ['SkiErg 1000m', 'Sled Push 50m (202/152kg)', 'Sled Pull 50m (153/103kg)', 'Burpee Broad Jump 80m', 'Rowing 1000m', 'Farmers Carry 200m (2×32/24kg)', 'Sandbag Lunges 100m (30/20kg)', 'Wall Balls 100 reps (9/6kg)'],
        workoutPreview: {
          type: 'HYROX',
          format: 'pro',
          totalTime: '~70–105 min',
          notes: 'PRO Men: Sled 202/153kg, Farmers 2×32kg, Sandbag 30kg, Wall Ball 9kg. PRO Women: Sled 152/103kg, Farmers 2×24kg, Sandbag 20kg, Wall Ball 6kg. This is significantly harder than open — you must have completed multiple open races first.',
          stations: [
            { run: '1km', station: 'SkiErg — 1,000m', weight: null },
            { run: '1km', station: 'Sled Push — 50m', weight: '202kg (M PRO) / 152kg (F PRO)', notes: '+50kg vs Open' },
            { run: '1km', station: 'Sled Pull — 50m', weight: '153kg (M PRO) / 103kg (F PRO)', notes: '+50kg vs Open' },
            { run: '1km', station: 'Burpee Broad Jump — 80m', weight: null },
            { run: '1km', station: 'Rowing — 1,000m', weight: null },
            { run: '1km', station: 'Farmers Carry — 200m', weight: '2×32kg (M PRO) / 2×24kg (F PRO)', notes: '+8kg per hand vs Open' },
            { run: '1km', station: 'Sandbag Lunges — 100m', weight: '30kg (M PRO) / 20kg (F PRO)', notes: '+10kg vs Open' },
            { run: '1km', station: 'Wall Balls — 100 reps', weight: '9kg (M PRO) / 6kg (F PRO)', notes: '10ft target for all' },
          ],
        },
      },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: { '1': { sets: 1, reps: 1, intensityLabel: 'PRO simulation — maximum effort' } },
    dossier: { creator: 'HybridHQ', focus: 'Elite HYROX', philosophy: 'The PRO division separates the serious competitors from the recreational racers. If you are chasing a podium, this is where you train.' },
  },

  {
    id: 'hyrox_wod_half',
    name: 'HYROX Half Simulation',
    tagline: 'First 4 stations — perfect race prep for beginners',
    description: 'A half-length HYROX simulation covering the first four stations with 4km of running. An ideal race preview for new athletes still building their base, or as a high-intensity training session for experienced competitors looking for a shorter stimulus. All race weights apply.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'hyrox',
    subcategory: 'race-simulation',
    tags: ['hyrox', 'hyrox-wod', 'half', 'race-sim', 'beginner-hyrox', 'conditioning', 'functional'],
    durationWeeks: 1,
    sessionsPerWeek: 1,
    sessionDurationMinutes: { min: 30, max: 50 },
    difficulty: 'intermediate',
    equipment: ['ski-erg', 'sled', 'running-shoes'],
    equipmentTier: 'gym',
    goals: ['hyrox', 'conditioning', 'race-completion'],
    metrics: { strengthEmphasis: 30, hypertrophyEmphasis: 5, enduranceEmphasis: 70, conditioningEmphasis: 85, recoveryDemand: 65, weeklyVolumeScore: 60 },
    highlights: ['4km total running', 'First 4 HYROX stations', 'Race weights applied', 'Faster recovery needed'],
    expectedOutcomes: ['Race familiarity', 'Station confidence', 'Pacing benchmark', 'Shorter training stimulus'],
    popularity: 82, rating: 4.6, ratingCount: 674, completionRate: 0.80, enrolledCount: 4100,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0e1a2e', '#1a2d4e'], accentColor: '#60a5fa', icon: '🏃',
    collections: ['hyrox-collection', 'hyrox-wods'],
    days: {
      mon: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sat: {
        title: 'HYROX Half Simulation', badge: 'Half Race', color: 'var(--accent-blue)',
        desc: 'Half HYROX simulation: 4×1km runs + first 4 stations (SkiErg, Sled Push, Sled Pull, Burpee Broad Jump).',
        runs: '🏃 4×1km at race pace',
        lifts: ['SkiErg 1000m', 'Sled Push 50m', 'Sled Pull 50m', 'Burpee Broad Jump 80m'],
        workoutPreview: {
          type: 'HYROX',
          format: 'half',
          totalTime: '~30–50 min',
          notes: 'Treat this exactly like race day — same weights, same pacing intent. Use this as a time trial to track fitness progress.',
          stations: [
            { run: '1km', station: 'SkiErg — 1,000m', weight: null },
            { run: '1km', station: 'Sled Push — 50m', weight: '152kg (M) / 102kg (F)' },
            { run: '1km', station: 'Sled Pull — 50m', weight: '103kg (M) / 78kg (F)' },
            { run: '1km', station: 'Burpee Broad Jump — 80m', weight: null, notes: 'Finish here — record your time' },
          ],
        },
      },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: { '1': { sets: 1, reps: 1, intensityLabel: 'Half race — race pace effort' } },
    dossier: { creator: 'HybridHQ', focus: 'HYROX Race Preparation', philosophy: 'The half simulation lets you experience race pressure without the full volume. It is the ideal format for first-timers building confidence.' },
  },

  {
    id: 'hyrox_wod_ski_blitz',
    name: 'SkiErg Blitz',
    tagline: 'Destroy your aerobic ceiling with ski erg intervals',
    description: 'A dedicated SkiErg conditioning session built around the demands of HYROX station one. Alternating long intervals and short bursts develop both the aerobic base and the neuromuscular power needed to handle 1,000m of skiing after a hard 1km run. The SkiErg is the most underrated HYROX weapon.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'hyrox',
    subcategory: 'station-specific',
    tags: ['hyrox', 'hyrox-wod', 'ski-erg', 'cardio', 'intervals', 'station-specific', 'conditioning'],
    durationWeeks: 1,
    sessionsPerWeek: 1,
    sessionDurationMinutes: { min: 30, max: 45 },
    difficulty: 'intermediate',
    equipment: ['ski-erg', 'rowing-machine', 'running-shoes'],
    equipmentTier: 'gym',
    goals: ['conditioning', 'hyrox'],
    metrics: { strengthEmphasis: 10, hypertrophyEmphasis: 5, enduranceEmphasis: 85, conditioningEmphasis: 90, recoveryDemand: 70, weeklyVolumeScore: 55 },
    highlights: ['SkiErg interval work', 'HYROX station 1 specific', 'Aerobic + power development', 'Short and brutal'],
    expectedOutcomes: ['Faster SkiErg 1,000m split', 'Improved upper body endurance', 'Better race pacing', 'Aerobic capacity gains'],
    popularity: 78, rating: 4.5, ratingCount: 389, completionRate: 0.72, enrolledCount: 2800,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a1a2e', '#102040'], accentColor: '#22d3ee', icon: '🎿',
    collections: ['hyrox-collection', 'hyrox-wods'],
    days: {
      mon: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sat: {
        title: 'SkiErg Blitz', badge: 'Station 1 Drill', color: 'var(--accent-blue)',
        desc: 'SkiErg interval workout targeting HYROX station 1. High intensity, short rest.',
        runs: '🎿 4×500m ski erg (2min rest) + 2×250m sprint (90s rest)',
        lifts: ['SkiErg 500m ×4', 'SkiErg 250m ×2'],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Warm-Up',         type: 'warmup',  duration: '5 min',       pace: 'Easy ski or row', description: 'Light ski erg at 50% effort + arm circles, shoulder rolls' },
            { name: '500m Intervals',   type: 'mainSet', duration: '4 × 500m',    pace: 'Hard — RPE 8–9',  description: 'Full stroke ski erg. Drive from hips and glutes, pull to chin.', notes: '2 min rest between each. Target consistent splits — don\'t blow up on rep 1.' },
            { name: '250m Sprints',     type: 'mainSet', duration: '2 × 250m',    pace: 'All out — RPE 10', description: 'Maximum effort 250m — race pace or faster. Flush out the fatigue.', notes: '90 sec rest. These build the top-end power you need for transitions.' },
            { name: 'Run Finish',       type: 'strength', duration: '1 × 1km',   pace: 'Race pace',        description: 'Finish with a 1km run to simulate the post-ski transition', notes: 'Feel what it\'s like to run after ski erg — this is your race reality.' },
            { name: 'Cool-Down',        type: 'cooldown', duration: '5 min',      pace: 'Easy ski or walk', description: 'Easy light ski + shoulder stretch, thoracic rotation' },
          ],
        },
      },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: { '1': { sets: 1, reps: 1, intensityLabel: 'SkiErg intervals — hard effort' } },
    dossier: { creator: 'HybridHQ', focus: 'HYROX SkiErg Conditioning', philosophy: 'Most HYROX athletes neglect the ski erg in training. The ones who drill it specifically always gain time here — it is a completely trainable station.' },
  },

  {
    id: 'hyrox_wod_sled_complex',
    name: 'Sled Push & Pull Complex',
    tagline: 'Master HYROX stations 2 and 3 — the make-or-break sleds',
    description: 'Dedicated sled training targeting HYROX stations two (push) and three (pull). The sled stations are where most athletes break — either pacing too hard and grinding to a halt, or saving too much and leaving time on the table. This session teaches you exactly where the line is.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'hyrox',
    subcategory: 'station-specific',
    tags: ['hyrox', 'hyrox-wod', 'sled', 'sled-push', 'sled-pull', 'station-specific', 'strength', 'conditioning'],
    durationWeeks: 1,
    sessionsPerWeek: 1,
    sessionDurationMinutes: { min: 25, max: 40 },
    difficulty: 'advanced',
    equipment: ['sled', 'running-shoes'],
    equipmentTier: 'gym',
    goals: ['hyrox', 'strength', 'conditioning'],
    metrics: { strengthEmphasis: 65, hypertrophyEmphasis: 15, enduranceEmphasis: 50, conditioningEmphasis: 85, recoveryDemand: 80, weeklyVolumeScore: 65 },
    highlights: ['Race-weight sled work', 'Push + pull combination', 'Transition practice', 'Pacing calibration'],
    expectedOutcomes: ['Faster sled station times', 'Race-weight familiarity', 'Leg drive and endurance', 'HYROX PB contribution'],
    popularity: 80, rating: 4.6, ratingCount: 451, completionRate: 0.68, enrolledCount: 3200,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0a00', '#2d1800'], accentColor: '#f97316', icon: '🛷',
    collections: ['hyrox-collection', 'hyrox-wods'],
    days: {
      mon: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sat: {
        title: 'Sled Push & Pull Complex', badge: 'Stations 2 & 3', color: 'var(--accent-amber)',
        desc: 'Race-weight sled push and pull repeats with short 200m run transitions between sets.',
        runs: '🏃 200m jog between sled sets',
        lifts: ['Sled Push 50m ×4 (race weight)', 'Sled Pull 50m ×4 (race weight)'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Sled Push — 50m (race weight)',      sets: 4, reps: '50m',  rpe: 9,   rest: '200m jog' },
            { exercise: 'Sled Pull — 50m (race weight)',      sets: 4, reps: '50m',  rpe: 8,   rest: '200m jog' },
            { exercise: 'Push + Pull Superset — 25m each',   sets: 2, reps: '50m',  rpe: 9.5, rest: '3 min' },
          ],
        },
      },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: { '1': { sets: 1, reps: 1, intensityLabel: 'Sled complex — race weight' } },
    dossier: { creator: 'HybridHQ', focus: 'HYROX Sled Stations', philosophy: 'The sled stations destroy athletes who have not trained with race weight. Load the sled to race spec and learn what your legs can actually sustain.' },
  },

  {
    id: 'hyrox_wod_wall_ball',
    name: 'Wall Ball Century',
    tagline: '100 wall balls for time — station 8 mastery',
    description: 'One hundred wall ball shots for time — the final HYROX station done in isolation. After 7km of running and 7 stations, this is where races are won and lost. Training the wall ball fresh teaches you the movement pattern. Training it fatigued teaches you race day reality. Do both.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'hyrox',
    subcategory: 'station-specific',
    tags: ['hyrox', 'hyrox-wod', 'wall-ball', 'station-specific', 'conditioning', 'benchmark', 'functional'],
    durationWeeks: 1,
    sessionsPerWeek: 1,
    sessionDurationMinutes: { min: 15, max: 30 },
    difficulty: 'intermediate',
    equipment: ['running-shoes'],
    equipmentTier: 'gym',
    goals: ['hyrox', 'conditioning'],
    metrics: { strengthEmphasis: 30, hypertrophyEmphasis: 20, enduranceEmphasis: 40, conditioningEmphasis: 80, recoveryDemand: 50, weeklyVolumeScore: 40 },
    highlights: ['100 wall balls unbroken', 'Station 8 specific', 'Great benchmark workout', 'Short and repeatable'],
    expectedOutcomes: ['Unbroken 100 wall balls', 'Sub-5 min target', 'Leg endurance under fatigue', 'Breathing rhythm'],
    popularity: 85, rating: 4.5, ratingCount: 1120, completionRate: 0.84, enrolledCount: 6700,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0e1a0e', '#1a300e'], accentColor: '#22c55e', icon: '🏀',
    collections: ['hyrox-collection', 'hyrox-wods'],
    days: {
      mon: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sat: {
        title: 'Wall Ball Century', badge: 'Station 8', color: 'var(--accent-green)',
        desc: '100 wall ball shots for time. Use race weight. No rest — push through.',
        runs: 'Rest',
        lifts: ['Wall Balls 100 reps for time'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Warm-Up: Wall Ball — light weight', sets: 2, reps: '10',     rpe: 4,   rest: '60 sec' },
            { exercise: 'Wall Balls — race weight (6/4kg)',  sets: 1, reps: '100',    rpe: 9,   rest: 'For time' },
            { exercise: 'Descending sets if needed: 50+30+20', sets: 1, reps: '100 total', rpe: 9, rest: 'Minimal rest' },
          ],
        },
      },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: { '1': { sets: 1, reps: 100, intensityLabel: 'For time — benchmark' } },
    dossier: { creator: 'HybridHQ', focus: 'HYROX Wall Ball Station', philosophy: 'The wall ball is the last station for a reason — it rewards athletes who paced the first seven. Your ability to sustain the squat-throw rhythm when exhausted is entirely trainable.' },
  },

  {
    id: 'hyrox_wod_bbj',
    name: 'Burpee Broad Jump 80',
    tagline: '80m of burpee broad jumps — station 4 benchmark',
    description: 'Eighty metres of burpee broad jumps for time — the most dreaded HYROX station. Each rep is a full chest-to-floor burpee followed by an explosive broad jump. Unlike conventional burpees, these demand lower body explosiveness alongside cardiovascular capacity. This WOD isolates and trains the skill completely.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'hyrox',
    subcategory: 'station-specific',
    tags: ['hyrox', 'hyrox-wod', 'burpee-broad-jump', 'bbj', 'station-specific', 'conditioning', 'bodyweight', 'benchmark'],
    durationWeeks: 1,
    sessionsPerWeek: 1,
    sessionDurationMinutes: { min: 10, max: 25 },
    difficulty: 'intermediate',
    equipment: ['running-shoes'],
    equipmentTier: 'minimal',
    goals: ['hyrox', 'conditioning', 'general-health'],
    metrics: { strengthEmphasis: 20, hypertrophyEmphasis: 5, enduranceEmphasis: 50, conditioningEmphasis: 85, recoveryDemand: 55, weeklyVolumeScore: 35 },
    highlights: ['Bodyweight only', 'Station 4 isolated', 'Pure benchmark', 'Accessible anywhere'],
    expectedOutcomes: ['Faster BBJ station time', 'Improved technique', 'Cardiovascular endurance', 'Consistent rep quality'],
    popularity: 83, rating: 4.4, ratingCount: 876, completionRate: 0.88, enrolledCount: 5100,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0e0a1a', '#1a1230'], accentColor: '#a78bfa', icon: '🤸',
    collections: ['hyrox-collection', 'hyrox-wods', 'home-gym-collection'],
    days: {
      mon: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sat: {
        title: 'Burpee Broad Jump 80', badge: 'Station 4', color: 'var(--accent-purple)',
        desc: '80m of burpee broad jumps for time. Each rep: burpee to ground, jump forward as far as possible.',
        runs: 'Rest',
        lifts: ['Burpee Broad Jump 80m for time'],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Warm-Up',        type: 'warmup',  duration: '5 min',   pace: 'Easy',          description: '10 air squats + 5 regular burpees + 5 broad jumps — prime the pattern' },
            { name: 'BBJ Benchmark',  type: 'mainSet', duration: '80m',     pace: 'Race pace',     description: 'Full burpee broad jumps — chest to floor each rep, max jump distance per rep', notes: 'Goal: complete without stopping. Target sub-4 min. Avg jump of 1.2–1.5m = ~55–65 reps.' },
            { name: 'BBJ Intervals',  type: 'mainSet', duration: '3 × 20m', pace: 'Explosive',     description: 'Three 20m intervals at maximum speed to build power and technique', notes: '90 sec rest between intervals. Focus on jump distance — this builds race-day proficiency.' },
            { name: 'Cool-Down',      type: 'cooldown', duration: '5 min',  pace: 'Easy',          description: 'Walk + hip flexor stretch, thoracic rotation, quad stretch' },
          ],
        },
      },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: { '1': { sets: 1, reps: 1, intensityLabel: 'BBJ benchmark — for time' } },
    dossier: { creator: 'HybridHQ', focus: 'HYROX BBJ Station', philosophy: 'The burpee broad jump station trips up athletes who have only trained regular burpees. The explosive jump is a separate skill — train it specifically and watch your time drop.' },
  },

  {
    id: 'hyrox_wod_row_run',
    name: 'Row & Run',
    tagline: 'Rowing station + running intervals — HYROX engine work',
    description: 'A classic HYROX-specific conditioning workout pairing 500m rowing intervals with 1km runs. This combo directly trains the transition from running to the rowing station (station 5) and back to running. Develops the aerobic base and lactate tolerance needed for a fast race.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'hyrox',
    subcategory: 'conditioning',
    tags: ['hyrox', 'hyrox-wod', 'rowing', 'running', 'intervals', 'conditioning', 'cardio', 'station-specific'],
    durationWeeks: 1,
    sessionsPerWeek: 1,
    sessionDurationMinutes: { min: 35, max: 50 },
    difficulty: 'intermediate',
    equipment: ['rowing-machine', 'running-shoes'],
    equipmentTier: 'gym',
    goals: ['hyrox', 'conditioning', 'endurance'],
    metrics: { strengthEmphasis: 10, hypertrophyEmphasis: 5, enduranceEmphasis: 85, conditioningEmphasis: 88, recoveryDemand: 65, weeklyVolumeScore: 60 },
    highlights: ['Row + run intervals', 'HYROX station 5 specific', 'Aerobic engine builder', 'Minimal equipment'],
    expectedOutcomes: ['Faster rowing split', 'Better run-to-row transition', 'Improved VO2max', 'HYROX race endurance'],
    popularity: 79, rating: 4.5, ratingCount: 534, completionRate: 0.74, enrolledCount: 3600,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a1a1a', '#0e2d2d'], accentColor: '#06b6d4', icon: '🚣',
    collections: ['hyrox-collection', 'hyrox-wods'],
    days: {
      mon: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sat: {
        title: 'Row & Run', badge: 'Stations 5 + Run', color: 'var(--accent-blue)',
        desc: '5 rounds: 500m row + 1km run. Minimal rest. HYROX-style transitions throughout.',
        runs: '🏃 5×1km at race pace (after each row)',
        lifts: ['Rowing 500m ×5'],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Warm-Up',        type: 'warmup',  duration: '8 min',        pace: 'Easy row + jog',    description: '4 min easy row + 4 min easy jog — get the heart rate up gradually' },
            { name: 'Row Intervals',  type: 'mainSet', duration: '5 × (500m row + 1km run)', pace: 'Hard — RPE 8', description: 'Row 500m at a pace ~5s/500m slower than 2K PR, then immediately run 1km at race pace', notes: '90 sec transition between row and run. 2 min rest after each full round. No long breaks — this is race simulation.' },
            { name: 'Cool-Down',      type: 'cooldown', duration: '8 min',       pace: 'Easy jog + row',    description: 'Easy 5 min row at 50% + 3 min walk. Stretch hip flexors and lower back.' },
          ],
        },
      },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: { '1': { sets: 1, reps: 1, intensityLabel: 'Row & run intervals' } },
    dossier: { creator: 'HybridHQ', focus: 'HYROX Rowing + Running', philosophy: 'The run-to-row transition is one of the most underestimated challenges in HYROX. Your breathing pattern from running disrupts your rowing rhythm. Training them back-to-back solves this.' },
  },

  {
    id: 'hyrox_wod_station_gauntlet',
    name: 'Station Gauntlet',
    tagline: 'All 8 HYROX stations back-to-back — no running, maximum suffering',
    description: 'All eight HYROX stations completed in sequence without any running between them. This WOD isolates the station work and compresses the total conditioning demand into a shorter window. Great for athletes with limited time, those building station-specific fitness, or anyone who wants a brutal upper and lower body conditioning circuit.',
    author: { name: 'HybridHQ', type: 'official', verified: true },
    category: 'hyrox',
    subcategory: 'conditioning',
    tags: ['hyrox', 'hyrox-wod', 'stations', 'circuit', 'conditioning', 'functional', 'benchmark', 'no-running'],
    durationWeeks: 1,
    sessionsPerWeek: 1,
    sessionDurationMinutes: { min: 25, max: 45 },
    difficulty: 'advanced',
    equipment: ['ski-erg', 'sled', 'rowing-machine', 'kettlebell', 'sandbag', 'running-shoes'],
    equipmentTier: 'gym',
    goals: ['hyrox', 'conditioning', 'general-health'],
    metrics: { strengthEmphasis: 45, hypertrophyEmphasis: 15, enduranceEmphasis: 70, conditioningEmphasis: 92, recoveryDemand: 78, weeklyVolumeScore: 70 },
    highlights: ['All 8 stations in one session', 'No running between stations', 'Time-efficient HYROX training', 'Benchmarkable WOD'],
    expectedOutcomes: ['Station mastery', 'Improved work capacity', 'Benchmark time', 'Confidence at all stations'],
    popularity: 86, rating: 4.7, ratingCount: 728, completionRate: 0.61, enrolledCount: 4400,
    featured: true, verified: true, isNew: false,
    coverGradient: ['#0e0e1a', '#1a1a30'], accentColor: '#8b5cf6', icon: '⚡',
    collections: ['hyrox-collection', 'hyrox-wods', 'hybridhq-picks', 'most-popular'],
    days: {
      mon: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sat: {
        title: 'Station Gauntlet', badge: 'All 8 Stations', color: 'var(--accent-purple)',
        desc: 'All 8 HYROX stations completed back-to-back, no running between. For time.',
        runs: 'Rest',
        lifts: ['SkiErg 1000m', 'Sled Push 50m', 'Sled Pull 50m', 'Burpee Broad Jump 80m', 'Rowing 1000m', 'Farmers Carry 200m', 'Sandbag Lunges 100m', 'Wall Balls 100 reps'],
        workoutPreview: {
          type: 'HYROX',
          format: 'circuit',
          totalTime: '~25–45 min',
          notes: 'Complete all 8 stations in sequence with no rest between (except natural transition time). Use race weights for a true benchmark, or 70% weights for a conditioning focus.',
          stations: [
            { station: 'SkiErg — 1,000m',          weight: null,                               notes: 'Set a strong but sustainable pace' },
            { station: 'Sled Push — 50m',           weight: '152kg (M) / 102kg (F)' },
            { station: 'Sled Pull — 50m',           weight: '103kg (M) / 78kg (F)' },
            { station: 'Burpee Broad Jump — 80m',   weight: null,                               notes: 'Chest to floor every rep' },
            { station: 'Rowing — 1,000m',           weight: null,                               notes: 'Focus on consistent split times' },
            { station: 'Farmers Carry — 200m',      weight: '2×24kg (M) / 2×16kg (F)',         notes: 'Don\'t put down the handles' },
            { station: 'Sandbag Lunges — 100m',     weight: '20kg (M) / 10kg (F)',              notes: 'Alternate legs, keep torso upright' },
            { station: 'Wall Balls — 100 reps',     weight: '6kg/10ft (M) / 4kg/9ft (F)',      notes: 'Finish strong — this is the end line' },
          ],
        },
      },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: { '1': { sets: 1, reps: 1, intensityLabel: 'All stations — for time' } },
    dossier: { creator: 'HybridHQ', focus: 'HYROX Station Conditioning', philosophy: 'The gauntlet reveals exactly which stations are limiting your race time. Track your split at each transition and you will know exactly where to focus in training.' },
  },


];
