// @ts-check
// =============================================================================
// AUTO-GENERATED — split from catalog.js. Edit individual entries here.
// =============================================================================

export default [
  // ── RUNNING ───────────────────────────────────────────────────────────────

  {
    id: 'couch_to_5k',
    name: 'Couch to 5K',
    tagline: 'Go from the sofa to running 5K in 9 weeks',
    description: 'The world\'s most popular running program for absolute beginners. Gentle walk-run intervals progressively build your endurance until you can run 5K continuously. Used by millions worldwide to start their running journey.',
    author: { name: 'Josh Clark', type: 'coach', verified: true },
    category: 'running',
    subcategory: 'beginner',
    tags: ['beginner', 'running', '5k', 'walk-run', 'couch-to-5k', 'c25k', 'no-equipment', 'cardio'],
    durationWeeks: 9,
    sessionsPerWeek: 3,
    sessionDurationMinutes: { min: 20, max: 35 },
    difficulty: 'beginner',
    equipment: ['running-shoes'],
    equipmentTier: 'minimal',
    goals: ['run-5k', 'fitness', 'general-health', 'cardio'],
    metrics: { strengthEmphasis: 5, hypertrophyEmphasis: 5, enduranceEmphasis: 88, conditioningEmphasis: 60, recoveryDemand: 30, weeklyVolumeScore: 30 },
    highlights: ['Walk-run intervals', '9 weeks to 5K', 'Beginner-friendly', 'No equipment needed'],
    expectedOutcomes: ['Run 5K continuously', 'Running habit established', 'Improved cardio', 'Confidence to race'],
    popularity: 98, rating: 4.9, ratingCount: 5600, completionRate: 0.72, enrolledCount: 24000,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a1628', '#1e3a5f'], accentColor: '#22d3ee', icon: '🏃',
    collections: ['beginner-friendly', 'running-collection', 'most-popular', 'highest-rated', 'time-efficient'],
    days: {
      mon: { title: 'Run Session 1', badge: 'C25K', color: 'var(--accent-cyan)', desc: 'Walk-run intervals as per week schedule.', runs: '🏃 Walk/Run intervals — see week schedule', lifts: [] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest. Let your body adapt.', runs: 'Rest', lifts: [] },
      wed: { title: 'Run Session 2', badge: 'C25K', color: 'var(--accent-cyan)', desc: 'Walk-run intervals as per week schedule.', runs: '🏃 Walk/Run intervals — see week schedule', lifts: [] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Run Session 3', badge: 'C25K', color: 'var(--accent-cyan)', desc: 'Walk-run intervals as per week schedule.', runs: '🏃 Walk/Run intervals — see week schedule', lifts: [] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest or light walking.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 0, reps: 0, intensityLabel: 'Run 1min, Walk 1.5min × 8 reps' },
      '2': { sets: 0, reps: 0, intensityLabel: 'Run 1.5min, Walk 2min × 6 reps' },
      '3': { sets: 0, reps: 0, intensityLabel: 'Run 3min, Walk 1.5min / Run 5min, Walk 2.5min alternating' },
      '4': { sets: 0, reps: 0, intensityLabel: 'Run 5min, Walk 2.5min × 3 reps' },
      '5': { sets: 0, reps: 0, intensityLabel: 'Run 8min, Walk 5min / Run 20min continuous on Day 3' },
      '6': { sets: 0, reps: 0, intensityLabel: 'Run 25min continuous' },
      '7': { sets: 0, reps: 0, intensityLabel: 'Run 25min continuous' },
      '8': { sets: 0, reps: 0, intensityLabel: 'Run 28min continuous' },
      '9': { sets: 0, reps: 0, intensityLabel: 'Run 30min (approx 5K)' },
    },
    dossier: { creator: 'Josh Clark / NHS', focus: 'Beginner Running', philosophy: 'Gradual walk-run interval progression builds running capacity without injury risk.' },
  },

  {
    id: 'half_marathon_foundation',
    name: 'Half Marathon Foundation',
    tagline: 'Build to 21.1km from a solid running base',
    description: 'A 16-week program for runners with a 5K base who want to complete their first half marathon. Builds weekly mileage progressively with easy runs, tempo work, and long run development. Safe, structured, and proven.',
    author: { name: 'Helyx Running', type: 'official', verified: true },
    category: 'running',
    subcategory: 'race-prep',
    tags: ['half-marathon', 'running', 'race-prep', 'endurance', 'long-run', 'tempo', 'intermediate'],
    durationWeeks: 16,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 35, max: 120 },
    difficulty: 'intermediate',
    equipment: ['running-shoes'],
    equipmentTier: 'minimal',
    goals: ['half-marathon', 'race-completion', 'running-endurance'],
    metrics: { strengthEmphasis: 5, hypertrophyEmphasis: 5, enduranceEmphasis: 95, conditioningEmphasis: 50, recoveryDemand: 60, weeklyVolumeScore: 70 },
    highlights: ['16-week structured plan', 'Progressive long runs', 'Tempo + easy mix', 'Race week taper'],
    expectedOutcomes: ['Complete first half marathon', 'Build to 21.1km', 'Improved running economy', 'Race confidence'],
    popularity: 84, rating: 4.7, ratingCount: 892, completionRate: 0.68, enrolledCount: 5800,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a1628', '#1e3a5f'], accentColor: '#22d3ee', icon: '🏃',
    collections: ['running-collection', 'most-popular', 'highest-rated'],
    days: {
      mon: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest.', runs: 'Rest', lifts: [] },
      tue: { title: 'Easy Run', badge: 'Zone 2', color: 'var(--accent-cyan)', desc: 'Easy conversational pace.', runs: '🏃 Easy run — see week schedule', lifts: [] },
      wed: { title: 'Tempo Run', badge: 'Threshold', color: 'var(--accent-amber)', desc: 'Comfortably hard sustained effort.', runs: '🔥 Tempo intervals — see week schedule', lifts: [] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest or easy walk.', runs: 'Rest', lifts: [] },
      fri: { title: 'Easy Run', badge: 'Zone 2', color: 'var(--accent-cyan)', desc: 'Easy recovery run.', runs: '🏃 Easy run — see week schedule', lifts: [] },
      sat: { title: 'Long Run', badge: 'Endurance', color: 'var(--accent-pink)', desc: 'Progressive long run. Very easy pace.', runs: '🏃 Long run — see week schedule', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 0, reps: 0, intensityLabel: 'Long run: 12km | Weekly: ~30km' },
      '2': { sets: 0, reps: 0, intensityLabel: 'Long run: 13km | Weekly: ~32km' },
      '3': { sets: 0, reps: 0, intensityLabel: 'Long run: 15km | Weekly: ~35km' },
      '4': { sets: 0, reps: 0, intensityLabel: 'CUTBACK: Long run: 10km | Recovery week' },
      '5': { sets: 0, reps: 0, intensityLabel: 'Long run: 16km | Weekly: ~38km' },
      '6': { sets: 0, reps: 0, intensityLabel: 'Long run: 17km | Weekly: ~40km' },
      '7': { sets: 0, reps: 0, intensityLabel: 'Long run: 19km | Weekly: ~43km' },
      '8': { sets: 0, reps: 0, intensityLabel: 'CUTBACK: Long run: 13km | Recovery week' },
      '9': { sets: 0, reps: 0, intensityLabel: 'Long run: 19km | Weekly: ~43km' },
      '10': { sets: 0, reps: 0, intensityLabel: 'Long run: 21km | Weekly: ~46km' },
      '11': { sets: 0, reps: 0, intensityLabel: 'Long run: 21km | Weekly: ~46km' },
      '12': { sets: 0, reps: 0, intensityLabel: 'CUTBACK: Long run: 15km | Recovery' },
      '13': { sets: 0, reps: 0, intensityLabel: 'Long run: 21km | Weekly: ~45km' },
      '14': { sets: 0, reps: 0, intensityLabel: 'Long run: 19km | Taper begins' },
      '15': { sets: 0, reps: 0, intensityLabel: 'Long run: 15km | Taper' },
      '16': { sets: 0, reps: 0, intensityLabel: 'RACE WEEK: 21.1km race day' },
    },
    dossier: { creator: 'Helyx Running', focus: 'Half Marathon Preparation', philosophy: 'Gradual mileage build with strategic cutback weeks for safe adaptation and race day success.' },
  },

  {
    id: 'marathon_base_builder',
    name: 'Marathon Base Builder',
    tagline: 'Build the aerobic engine for 42.2km',
    description: 'An 18-week first marathon program for runners who can comfortably run 10K. Progressive mileage build with strategic cutback weeks, multiple long runs over 30km, and a structured 3-week taper into race day.',
    author: { name: 'Helyx Running', type: 'official', verified: true },
    category: 'running',
    subcategory: 'marathon',
    tags: ['marathon', 'running', 'race-prep', 'endurance', 'long-run', 'aerobic', 'advanced'],
    durationWeeks: 18,
    sessionsPerWeek: 5,
    sessionDurationMinutes: { min: 40, max: 180 },
    difficulty: 'advanced',
    equipment: ['running-shoes'],
    equipmentTier: 'minimal',
    goals: ['marathon', 'race-completion', 'endurance'],
    metrics: { strengthEmphasis: 5, hypertrophyEmphasis: 5, enduranceEmphasis: 98, conditioningEmphasis: 40, recoveryDemand: 75, weeklyVolumeScore: 85 },
    highlights: ['18-week full plan', '3-week structured taper', 'Multiple 30km+ long runs', 'Race day ready'],
    expectedOutcomes: ['Complete first marathon', 'Build to 42.2km', 'Strong aerobic base', 'Race confidence'],
    popularity: 76, rating: 4.7, ratingCount: 423, completionRate: 0.64, enrolledCount: 3100,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a1628', '#1e3a5f'], accentColor: '#06b6d4', icon: '🏃',
    collections: ['running-collection', 'endurance-collection'],
    days: {
      mon: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest.', runs: 'Rest', lifts: [] },
      tue: { title: 'Easy Run', badge: 'Zone 2', color: 'var(--accent-cyan)', desc: 'Easy conversational run.', runs: '🏃 Easy run — see week schedule', lifts: [] },
      wed: { title: 'Medium Run + Tempo', badge: 'Threshold', color: 'var(--accent-amber)', desc: 'Medium distance with tempo section.', runs: '🔥 Medium run with tempo — see week schedule', lifts: [] },
      thu: { title: 'Easy Run', badge: 'Zone 2', color: 'var(--accent-cyan)', desc: 'Easy recovery run.', runs: '🏃 Easy run — see week schedule', lifts: [] },
      fri: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sat: { title: 'Long Run', badge: 'Endurance', color: 'var(--accent-pink)', desc: 'Primary long run. Very easy pace.', runs: '🏃 Long run — see week schedule', lifts: [] },
      sun: { title: 'Easy Recovery Run', badge: 'Zone 2', color: 'var(--accent-cyan)', desc: 'Short easy run post long run.', runs: '🏃 20-30min very easy', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 0, reps: 0, intensityLabel: 'Long: 19km | Weekly: ~48km' },
      '2': { sets: 0, reps: 0, intensityLabel: 'Long: 21km | Weekly: ~51km' },
      '3': { sets: 0, reps: 0, intensityLabel: 'Long: 24km | Weekly: ~55km' },
      '4': { sets: 0, reps: 0, intensityLabel: 'CUTBACK: Long: 16km | Recovery' },
      '5': { sets: 0, reps: 0, intensityLabel: 'Long: 26km | Weekly: ~58km' },
      '6': { sets: 0, reps: 0, intensityLabel: 'Long: 27km | Weekly: ~61km' },
      '7': { sets: 0, reps: 0, intensityLabel: 'Long: 29km | Weekly: ~64km' },
      '8': { sets: 0, reps: 0, intensityLabel: 'CUTBACK: Long: 19km | Recovery' },
      '9': { sets: 0, reps: 0, intensityLabel: 'Long: 29km | Weekly: ~64km' },
      '10': { sets: 0, reps: 0, intensityLabel: 'Long: 32km | Weekly: ~68km' },
      '11': { sets: 0, reps: 0, intensityLabel: 'Long: 32km | Weekly: ~68km' },
      '12': { sets: 0, reps: 0, intensityLabel: 'CUTBACK: Long: 21km | Recovery' },
      '13': { sets: 0, reps: 0, intensityLabel: 'Long: 34km | Weekly: ~70km' },
      '14': { sets: 0, reps: 0, intensityLabel: 'Long: 32km | Weekly: ~67km' },
      '15': { sets: 0, reps: 0, intensityLabel: 'TAPER: Long: 27km | Weekly: ~55km' },
      '16': { sets: 0, reps: 0, intensityLabel: 'TAPER: Long: 21km | Weekly: ~44km' },
      '17': { sets: 0, reps: 0, intensityLabel: 'TAPER: Long: 16km | Weekly: ~35km' },
      '18': { sets: 0, reps: 0, intensityLabel: 'RACE WEEK: 42.2km race day' },
    },
    dossier: { creator: 'Helyx Running', focus: 'Marathon Preparation', philosophy: 'Safe aerobic mileage build with strategic cutback weeks and evidence-based taper for first marathon success.' },
  },
  // ── ENDURANCE ─────────────────────────────────────────────────────────────

  {
    id: 'zone2_foundation',
    name: 'Zone 2 Aerobic Foundation',
    tagline: 'Build your aerobic engine from the ground up',
    description: 'A 12-week program built entirely around Zone 2 heart rate training. Develop your mitochondrial density, fat oxidation, and aerobic efficiency through consistent easy effort work. The foundation all other training is built on.',
    author: { name: 'Helyx', type: 'official', verified: true },
    category: 'endurance',
    subcategory: 'zone2',
    tags: ['zone2', 'aerobic', 'endurance', 'heart-rate', 'easy', 'mitochondria', 'foundation', 'beginner'],
    durationWeeks: 12,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 30, max: 75 },
    difficulty: 'beginner',
    equipment: ['running-shoes'],
    equipmentTier: 'minimal',
    goals: ['aerobic-base', 'endurance', 'health', 'fat-adaptation'],
    metrics: { strengthEmphasis: 5, hypertrophyEmphasis: 5, enduranceEmphasis: 95, conditioningEmphasis: 30, recoveryDemand: 35, weeklyVolumeScore: 50 },
    highlights: ['Pure Zone 2 focus', 'Heart rate guided', 'Sustainable volume build', 'Foundation for everything'],
    expectedOutcomes: ['Improved aerobic efficiency', 'Lower resting HR', 'Better fat oxidation', 'Endurance base'],
    popularity: 72, rating: 4.5, ratingCount: 234, completionRate: 0.71, enrolledCount: 1800,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a2818', '#1a4731'], accentColor: '#10b981', icon: '🫀',
    collections: ['endurance-collection', 'beginner-friendly', 'time-efficient'],
    days: {
      mon: { title: 'Zone 2 Run', badge: 'Aerobic', color: 'var(--accent-green)', desc: 'Easy conversational run. HR 130-150bpm.', runs: '🏃 Zone 2 run — see week schedule', lifts: [] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Zone 2 Run', badge: 'Aerobic', color: 'var(--accent-green)', desc: 'Easy conversational run. HR 130-150bpm.', runs: '🏃 Zone 2 run — see week schedule', lifts: [] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest or light mobility.', runs: 'Rest', lifts: [] },
      fri: { title: 'Zone 2 Run', badge: 'Aerobic', color: 'var(--accent-green)', desc: 'Easy conversational run.', runs: '🏃 Zone 2 run — see week schedule', lifts: [] },
      sat: { title: 'Long Zone 2', badge: 'Long Aerobic', color: 'var(--accent-green)', desc: 'Longest run of the week. Very easy pace.', runs: '🏃 Long Zone 2 — see week schedule', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 0, reps: 0, intensityLabel: 'Long: 35min | 3 sessions × 25min' },
      '2': { sets: 0, reps: 0, intensityLabel: 'Long: 40min | 3 sessions × 28min' },
      '3': { sets: 0, reps: 0, intensityLabel: 'Long: 45min | 3 sessions × 30min' },
      '4': { sets: 0, reps: 0, intensityLabel: 'CUTBACK: Long: 30min | Recovery week' },
      '5': { sets: 0, reps: 0, intensityLabel: 'Long: 50min | 3 sessions × 32min' },
      '6': { sets: 0, reps: 0, intensityLabel: 'Long: 55min | 3 sessions × 35min' },
      '7': { sets: 0, reps: 0, intensityLabel: 'Long: 60min | 3 sessions × 38min' },
      '8': { sets: 0, reps: 0, intensityLabel: 'CUTBACK: Long: 40min | Recovery' },
      '9': { sets: 0, reps: 0, intensityLabel: 'Long: 65min | 3 sessions × 40min' },
      '10': { sets: 0, reps: 0, intensityLabel: 'Long: 70min | 3 sessions × 45min' },
      '11': { sets: 0, reps: 0, intensityLabel: 'Long: 75min | 3 sessions × 45min' },
      '12': { sets: 0, reps: 0, intensityLabel: 'Peak week — assess improvement' },
    },
    dossier: { creator: 'Helyx', focus: 'Aerobic Foundation', philosophy: 'Consistent Zone 2 training builds the mitochondrial base that powers all athletic performance.' },
  },
  // ── RUNNING — ADDITIONAL ──────────────────────────────────────────────────

  {
    id: 'ten_k_builder',
    name: '10K Builder',
    tagline: 'From casual runner to 10K finisher in 12 weeks',
    description: 'A structured 12-week plan that takes you from comfortable 5K running to completing — and eventually racing — a 10K. Three runs per week with a mix of easy aerobic miles, tempo efforts, and a weekly long run that peaks at 12K before race week.',
    author: { name: 'Helyx', type: 'official', verified: true },
    category: 'running',
    subcategory: '10k',
    tags: ['running', '10k', 'endurance', 'aerobic', 'beginner', 'race-prep', '10km', 'cardio'],
    durationWeeks: 12,
    sessionsPerWeek: 3,
    sessionDurationMinutes: { min: 30, max: 75 },
    difficulty: 'beginner',
    equipment: ['running-shoes'],
    equipmentTier: 'minimal',
    goals: ['complete-10k', 'endurance', 'running-base'],
    metrics: { strengthEmphasis: 5, hypertrophyEmphasis: 5, enduranceEmphasis: 95, conditioningEmphasis: 60, recoveryDemand: 35, weeklyVolumeScore: 40 },
    highlights: ['3 runs per week', 'Long run peaks at 12K', 'Tempo runs for speed', 'Race-week taper included'],
    expectedOutcomes: ['Complete your first 10K', 'Running confidence', 'Aerobic base developed', 'Race-day ready'],
    popularity: 80, rating: 4.7, ratingCount: 980, completionRate: 0.74, enrolledCount: 5600,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#001a10', '#00301a'], accentColor: '#10b981', icon: '🏃',
    collections: ['running-collection', 'beginner-friendly', 'most-popular'],
    days: {
      mon: { title: 'Easy Run', badge: 'Running', color: 'var(--accent-green)', desc: 'Easy aerobic pace — conversational.', runs: '🏃 30-45min easy run', lifts: [] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Tempo Run', badge: 'Running', color: 'var(--accent-amber)', desc: 'Comfortably hard — 10K race pace.', runs: '🏃 20-30min tempo effort', lifts: [] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sat: { title: 'Long Run', badge: 'Running', color: 'var(--accent-blue)', desc: 'Build your longest run of the week.', runs: '🏃 Long run (peaks 12K)', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 1, reps: 1, intensityLabel: 'Week 1: Easy 5K + 4K + 6K' },
      '2': { sets: 1, reps: 1, intensityLabel: 'Week 2: Easy 5K + 4K + 7K' },
      '3': { sets: 1, reps: 1, intensityLabel: 'Week 3: Easy 5K + Tempo 4K + 8K' },
      '4': { sets: 1, reps: 1, intensityLabel: 'Deload — shorter runs, full recovery' },
      '5': { sets: 1, reps: 1, intensityLabel: 'Week 5: Easy 6K + Tempo 5K + 9K' },
      '6': { sets: 1, reps: 1, intensityLabel: 'Week 6: Easy 6K + Tempo 5K + 10K' },
      '7': { sets: 1, reps: 1, intensityLabel: 'Week 7: Easy 6K + Tempo 6K + 11K' },
      '8': { sets: 1, reps: 1, intensityLabel: 'Deload — race pace sharpening' },
      '9': { sets: 1, reps: 1, intensityLabel: 'Week 9: Easy 7K + Tempo 6K + 12K' },
      '10': { sets: 1, reps: 1, intensityLabel: 'Week 10: Build confidence — big long run' },
      '11': { sets: 1, reps: 1, intensityLabel: 'Taper — reduce mileage 30%' },
      '12': { sets: 1, reps: 1, intensityLabel: 'Race week — short shakeout runs' },
    },
    dossier: { creator: 'Helyx', focus: '10K Training', philosophy: 'Consistent aerobic mileage with structured tempo efforts builds the engine needed to run 10K comfortably and confidently.' },
  },

  {
    id: 'sub_20_5k',
    name: 'Sub-20 5K Plan',
    tagline: 'Break the 20-minute barrier with structured speed training',
    description: 'An 8-week speed-focused plan to crack sub-20 minutes for 5K. This plan assumes you can already run sub-25 minutes and focuses on VO2 max intervals, tempo runs at 4:00/km pace, and race-specific preparation. One of the most satisfying running milestones.',
    author: { name: 'Helyx', type: 'official', verified: true },
    category: 'running',
    subcategory: '5k',
    tags: ['running', '5k', 'speed', 'sub-20', 'intervals', 'vo2max', 'race-prep', 'advanced-running', 'parkrun'],
    durationWeeks: 8,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 35, max: 70 },
    difficulty: 'intermediate',
    equipment: ['running-shoes'],
    equipmentTier: 'minimal',
    goals: ['sub-20-5k', 'speed', 'vo2max', 'race-pb'],
    metrics: { strengthEmphasis: 5, hypertrophyEmphasis: 5, enduranceEmphasis: 90, conditioningEmphasis: 85, recoveryDemand: 60, weeklyVolumeScore: 55 },
    highlights: ['VO2 max interval sessions', 'Threshold tempo runs', 'Sub-20 race pacing strategy', '4:00/km pace work'],
    expectedOutcomes: ['Sub-20 min 5K', 'Improved VO2 max', 'Race confidence', 'PB by multiple minutes'],
    popularity: 82, rating: 4.8, ratingCount: 620, completionRate: 0.68, enrolledCount: 3900,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#001a10', '#00301a'], accentColor: '#22d3ee', icon: '⚡',
    collections: ['running-collection', 'most-popular', 'new-programs'],
    days: {
      mon: { title: 'Easy Recovery Run', badge: 'Running', color: 'var(--accent-green)', desc: 'Easy pace — active recovery.', runs: '🏃 30min easy run', lifts: [] },
      tue: { title: 'VO2 Max Intervals', badge: 'Speed', color: 'var(--accent-blue)', desc: '400m repeats at max effort.', runs: '🔥 8×400m @ 1:45-1:50 pace + warm-up/cool-down', lifts: [] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: { title: 'Tempo Run', badge: 'Speed', color: 'var(--accent-amber)', desc: '4:00/km sustained effort.', runs: '🏃 Warm-up + 20-25min @ 4:00/km + cool-down', lifts: [] },
      fri: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sat: { title: 'Parkrun / Race Sim', badge: 'Race', color: 'var(--accent-pink)', desc: 'Race or race simulation.', runs: '🏅 5K at goal race pace', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 1, reps: 1, intensityLabel: 'Week 1: Establish 5K benchmark — where are you now?' },
      '2': { sets: 1, reps: 1, intensityLabel: 'Week 2: 6×400m intervals + Tempo 20min' },
      '3': { sets: 1, reps: 1, intensityLabel: 'Week 3: 8×400m intervals + Tempo 22min' },
      '4': { sets: 1, reps: 1, intensityLabel: 'Deload — 4×400m light + easy run' },
      '5': { sets: 1, reps: 1, intensityLabel: 'Week 5: 10×400m intervals + Tempo 25min' },
      '6': { sets: 1, reps: 1, intensityLabel: 'Week 6: 6×800m intervals + Tempo 22min' },
      '7': { sets: 1, reps: 1, intensityLabel: 'Taper — reduce volume, keep intensity' },
      '8': { sets: 1, reps: 1, intensityLabel: 'Race week — sub-20 attempt' },
    },
    dossier: { creator: 'Helyx', focus: 'Sub-20 5K', philosophy: 'Breaking 20 minutes requires training at and above race pace. Intervals push your ceiling; tempo runs lower your floor.' },
  },
  // ── RUNNING ───────────────────────────────────────────────────────────────────

  {
    id: 'couch_to_5k',
    name: 'Couch to 5K',
    tagline: 'From your first steps to your first 5K finish line',
    description: 'The classic 9-week run/walk programme that has helped millions of people run their first 5K. Alternates running and walking intervals with a progressive weekly build — the intervals get longer and the walks get shorter until you run the whole thing. Beginner-proof and endlessly effective.',
    author: { name: 'Josh Clark', type: 'community', verified: true },
    source: 'community',
    category: 'running',
    subcategory: 'beginner',
    tags: ['couch-to-5k', 'c25k', 'beginner', 'running', '5k', '9-week', 'run-walk', 'first-run', 'starter'],
    durationWeeks: 9,
    sessionsPerWeek: 3,
    sessionDurationMinutes: { min: 30, max: 40 },
    difficulty: 'beginner',
    equipment: [],
    equipmentTier: 'bodyweight',
    goals: ['run-5k', 'fitness', 'aerobic-base', 'beginner-running'],
    metrics: { strengthEmphasis: 0, hypertrophyEmphasis: 0, enduranceEmphasis: 80, conditioningEmphasis: 40, recoveryDemand: 25, weeklyVolumeScore: 30 },
    highlights: ['Perfect for non-runners', 'Run/walk interval structure', 'Scales week by week', 'Only 30–40 min per session'],
    expectedOutcomes: ['Complete a continuous 5K run', 'Aerobic fitness base', 'Sustainable running habit', 'Confidence on the road'],
    popularity: 92, rating: 4.9, ratingCount: 3456, completionRate: 0.75, enrolledCount: 18400,
    featured: true, verified: true, isNew: false,
    coverGradient: ['#0a1020', '#0d2435'], accentColor: '#22d3ee', icon: '🏃',
    collections: ['running-collection', 'beginner-friendly', 'most-popular', 'highest-rated'],
    days: {
      mon: {
        title: 'Run Session', badge: 'C25K', color: 'var(--accent-pink)',
        desc: 'Run/walk intervals — progressive each week.', runs: '🏃 Week 1: 8×60sec run / 90sec walk (20 min total)',
        lifts: [],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Brisk Walk',     type: 'warmup',  duration: '5 min',              pace: 'Brisk walking pace',          description: 'Fast walking warm-up — get your heart rate up before the first run' },
            { name: 'Run/Walk',       type: 'mainSet', duration: '20 min (8 intervals)', pace: 'Easy to moderate run',       description: 'Week 1: 8 sets of 60 sec run / 90 sec walk. Week 5: 5 min run / 3 min walk ×3. Week 9: 30 min continuous run.', notes: 'Each week the runs get longer and the walks get shorter. Trust the process.' },
            { name: 'Cool-Down Walk', type: 'cooldown', duration: '5 min',             pace: 'Easy walking',                description: 'Slow walk back to resting heart rate + calf and quad stretch' },
          ],
        },
      },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day.', runs: 'Rest', lifts: [] },
      wed: {
        title: 'Run Session', badge: 'C25K', color: 'var(--accent-pink)',
        desc: 'Second run session — same structure as Monday.', runs: '🏃 Repeat Monday\'s session',
        lifts: [],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Brisk Walk', type: 'warmup',  duration: '5 min',   pace: 'Brisk',         description: 'Same warm-up as Monday' },
            { name: 'Run/Walk',   type: 'mainSet', duration: '20 min',  pace: 'Easy to moderate', description: 'Repeat this week\'s interval pattern. Focus on controlled breathing.', notes: 'If Monday felt very hard, repeat it without guilt — your body is adapting' },
            { name: 'Cool-Down',  type: 'cooldown', duration: '5 min', pace: 'Easy walking',   description: 'Cool-down walk + light stretching' },
          ],
        },
      },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day.', runs: 'Rest', lifts: [] },
      fri: {
        title: 'Run Session (Long)', badge: 'C25K', color: 'var(--accent-pink)',
        desc: 'Third run — longest session of the week. End-of-week effort.', runs: '🏃 Repeat this week\'s session',
        lifts: [],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Brisk Walk', type: 'warmup',  duration: '5 min',  pace: 'Brisk',           description: 'Same warm-up' },
            { name: 'Run/Walk',   type: 'mainSet', duration: '20 min', pace: 'Controlled effort', description: 'Final session of the week. Finish strong. Next week the intervals get longer.', notes: 'By week 5 this session becomes a 20-min continuous run. By week 9 — 30 min continuous.' },
            { name: 'Cool-Down',  type: 'cooldown', duration: '5 min', pace: 'Easy',             description: 'Cool-down walk' },
          ],
        },
      },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 1, reps: 8, intensityLabel: 'Week 1: 8×(60sec run / 90sec walk)' },
      '2': { sets: 1, reps: 6, intensityLabel: 'Week 2: 6×(90sec run / 2min walk)' },
      '3': { sets: 1, reps: 4, intensityLabel: 'Week 3: 2×(90sec run/90sec walk/3min run/3min walk)' },
      '4': { sets: 1, reps: 3, intensityLabel: 'Week 4: 3×(3min run/90sec walk/5min run/2.5min walk)' },
      '5': { sets: 1, reps: 3, intensityLabel: 'Week 5: 5min/8min/5min runs with walk breaks' },
      '6': { sets: 1, reps: 2, intensityLabel: 'Week 6: 5min/10min/5min + one 20-min run' },
      '7': { sets: 1, reps: 1, intensityLabel: 'Week 7: 25 min continuous run' },
      '8': { sets: 1, reps: 1, intensityLabel: 'Week 8: 28 min continuous run' },
      '9': { sets: 1, reps: 1, intensityLabel: 'Week 9: 30 min continuous run — YOU DID IT' },
    },
    dossier: { creator: 'Josh Clark / NHS adaptation', focus: 'Beginner Running', philosophy: 'Everyone who runs was once someone who could not run at all. The intervals get you there without destroying you in the process.' },
  },

  {
    id: 'half_marathon_builder',
    name: 'Half Marathon Builder',
    tagline: '12 weeks to your best half marathon',
    description: 'A 12-week half marathon training plan for runners with an existing 5K base. Builds your weekly mileage systematically through zone 2 long runs, tempo efforts, and structured interval sessions. Includes two deload weeks and a race-week taper protocol.',
    author: { name: 'Helyx', type: 'official', verified: true },
    source: 'internal',
    category: 'running',
    subcategory: 'half-marathon',
    tags: ['half-marathon', '21k', 'running', 'intermediate', '12-week', 'tempo', 'intervals', 'long-run', 'race-prep'],
    durationWeeks: 12,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 35, max: 100 },
    difficulty: 'intermediate',
    equipment: [],
    equipmentTier: 'bodyweight',
    goals: ['half-marathon', 'running-performance', 'endurance', 'race-completion'],
    metrics: { strengthEmphasis: 0, hypertrophyEmphasis: 0, enduranceEmphasis: 95, conditioningEmphasis: 65, recoveryDemand: 60, weeklyVolumeScore: 75 },
    highlights: ['4 run days per week', 'Zone 2 long run progression', 'Tempo + interval work', 'Structured deload + taper'],
    expectedOutcomes: ['Complete a half marathon', 'Improved aerobic threshold', 'Faster running economy', 'Race-day confidence'],
    popularity: 81, rating: 4.7, ratingCount: 678, completionRate: 0.62, enrolledCount: 4200,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#0a1020', '#0d1f35'], accentColor: '#22d3ee', icon: '🏃',
    collections: ['running-collection', 'endurance-collection', 'most-popular'],
    days: {
      mon: {
        title: 'Easy Recovery Run', badge: 'Zone 2', color: 'var(--accent-green)',
        desc: 'Easy aerobic recovery run at conversational pace.', runs: '🏃 30–40min Zone 2 easy run',
        lifts: [],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Easy Run', type: 'mainSet', duration: '30–40 min', pace: 'Zone 2 — conversational', description: 'Relaxed, easy effort. If you cannot hold a full conversation, slow down.', notes: 'This run is about active recovery and aerobic base. Resist the urge to push.' },
            { name: 'Stretch',  type: 'cooldown', duration: '5 min',   pace: '—', description: 'Calf, quad, hip flexor and hamstring stretch' },
          ],
        },
      },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest day.', runs: 'Rest', lifts: [] },
      wed: {
        title: 'Tempo Run', badge: 'Threshold', color: 'var(--accent-amber)',
        desc: 'Sustained threshold effort — comfortably hard.', runs: '🔥 Tempo: 20–35min @ threshold pace',
        lifts: [],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Warm-Up',   type: 'warmup',  duration: '10–15 min',  pace: 'Zone 1–2 (easy jog)', description: 'Easy jog to warm up — include 4×20 sec strides at the end' },
            { name: 'Tempo',     type: 'mainSet', duration: '20–35 min',  pace: 'Threshold (RPE 7–8)',  description: 'Continuous run at lactate threshold pace — comfortably hard, not all-out', notes: 'Week 1-3: 20 min. Week 4-7: 25-30 min. Week 8-10: 35 min. No threshold on deload weeks.' },
            { name: 'Cool-Down', type: 'cooldown', duration: '10 min',   pace: 'Zone 1 (very easy)',   description: 'Easy jog reducing to walk — flush the lactate out' },
          ],
        },
      },
      thu: {
        title: 'Intervals', badge: 'Speed', color: 'var(--accent-pink)',
        desc: 'Interval training to develop running economy and VO2max.', runs: '⚡ 6×800m @ 5K race pace (90sec recovery)',
        lifts: [],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Warm-Up',   type: 'warmup',  duration: '15 min',  pace: 'Easy jog + drills', description: 'Easy jog + leg swings, high knees, butt kicks, 4×100m strides' },
            { name: 'Intervals', type: 'mainSet', duration: '6×800m',  pace: '5K race pace',      description: '800m reps at your target 5K pace with 90 sec walk/jog recovery between each', notes: 'Progression: Weeks 1-4: 4×800m. Weeks 5-8: 6×800m. Weeks 9-10: 4×1km.' },
            { name: 'Cool-Down', type: 'cooldown', duration: '10 min', pace: 'Easy jog to walk',  description: 'Easy jog decreasing to walk — full leg stretch' },
          ],
        },
      },
      fri: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day.', runs: 'Rest', lifts: [] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day — saving energy for long run tomorrow.', runs: 'Rest', lifts: [] },
      sun: {
        title: 'Long Run', badge: 'Key Session', color: 'var(--accent-green)',
        desc: 'Weekly long run — the cornerstone of half marathon training.', runs: '🏃 Zone 2 long run (progressive)',
        lifts: [],
        workoutPreview: {
          type: 'RUNNING',
          phases: [
            { name: 'Warm-Up',   type: 'warmup',  duration: '5 min',     pace: 'Easy jog',              description: 'Gentle warm-up before the long haul' },
            { name: 'Long Run',  type: 'mainSet', duration: 'Progressive', pace: 'Zone 2 — conversational', description: 'Week 1: 10km. Week 3: 13km. Week 6: 16km. Week 9: 19km. Week 11: 13km (taper). Week 12: Race day!', notes: 'The long run builds your aerobic base and mental fortitude. Eat and drink on anything over 75 min.' },
            { name: 'Cool-Down', type: 'cooldown', duration: '5 min',    pace: 'Walk',                   description: 'Walk + extensive leg stretch. Refuel within 30 minutes.' },
          ],
        },
      },
    },
    weeklyVolModifiers: {
      '1': { sets: 1, reps: 10, intensityLabel: 'Base build — 10km long run' }, '2': { sets: 1, reps: 12, intensityLabel: 'Base build — 12km long run' },
      '3': { sets: 1, reps: 13, intensityLabel: 'Build — 13km long run' }, '4': { sets: 1, reps: 8, intensityLabel: 'Deload — 8km long run' },
      '5': { sets: 1, reps: 14, intensityLabel: 'Build — 14km long run' }, '6': { sets: 1, reps: 16, intensityLabel: 'Build — 16km long run' },
      '7': { sets: 1, reps: 17, intensityLabel: 'Peak build — 17km' }, '8': { sets: 1, reps: 10, intensityLabel: 'Deload — 10km' },
      '9': { sets: 1, reps: 19, intensityLabel: 'Peak — 19km long run' }, '10': { sets: 1, reps: 18, intensityLabel: 'Peak — 18km long run' },
      '11': { sets: 1, reps: 13, intensityLabel: 'Taper — 13km long run' }, '12': { sets: 1, reps: 21, intensityLabel: 'RACE DAY — 21.1km' },
    },
    dossier: { creator: 'Helyx', focus: 'Half Marathon', philosophy: 'The long run is king. Build it slowly, respect the recovery, and show up on race day with miles in the legs and confidence in the mind.' },
  },

];
