// @ts-check
// =============================================================================
// AUTO-GENERATED — split from catalog.js. Edit individual entries here.
// =============================================================================

export default [
  // ── STRENGTH ──────────────────────────────────────────────────────────────

  {
    id: 'stronglifts_5x5',
    name: 'StrongLifts 5×5',
    tagline: 'The internet\'s most popular beginner strength program',
    description: 'The simplest effective strength program ever created. Three days per week, two alternating sessions, five core barbell movements. Linear progression on every session. Perfect for beginners building their first real base of strength.',
    author: { name: 'Mehdi (StrongLifts)', type: 'coach', verified: true },
    category: 'strength',
    subcategory: 'linear-progression',
    tags: ['beginner', 'strength', '5x5', 'barbell', 'linear-progression', 'simple', 'compound'],
    durationWeeks: 12,
    sessionsPerWeek: 3,
    sessionDurationMinutes: { min: 30, max: 50 },
    difficulty: 'beginner',
    equipment: ['barbell', 'rack', 'bench'],
    equipmentTier: 'gym',
    goals: ['strength', 'beginner-gains', 'barbell-fundamentals'],
    metrics: { strengthEmphasis: 95, hypertrophyEmphasis: 40, enduranceEmphasis: 5, conditioningEmphasis: 5, recoveryDemand: 45, weeklyVolumeScore: 40 },
    highlights: ['3 days/week only', 'Linear progression every session', '5 movements mastered', 'Beginner-perfect'],
    expectedOutcomes: ['Rapid strength gains', 'Barbell technique mastered', 'Squat/Bench/Deadlift PRs', 'Confidence in the gym'],
    popularity: 97, rating: 4.8, ratingCount: 2140, completionRate: 0.58, enrolledCount: 9800,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0a0a', '#3d1515'], accentColor: '#ef4444', icon: '🏋️',
    collections: ['most-popular', 'beginner-friendly', 'strength-collection', 'highest-rated'],
    days: {
      mon: { title: 'Workout A', badge: 'SL 5x5', color: 'var(--accent-blue)', desc: 'Squat + Bench Press + Barbell Row. 5×5 across.', runs: 'Rest', lifts: ['Back Squat', 'Bench Press', 'Barbell Row'] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Workout B', badge: 'SL 5x5', color: 'var(--accent-green)', desc: 'Squat + OHP + Deadlift. 5×5 on Squat/OHP, 1×5 Deadlift.', runs: 'Rest', lifts: ['Back Squat', 'Standing OHP', 'Deadlift'] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Workout A', badge: 'SL 5x5', color: 'var(--accent-blue)', desc: 'Squat + Bench Press + Barbell Row. 5×5 across.', runs: 'Rest', lifts: ['Back Squat', 'Bench Press', 'Barbell Row'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 5, reps: 5, intensityLabel: 'Linear Progression — add 2.5kg each session' },
      '2': { sets: 5, reps: 5, intensityLabel: 'Linear Progression — add 2.5kg each session' },
      '3': { sets: 5, reps: 5, intensityLabel: 'Linear Progression — add 2.5kg each session' },
      '4': { sets: 5, reps: 5, intensityLabel: 'Linear Progression — add 2.5kg each session' },
      '5': { sets: 5, reps: 5, intensityLabel: 'Linear Progression — add 2.5kg each session' },
      '6': { sets: 5, reps: 5, intensityLabel: 'Deload if stalling — reset 10%' },
      '7': { sets: 5, reps: 5, intensityLabel: 'Linear Progression continues' },
      '8': { sets: 5, reps: 5, intensityLabel: 'Linear Progression continues' },
      '9': { sets: 5, reps: 5, intensityLabel: 'Linear Progression continues' },
      '10': { sets: 5, reps: 5, intensityLabel: 'Linear Progression continues' },
      '11': { sets: 5, reps: 5, intensityLabel: 'Final push block' },
      '12': { sets: 5, reps: 5, intensityLabel: 'Peak week — test maxes' },
    },
    dossier: { creator: 'Mehdi (StrongLifts)', focus: 'Beginner Strength', philosophy: 'Simple is effective. Master the squat, bench, deadlift, row, and OHP with linear progression every session.' },
  },

  {
    id: 'nsuns_531',
    name: 'nSuns 5/3/1 (4-Day)',
    tagline: 'The hardest 5/3/1 variant ever programmed',
    description: 'Not for the faint of heart. nSuns uses a demanding 9-set progression scheme for main lifts based on Jim Wendler\'s 5/3/1 math. Forces rapid strength adaptation through sheer volume and heavy loads across 4 brutal days.',
    author: { name: 'nSuns', type: 'community', verified: true },
    category: 'strength',
    subcategory: 'powerlifting-style',
    tags: ['531', 'nsuns', 'strength', 'powerlifting', 'volume', 'advanced', 'barbell', 'intermediate'],
    durationWeeks: 12,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 75, max: 100 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells'],
    equipmentTier: 'gym',
    goals: ['strength', 'powerlifting-total', 'main-lift-prs'],
    metrics: { strengthEmphasis: 92, hypertrophyEmphasis: 45, enduranceEmphasis: 5, conditioningEmphasis: 10, recoveryDemand: 80, weeklyVolumeScore: 85 },
    highlights: ['9-set main lift scheme', '5/3/1 progression system', '4 days/week', 'Rapid strength gains'],
    expectedOutcomes: ['Significant strength PRs', 'Improved power output', 'Dense muscle mass', 'Competition readiness'],
    popularity: 90, rating: 4.7, ratingCount: 834, completionRate: 0.42, enrolledCount: 5600,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0a0a', '#2d0a0a'], accentColor: '#ef4444', icon: '🏋️',
    collections: ['strength-collection', 'most-popular', 'highest-rated'],
  },

  {
    id: 'gzclp',
    name: 'GZCLP',
    tagline: 'The most intelligent beginner program on the internet',
    description: 'GZCL\'s tiered progression system adapted for beginners. Three tiers of exercises with different set/rep schemes create a self-regulating program that responds to your actual performance rather than a fixed schedule.',
    author: { name: 'Cody Lefever (GZCL)', type: 'coach', verified: true },
    category: 'strength',
    subcategory: 'linear-progression',
    tags: ['gzcl', 'beginner', 'strength', 'tiered', 'intelligent', 'barbell', 'progression'],
    durationWeeks: 16,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 50, max: 70 },
    difficulty: 'beginner',
    equipment: ['barbell', 'rack', 'bench', 'dumbbells'],
    equipmentTier: 'gym',
    goals: ['strength', 'beginner-gains', 'barbell-fundamentals'],
    metrics: { strengthEmphasis: 88, hypertrophyEmphasis: 55, enduranceEmphasis: 5, conditioningEmphasis: 5, recoveryDemand: 55, weeklyVolumeScore: 65 },
    highlights: ['Self-regulating progression', 'Intelligent tier system', '4 days/week', 'Beginner-perfect'],
    expectedOutcomes: ['Strong linear gains', 'Barbell movement mastery', 'Solid strength base', 'Understanding of training'],
    popularity: 84, rating: 4.6, ratingCount: 612, completionRate: 0.62, enrolledCount: 4200,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0a0a', '#3d1515'], accentColor: '#f97316', icon: '🏋️',
    collections: ['beginner-friendly', 'strength-collection', 'most-popular'],
    days: {
      mon: { title: 'T1 Squat Day', badge: 'GZCLP', color: 'var(--accent-green)', desc: 'T1: Back Squat 5×3+. T2: OHP 3×10. T3 accessories.', runs: 'Rest', lifts: ['Back Squat', 'Standing OHP', 'Lat Pulldown', 'Lateral Raise', 'Tricep Band Pushdown'] },
      tue: { title: 'T1 Bench Day', badge: 'GZCLP', color: 'var(--accent-blue)', desc: 'T1: Bench Press 5×3+. T2: Deadlift 3×8. T3 accessories.', runs: 'Rest', lifts: ['Bench Press', 'Deadlift', 'Barbell Row', 'Hammer Curl', 'Core/Plank'] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day.', runs: 'Rest', lifts: [] },
      thu: { title: 'T1 Squat Day B', badge: 'GZCLP', color: 'var(--accent-green)', desc: 'T1: Squat. T2: OHP. T3: Accessories.', runs: 'Rest', lifts: ['Back Squat', 'Standing OHP', 'Pull-Ups', 'Lateral Raise', 'Ab Wheel Rollouts'] },
      fri: { title: 'T1 Bench Day B', badge: 'GZCLP', color: 'var(--accent-blue)', desc: 'T1: Bench. T2: Deadlift. T3 accessories.', runs: 'Rest', lifts: ['Bench Press', 'Deadlift', 'Chin-Ups', 'Barbell Curl', 'Hanging Leg Raises'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 5, reps: 3, intensityLabel: 'T1: 5×3+ (AMRAP last set)' },
      '2': { sets: 5, reps: 3, intensityLabel: 'T1: 5×3+ (AMRAP last set)' },
      '3': { sets: 5, reps: 3, intensityLabel: 'T1: 5×3+ (AMRAP last set)' },
      '4': { sets: 5, reps: 3, intensityLabel: 'T1: 5×3+ (AMRAP last set)' },
      '5': { sets: 6, reps: 2, intensityLabel: 'T1 advancement: 6×2+' },
      '6': { sets: 6, reps: 2, intensityLabel: 'T1: 6×2+ (AMRAP last set)' },
      '7': { sets: 6, reps: 2, intensityLabel: 'T1: 6×2+' },
      '8': { sets: 6, reps: 2, intensityLabel: 'T1: 6×2+' },
      '9': { sets: 10, reps: 1, intensityLabel: 'T1 advancement: 10×1+' },
      '10': { sets: 10, reps: 1, intensityLabel: 'T1: 10×1+' },
      '11': { sets: 10, reps: 1, intensityLabel: 'T1: 10×1+' },
      '12': { sets: 10, reps: 1, intensityLabel: 'T1: 10×1+' },
      '13': { sets: 5, reps: 3, intensityLabel: 'Cycle 2 begins at new weight' },
      '14': { sets: 5, reps: 3, intensityLabel: 'Cycle 2' },
      '15': { sets: 6, reps: 2, intensityLabel: 'Cycle 2 advancement' },
      '16': { sets: 6, reps: 2, intensityLabel: 'Cycle 2 peak' },
    },
    dossier: { creator: 'Cody Lefever (GZCL)', focus: 'Beginner Strength', philosophy: 'Tiered training where T1 compounds drive strength, T2 builds volume, and T3 targets weaknesses.' },
  },

  {
    id: 'texas_method',
    name: 'Texas Method',
    tagline: 'Volume Monday, Recovery Wednesday, Intensity Friday',
    description: 'A classic intermediate strength program using a three-day weekly template. Monday accumulates volume, Wednesday promotes recovery, and Friday tests intensity with heavy singles and triples. Perfect for lifters who have exhausted linear progression.',
    author: { name: 'Mark Rippetoe', type: 'coach', verified: true },
    category: 'strength',
    subcategory: 'intermediate',
    tags: ['texas-method', 'intermediate', 'strength', 'barbell', 'volume-intensity', '5x5', 'classic'],
    durationWeeks: 12,
    sessionsPerWeek: 3,
    sessionDurationMinutes: { min: 60, max: 90 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack', 'bench'],
    equipmentTier: 'gym',
    goals: ['strength', 'intermediate-progression', 'powerlifting-base'],
    metrics: { strengthEmphasis: 90, hypertrophyEmphasis: 35, enduranceEmphasis: 5, conditioningEmphasis: 5, recoveryDemand: 65, weeklyVolumeScore: 60 },
    highlights: ['Classic V/R/I template', 'Weekly PRs possible', '3 days/week', 'Intermediate bridge'],
    expectedOutcomes: ['Break through plateaus', 'Weekly strength PRs', 'Solid powerlifting base', 'Improved 1RM'],
    popularity: 78, rating: 4.5, ratingCount: 389, completionRate: 0.52, enrolledCount: 2800,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0a0a', '#3d1515'], accentColor: '#dc2626', icon: '🏋️',
    collections: ['strength-collection', 'most-popular'],
    days: {
      mon: { title: 'Volume Day', badge: 'Texas Method', color: 'var(--accent-blue)', desc: '5×5 at 90% of Friday weight. High volume.', runs: 'Rest', lifts: ['Back Squat', 'Bench Press', 'Deadlift'] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Recovery Day', badge: 'Texas Method', color: 'var(--accent-green)', desc: 'Light squats, OHP, and chin-ups. 80% intensity.', runs: 'Rest', lifts: ['Back Squat', 'Standing OHP', 'Chin-Ups'] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Intensity Day', badge: 'Texas Method', color: 'var(--accent-amber)', desc: '1×5 PR attempt. Heavy singles. Test your strength.', runs: 'Rest', lifts: ['Back Squat', 'Bench Press', 'Deadlift', 'Barbell Row'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 5, reps: 5, intensityLabel: 'Volume: 5×5 / Intensity: 1×5 PR' },
      '2': { sets: 5, reps: 5, intensityLabel: 'Volume: 5×5 / Intensity: 1×5 PR' },
      '3': { sets: 5, reps: 5, intensityLabel: 'Volume: 5×5 / Intensity: 1×5 PR' },
      '4': { sets: 5, reps: 5, intensityLabel: 'Volume: 5×5 / Intensity: 1×5 PR' },
      '5': { sets: 5, reps: 5, intensityLabel: 'Volume: 5×5 / Intensity: 1×5 PR' },
      '6': { sets: 5, reps: 5, intensityLabel: 'Deload if stalling' },
      '7': { sets: 5, reps: 5, intensityLabel: 'Texas Method continues' },
      '8': { sets: 5, reps: 5, intensityLabel: 'Texas Method continues' },
      '9': { sets: 5, reps: 5, intensityLabel: 'Texas Method continues' },
      '10': { sets: 5, reps: 5, intensityLabel: 'Texas Method continues' },
      '11': { sets: 5, reps: 5, intensityLabel: 'Final push' },
      '12': { sets: 5, reps: 5, intensityLabel: 'Peak' },
    },
    dossier: { creator: 'Mark Rippetoe', focus: 'Intermediate Strength', philosophy: 'Weekly periodisation — volume on Monday, recovery on Wednesday, intensity on Friday.' },
  },

  {
    id: 'candito_6_week',
    name: 'Candito 6-Week Strength',
    tagline: 'Six weeks to a new strength PR',
    description: 'Jonnie Candito\'s legendary 6-week peaking program. Builds volume, transitions to intensity, then peaks with heavy triples and singles. One of the most effective short-term strength programs ever designed.',
    author: { name: 'Jonnie Candito', type: 'coach', verified: true },
    category: 'strength',
    subcategory: 'peaking',
    tags: ['candito', 'strength', 'peaking', '6-week', 'powerlifting', 'PR', 'advanced'],
    durationWeeks: 6,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 60, max: 90 },
    difficulty: 'advanced',
    equipment: ['barbell', 'rack', 'bench'],
    equipmentTier: 'gym',
    goals: ['strength-pr', 'peaking', 'powerlifting'],
    metrics: { strengthEmphasis: 95, hypertrophyEmphasis: 25, enduranceEmphasis: 5, conditioningEmphasis: 5, recoveryDemand: 75, weeklyVolumeScore: 70 },
    highlights: ['6-week peaking protocol', 'Strategic volume to intensity', 'Proven PR system', 'Deload + peak structure'],
    expectedOutcomes: ['New strength PRs', 'Competition readiness', 'Optimised strength expression', 'PR on all main lifts'],
    popularity: 85, rating: 4.8, ratingCount: 567, completionRate: 0.60, enrolledCount: 3400,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0a0a', '#2d0a0a'], accentColor: '#ef4444', icon: '🔱',
    collections: ['strength-collection', 'highest-rated'],
    days: {
      mon: { title: 'Upper Hypertrophy', badge: 'Candito', color: 'var(--accent-blue)', desc: 'Volume upper body work.', runs: 'Rest', lifts: ['Bench Press', 'Barbell Row', 'Incline DB Press', 'Lateral Raise', 'Tricep Band Pushdown'] },
      tue: { title: 'Lower Hypertrophy', badge: 'Candito', color: 'var(--accent-green)', desc: 'Volume lower body work.', runs: 'Rest', lifts: ['Back Squat', 'Romanian Deadlift', 'Bulgarian Split Squat', 'Leg Press'] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: { title: 'Bench Intensity', badge: 'Candito', color: 'var(--accent-blue)', desc: 'Heavy bench + OHP accessory.', runs: 'Rest', lifts: ['Bench Press', 'Standing OHP', 'Barbell Row'] },
      fri: { title: 'Squat + Deadlift', badge: 'Candito', color: 'var(--accent-green)', desc: 'Heavy squat + deadlift.', runs: 'Rest', lifts: ['Back Squat', 'Deadlift'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 4, reps: 10, intensityLabel: 'Week 1-2: Hypertrophy Phase' },
      '2': { sets: 4, reps: 8, intensityLabel: 'Week 1-2: Hypertrophy Phase' },
      '3': { sets: 4, reps: 6, intensityLabel: 'Week 3-4: Strength Phase (70-85%)' },
      '4': { sets: 4, reps: 4, intensityLabel: 'Week 3-4: Strength Phase (80-90%)' },
      '5': { sets: 3, reps: 3, intensityLabel: 'Week 5: Heavy (85-95%) — Reduce volume' },
      '6': { sets: 1, reps: 1, intensityLabel: 'Week 6: Peak + PR Test' },
    },
    dossier: { creator: 'Jonnie Candito', focus: 'Strength Peaking', philosophy: 'Six weeks of strategic periodisation from hypertrophy to strength to peak performance.' },
  },
  // ── STRENGTH — ADDITIONAL ─────────────────────────────────────────────────

  {
    id: 'starting_strength',
    name: 'Starting Strength',
    tagline: 'The most effective beginner barbell program ever written',
    description: 'Mark Rippetoe\'s Starting Strength is the gold-standard beginner barbell program. Three sessions per week, five core lifts, linear progression every single workout. Deceptively simple. Brutally effective. No fluff, no supersets — just add weight to the bar.',
    author: { name: 'Mark Rippetoe', type: 'coach', verified: true },
    category: 'strength',
    subcategory: 'beginner-strength',
    tags: ['beginner', 'barbell', 'linear-progression', 'squat', 'deadlift', 'strength', '3-day', 'novice'],
    durationWeeks: 12,
    sessionsPerWeek: 3,
    sessionDurationMinutes: { min: 45, max: 70 },
    difficulty: 'beginner',
    equipment: ['barbell', 'rack', 'bench'],
    equipmentTier: 'barbell-only',
    goals: ['beginner-strength', 'barbell-mastery', 'linear-progression'],
    metrics: { strengthEmphasis: 90, hypertrophyEmphasis: 45, enduranceEmphasis: 5, conditioningEmphasis: 5, recoveryDemand: 35, weeklyVolumeScore: 35 },
    highlights: ['3 barbell lifts per session', 'Add weight every session', 'Squat 3× per week', 'Proven for 40+ years'],
    expectedOutcomes: ['200lb+ squat for beginners', 'Barbell movement mastery', 'Rapid strength gains', 'Foundation for intermediate training'],
    popularity: 91, rating: 4.6, ratingCount: 4200, completionRate: 0.64, enrolledCount: 18000,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0a00', '#2d1a00'], accentColor: '#f59e0b', icon: '🏋️',
    collections: ['most-popular', 'strength-collection', 'beginner-friendly', 'community-favourites'],
    days: {
      mon: { title: 'Workout A', badge: 'Strength', color: 'var(--accent-amber)', desc: 'Squat, Bench, Deadlift.', runs: 'Rest', lifts: ['Back Squat 3×5', 'Bench Press 3×5', 'Deadlift 1×5'] },
      tue: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest.', runs: 'Rest', lifts: [] },
      wed: { title: 'Workout B', badge: 'Strength', color: 'var(--accent-amber)', desc: 'Squat, Press, Deadlift.', runs: 'Rest', lifts: ['Back Squat 3×5', 'Press 3×5', 'Deadlift 1×5'] },
      thu: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest.', runs: 'Rest', lifts: [] },
      fri: { title: 'Workout A', badge: 'Strength', color: 'var(--accent-amber)', desc: 'Squat, Bench, Deadlift.', runs: 'Rest', lifts: ['Back Squat 3×5', 'Bench Press 3×5', 'Deadlift 1×5'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 5, intensityLabel: 'Start light — form first' },
      '2': { sets: 3, reps: 5, intensityLabel: 'Linear progression' },
      '3': { sets: 3, reps: 5, intensityLabel: 'Linear progression' },
      '4': { sets: 3, reps: 5, intensityLabel: 'Linear progression' },
      '5': { sets: 3, reps: 5, intensityLabel: 'Linear progression' },
      '6': { sets: 3, reps: 5, intensityLabel: 'Linear progression' },
      '7': { sets: 3, reps: 5, intensityLabel: 'Linear progression' },
      '8': { sets: 3, reps: 5, intensityLabel: 'Linear progression' },
      '9': { sets: 3, reps: 5, intensityLabel: 'Linear progression' },
      '10': { sets: 3, reps: 5, intensityLabel: 'Linear progression' },
      '11': { sets: 3, reps: 5, intensityLabel: 'Linear progression' },
      '12': { sets: 3, reps: 5, intensityLabel: 'Test maxes — how far have you come?' },
    },
    dossier: { creator: 'Mark Rippetoe', focus: 'Beginner Strength', philosophy: 'The fastest way to get strong is to squat heavy, deadlift heavy, press heavy, and add weight to the bar every time you train.' },
  },

  {
    id: 'juggernaut_method',
    name: 'Juggernaut Method',
    tagline: 'Wave loading periodization for intermediate lifters',
    description: 'Chad Wesley Smith\'s Juggernaut Method uses a unique wave-loading structure across 4 phases: 10s, 8s, 5s, and 3s. Each wave builds strength across the four main lifts while managing fatigue intelligently. A proven bridge from beginner to advanced powerlifting.',
    author: { name: 'Chad Wesley Smith', type: 'coach', verified: true },
    category: 'strength',
    subcategory: 'powerlifting',
    tags: ['powerlifting', 'intermediate', 'wave-loading', 'periodization', 'squat', 'bench', 'deadlift', 'press', '4-day'],
    durationWeeks: 16,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 60, max: 90 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack', 'bench'],
    equipmentTier: 'barbell-only',
    goals: ['powerlifting', 'strength', 'competition-prep', 'periodization'],
    metrics: { strengthEmphasis: 95, hypertrophyEmphasis: 40, enduranceEmphasis: 5, conditioningEmphasis: 5, recoveryDemand: 65, weeklyVolumeScore: 60 },
    highlights: ['Wave loading structure', '4 distinct phases', 'AMRAP sets built in', 'Volume-to-intensity progression'],
    expectedOutcomes: ['Significant strength PR\'s', 'Periodization mastery', 'Competition-ready total', 'Big three improvement'],
    popularity: 78, rating: 4.6, ratingCount: 870, completionRate: 0.56, enrolledCount: 4200,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0a00', '#2d1a00'], accentColor: '#f59e0b', icon: '🏆',
    collections: ['strength-collection', 'community-favourites'],
    days: {
      mon: { title: 'Squat + Accessory', badge: 'Strength', color: 'var(--accent-amber)', desc: 'Main squat + supplemental work.', runs: 'Rest', lifts: ['Back Squat (Main Sets + AMRAP)', 'Paused Squat', 'Leg Press', 'Hamstring Curl', 'Ab Work'] },
      tue: { title: 'Bench + Accessory', badge: 'Strength', color: 'var(--accent-blue)', desc: 'Main bench + supplemental work.', runs: 'Rest', lifts: ['Bench Press (Main Sets + AMRAP)', 'Close-Grip Bench', 'Tricep Pushdown', 'Cable Row', 'Face Pulls'] },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      thu: { title: 'Deadlift + Accessory', badge: 'Strength', color: 'var(--accent-amber)', desc: 'Main deadlift + supplemental work.', runs: 'Rest', lifts: ['Deadlift (Main Sets + AMRAP)', 'Romanian Deadlift', 'Good Mornings', 'Leg Curl', 'Back Raises'] },
      fri: { title: 'Press + Accessory', badge: 'Strength', color: 'var(--accent-green)', desc: 'Main press + supplemental work.', runs: 'Rest', lifts: ['Standing OHP (Main Sets + AMRAP)', 'Push Press', 'Lateral Raise', 'Tricep Extension', 'Face Pulls'] },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 5, reps: 10, intensityLabel: '10s Wave — Volume Phase' },
      '2': { sets: 5, reps: 10, intensityLabel: '10s Wave — Volume Phase' },
      '3': { sets: 5, reps: 10, intensityLabel: '10s Wave — Peak' },
      '4': { sets: 2, reps: 5, intensityLabel: 'Deload' },
      '5': { sets: 4, reps: 8, intensityLabel: '8s Wave — Volume Phase' },
      '6': { sets: 4, reps: 8, intensityLabel: '8s Wave — Volume Phase' },
      '7': { sets: 4, reps: 8, intensityLabel: '8s Wave — Peak' },
      '8': { sets: 2, reps: 5, intensityLabel: 'Deload' },
      '9': { sets: 3, reps: 5, intensityLabel: '5s Wave — Volume Phase' },
      '10': { sets: 3, reps: 5, intensityLabel: '5s Wave — Intensity Phase' },
      '11': { sets: 3, reps: 5, intensityLabel: '5s Wave — Peak' },
      '12': { sets: 2, reps: 3, intensityLabel: 'Deload' },
      '13': { sets: 3, reps: 3, intensityLabel: '3s Wave — Volume Phase' },
      '14': { sets: 3, reps: 2, intensityLabel: '3s Wave — Intensity Phase' },
      '15': { sets: 3, reps: 1, intensityLabel: '3s Wave — Peak' },
      '16': { sets: 2, reps: 3, intensityLabel: 'Final Deload — competition ready' },
    },
    dossier: { creator: 'Chad Wesley Smith', focus: 'Intermediate Powerlifting', philosophy: 'Wave loading allows progressive volume and intensity across four phases, building towards peak strength at exactly the right time.' },
  },
  // ── MORE POWERLIFTING ─────────────────────────────────────────────────────────

  {
    id: '531_wendler',
    name: '5/3/1 Wendler',
    tagline: "Jim Wendler's legendary 4-week wave progression",
    description: "Jim Wendler's simple but brutally effective strength protocol. Four main lifts across four days with a repeating 4-week wave of 5s, 3s, and singles. The final AMRAP set is where the real progress lives. Add 2.5–5kg per cycle and watch your numbers climb indefinitely.",
    author: { name: 'Jim Wendler', type: 'coach', verified: true },
    source: 'coach',
    category: 'powerlifting',
    subcategory: '5-3-1',
    tags: ['531', '5-3-1', 'wendler', 'powerlifting', 'strength', 'barbell', 'intermediate', 'amrap', 'wave-loading'],
    durationWeeks: 16,
    sessionsPerWeek: 4,
    sessionDurationMinutes: { min: 55, max: 75 },
    difficulty: 'intermediate',
    equipment: ['barbell', 'rack', 'bench'],
    equipmentTier: 'gym',
    goals: ['strength', 'powerlifting', 'main-lift-progress', '1rm-improvement'],
    metrics: { strengthEmphasis: 92, hypertrophyEmphasis: 30, enduranceEmphasis: 5, conditioningEmphasis: 5, recoveryDemand: 60, weeklyVolumeScore: 55 },
    highlights: ['4-week wave progression', 'AMRAP final sets build confidence', '4 main lifts only', 'Proven over 15+ years'],
    expectedOutcomes: ['Consistent strength progress', 'New 1RMs on all main lifts', 'Mental toughness under load', 'Long-term strength base'],
    popularity: 89, rating: 4.8, ratingCount: 1234, completionRate: 0.62, enrolledCount: 7800,
    featured: false, verified: true, isNew: false,
    coverGradient: ['#1a0a0a', '#3d1515'], accentColor: '#dc2626', icon: '🔱',
    collections: ['strength-collection', 'powerlifting-collection', 'most-popular', 'highest-rated', 'coach-created'],
    days: {
      mon: {
        title: 'OHP Day', badge: '5/3/1', color: 'var(--accent-blue)',
        desc: 'Overhead Press wave + press accessories.', runs: 'Rest',
        lifts: ['Standing OHP', 'Pull-Ups', 'DB Shoulder Press', 'Lateral Raise', 'Tricep Band Pushdown'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Standing OHP (Wave)',   sets: 3, reps: '5/3/1+', rpe: 9,   rest: '3 min',  notes: 'Week 1: 65/75/85%. Week 2: 70/80/90%. Week 3: 75/85/95%. + = AMRAP on final set' },
            { exercise: 'Pull-Ups',              sets: 5, reps: 'Max',    rpe: 8,   rest: '2 min' },
            { exercise: 'DB Shoulder Press',     sets: 3, reps: '10–15',  rpe: 6.5, rest: '90 sec' },
            { exercise: 'Lateral Raise',         sets: 3, reps: '15–20',  rpe: 6,   rest: '60 sec' },
            { exercise: 'Tricep Band Pushdown',  sets: 3, reps: '15–20',  rpe: 6,   rest: '60 sec' },
          ],
        },
      },
      tue: {
        title: 'Deadlift Day', badge: '5/3/1', color: 'var(--accent-green)',
        desc: 'Deadlift wave + lower body accessories.', runs: 'Rest',
        lifts: ['Deadlift', 'Romanian Deadlift', 'Leg Press', 'Barbell Row', 'Face Pull'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Deadlift (Wave)',    sets: 3, reps: '5/3/1+', rpe: 9,   rest: '4 min',  notes: 'Pull as many reps as possible on the final set. This is where the gains live.' },
            { exercise: 'Romanian Deadlift', sets: 4, reps: '10–12',   rpe: 7,   rest: '2 min' },
            { exercise: 'Leg Press',         sets: 3, reps: '10–15',   rpe: 6.5, rest: '2 min' },
            { exercise: 'Barbell Row',       sets: 4, reps: '10–15',   rpe: 6.5, rest: '90 sec' },
            { exercise: 'Face Pull',         sets: 3, reps: '15–20',   rpe: 6,   rest: '60 sec' },
          ],
        },
      },
      wed: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Full rest day — recovery is where adaptation happens.', runs: 'Rest', lifts: [] },
      thu: {
        title: 'Bench Day', badge: '5/3/1', color: 'var(--accent-blue)',
        desc: 'Bench Press wave + upper body accessories.', runs: 'Rest',
        lifts: ['Bench Press', 'Incline DB Press', 'Tricep Band Pushdown', 'Barbell Row', 'Barbell Curl'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Bench Press (Wave)',   sets: 3, reps: '5/3/1+', rpe: 9,   rest: '3 min',  notes: 'Hit the AMRAP on the final set. Aim to beat last cycle\'s rep count.' },
            { exercise: 'Incline DB Press',     sets: 4, reps: '10–15',  rpe: 7,   rest: '90 sec' },
            { exercise: 'Tricep Band Pushdown', sets: 4, reps: '15–20',  rpe: 6,   rest: '60 sec' },
            { exercise: 'Barbell Row',          sets: 4, reps: '10–15',  rpe: 6.5, rest: '90 sec' },
            { exercise: 'Barbell Curl',         sets: 3, reps: '10–15',  rpe: 6.5, rest: '60 sec' },
          ],
        },
      },
      fri: {
        title: 'Squat Day', badge: '5/3/1', color: 'var(--accent-green)',
        desc: 'Back Squat wave + leg accessories.', runs: 'Rest',
        lifts: ['Back Squat', 'Romanian Deadlift', 'Bulgarian Split Squat', 'Leg Curl', 'Calf Raises'],
        workoutPreview: {
          type: 'STRENGTH',
          exercises: [
            { exercise: 'Back Squat (Wave)',    sets: 3, reps: '5/3/1+', rpe: 9,   rest: '4 min',  notes: 'AMRAP on the final set. Full depth. Stay patient between reps.' },
            { exercise: 'Romanian Deadlift',   sets: 4, reps: '10–12',   rpe: 7,   rest: '2 min' },
            { exercise: 'Bulgarian Split Squat', sets: 3, reps: '10–12', rpe: 7,   rest: '2 min' },
            { exercise: 'Leg Curl',            sets: 3, reps: '12–15',   rpe: 6.5, rest: '90 sec' },
            { exercise: 'Calf Raises',         sets: 4, reps: '15–20',   rpe: 6,   rest: '60 sec' },
          ],
        },
      },
      sat: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day.', runs: 'Rest', lifts: [] },
      sun: { title: 'Rest', badge: 'Recovery', color: 'var(--text-muted)', desc: 'Rest day.', runs: 'Rest', lifts: [] },
    },
    weeklyVolModifiers: {
      '1': { sets: 3, reps: 5, intensityLabel: 'Week 1: 3×5 — 65/75/85% + AMRAP' },
      '2': { sets: 3, reps: 3, intensityLabel: 'Week 2: 3×3 — 70/80/90% + AMRAP' },
      '3': { sets: 3, reps: 1, intensityLabel: 'Week 3: 5/3/1 — 75/85/95% + AMRAP' },
      '4': { sets: 3, reps: 5, intensityLabel: 'Week 4: Deload — 40/50/60%' },
      '5': { sets: 3, reps: 5, intensityLabel: 'Cycle 2 — +2.5kg upper / +5kg lower' },
      '6': { sets: 3, reps: 3, intensityLabel: 'Cycle 2 — 3s week' },
      '7': { sets: 3, reps: 1, intensityLabel: 'Cycle 2 — 1s week + AMRAP PR' },
      '8': { sets: 3, reps: 5, intensityLabel: 'Deload' },
      '9': { sets: 3, reps: 5, intensityLabel: 'Cycle 3 — loading continues' },
      '10': { sets: 3, reps: 3, intensityLabel: 'Cycle 3 — 3s week' },
      '11': { sets: 3, reps: 1, intensityLabel: 'Cycle 3 — 1s week + AMRAP PR' },
      '12': { sets: 3, reps: 5, intensityLabel: 'Deload' },
      '13': { sets: 3, reps: 5, intensityLabel: 'Cycle 4 begins' },
      '14': { sets: 3, reps: 3, intensityLabel: 'Cycle 4 — 3s week' },
      '15': { sets: 3, reps: 1, intensityLabel: 'Cycle 4 — 1s week peak AMRAP' },
      '16': { sets: 3, reps: 5, intensityLabel: 'Final deload — evaluate next training max' },
    },
    dossier: { creator: 'Jim Wendler', focus: 'Strength', philosophy: "If it isn't simple and based around heavy, basic exercises, I don't want to do it. Get strong. Everything else will follow." },
  },

];
