// Regenerates js/vendor/fit-parser.js — a self-contained ESM bundle of
// fit-file-parser + its Buffer polyfill, so FIT import runs from our own origin
// under the strict CSP with NO remote (esm.sh) code in the privileged WebView.
// Run: node scripts/vendor-fit.mjs   (see package.json "vendor:fit")
import { build } from 'esbuild';
import { writeFileSync } from 'node:fs';

const entry = `
import FitParser from 'fit-file-parser';
import { Buffer } from 'buffer';
export { FitParser, Buffer };
`;

const res = await build({
  stdin: { contents: entry, resolveDir: process.cwd(), sourcefile: 'fit-entry.js' },
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: ['es2020'],
  legalComments: 'none',
  define: { 'process.env.NODE_ENV': '"production"', global: 'globalThis' },
  write: false,
});
const banner = '// VENDORED — generated by scripts/vendor-fit.mjs. Do not edit by hand.\n'
  + '// Sources: fit-file-parser@3.0.2 + buffer@6.0.3 (both MIT). Bundled to keep\n'
  + '// FIT import free of remote code under the app CSP.\n';
writeFileSync('js/vendor/fit-parser.js', banner + res.outputFiles[0].text);
console.log('Wrote js/vendor/fit-parser.js (' + res.outputFiles[0].text.length + ' bytes)');
